Silveridge_Refuge_MapScripts::
	.byte 0


Silveridge_Refuge_EventScript_ImWorried::
# 6 "data/maps/Silveridge_Refuge/scripts.pory"
	speakername Silveridge_Refuge_EventScript_ImWorried_Text_0
# 7 "data/maps/Silveridge_Refuge/scripts.pory"
	msgbox Silveridge_Refuge_EventScript_ImWorried_Text_1, MSGBOX_NPC
	return


Silveridge_Refuge_EventScript_ImWorried_Text_0:
# 6 "data/maps/Silveridge_Refuge/scripts.pory"
	.string "Woman$"

Silveridge_Refuge_EventScript_ImWorried_Text_1:
# 8 "data/maps/Silveridge_Refuge/scripts.pory"
	.string "The whole town trembles from the\n"
	.string "Volcano's quakes…\p"
	.string "I'm so worried…$"
