Silveridge_Refuge_MapScripts::
	.byte 0


Silveridge_Refuge_EventScript_ImWorried::
# 6 "data/maps/Silveridge_Refuge/scripts.pory"
	speakername Silveridge_Refuge_EventScript_ImWorried_Text_0
# 7 "data/maps/Silveridge_Refuge/scripts.pory"
	msgbox Silveridge_Refuge_EventScript_ImWorried_Text_1, MSGBOX_NPC
	return


Silveridge_Refuge_EventScript_Firebringer::
# 14 "data/maps/Silveridge_Refuge/scripts.pory"
	speakername Silveridge_Refuge_EventScript_Firebringer_Text_0
# 15 "data/maps/Silveridge_Refuge/scripts.pory"
	msgbox Silveridge_Refuge_EventScript_Firebringer_Text_1, MSGBOX_NPC
	return


Silveridge_Refuge_EventScript_ImWorried_Text_0:
# 6 "data/maps/Silveridge_Refuge/scripts.pory"
	.string "Woman$"

Silveridge_Refuge_EventScript_ImWorried_Text_1:
# 8 "data/maps/Silveridge_Refuge/scripts.pory"
	.string "The whole town trembles from the\n"
	.string "Volcano's quakes…\p"
	.string "I'm so worried…$"

Silveridge_Refuge_EventScript_Firebringer_Text_0:
# 14 "data/maps/Silveridge_Refuge/scripts.pory"
	.string "Firebringer$"

Silveridge_Refuge_EventScript_Firebringer_Text_1:
# 16 "data/maps/Silveridge_Refuge/scripts.pory"
	.string "I'm bringin' down some Slugma today,\n"
	.string "freshly caught on Burnfoot Pass this\l"
	.string "mornin'.\p"
	.string "Tomorrow I'll be back up there,\n"
	.string "catching some more of 'em.$"
