PokemonMansionF1_MapScripts::
	.byte 0

Mewtwo_Statue::
	msgbox Mewtwo_Statue_Text, MSGBOX_SIGN
	end

Mewtwo_Journal_1::
	msgbox Mewtwo_Journal_1_Text, MSGBOX_SIGN
	end

Mewtwo_Journal_2::
	msgbox Mewtwo_Journal_2_Text, MSGBOX_SIGN
	end

Mewtwo_Journal_3::
	msgbox Mewtwo_Journal_3_Text, MSGBOX_SIGN
	end

Mewtwo_Journal_4::
	msgbox Mewtwo_Journal_4_Text, MSGBOX_SIGN
	end

Deoxys_Journal_1::
	msgbox Deoxys_Journal_1_Text, MSGBOX_SIGN
	end

Deoxys_Journal_2::
	msgbox Deoxys_Journal_2_Text, MSGBOX_SIGN
	end

Deoxys_Journal_3::
	msgbox Deoxys_Journal_3_Text, MSGBOX_SIGN
	end

Deoxys_Journal_4::
	msgbox Deoxys_Journal_4_Text, MSGBOX_SIGN
	end

Deoxys_Journal_5::
	msgbox Deoxys_Journal_5_Text, MSGBOX_SIGN
	end

Mewtwo_Statue_Text::
    .string "It's a POKéMON statue.\n"
    .string "It gives the shivers.$"

Mewtwo_Journal_1_Text::
    .string "Diary: July 5\n"
    .string "FARAWAY ISLAND\p"
    .string "A new POKéMON was discovered deep\n"
    .string "in the jungle.$"

Mewtwo_Journal_2_Text::
    .string "Diary: July 10\n"
    .string "We christened the newly discovered\l"
    .string "POKéMON, MEW.$"

Mewtwo_Journal_3_Text::
    .string "Diary: Feb. 6\n"
    .string "MEW gave birth.\p"
    .string "We named the newborn MEWTWO.$"

Mewtwo_Journal_4_Text::
    .string "Diary: Sept. 1\n"
    .string "MEWTWO is far too powerful.\p"
    .string "We have failed to curb its vicious\n"
    .string "tendencies…$"

Deoxys_Journal_1_Text::
    .string "Observation no.12\n"
    .string "The exposure of the METEORITE to a\p"
    .string "certain type of light seems to generate\n"
    .string "small, short-lived life forms.$"

Deoxys_Journal_2_Text::
    .string "Observation no.18\l"
    .string "Under prolonged and more intense\n"
    .string "exposure, the life forms seem to\p"
    .string "intertwine to generate a more complex\l"
    .string "one, it is difficult to determine its\n"
    .string "nature.\p"
    .string "The life form has been named\n"
    .string "ORGANISM NO.1$"

Deoxys_Journal_3_Text::
    .string "Observation no.26\n"
    .string "ORGANISM NO.1 is evolving very rapidly,\p"
    .string "the laboratory is not equipped to\n"
    .string "contain it and in our haste we had to\p"
    .string "finish the ORGANISM before it could\n"
    .string "become too powerful.$"

Deoxys_Journal_4_Text::
    .string "Observation no.33\n"
    .string "The government threatens to close the\p"
    .string "laboratory if the required biological\n"
    .string "weapon is not recreated.\p"
    .string "The METEORITE luckily appears to be\n"
    .string "a fragment of a larger rock.\p"
    .string "We hypothesize that it could be divided\n"
    .string "into three pieces.\p"
    .string "One fell here, on BIRTH ISLAND,\n"
    .string "the second in HOENN, in METEOR FALLS\p"
    .string "area and the third, contingently the\n"
    .string "largest, in an unknown location.$"

Deoxys_Journal_5_Text::
    .string "Looks like the remains of ORGANISM NO.1$"