#ifndef GUARD_ITEM_CONSTANTS_H
#define GUARD_ITEM_CONSTANTS_H

#include "config/item.h"

// These constants are used in gItemsInfo
enum {
    POCKET_NONE,
    POCKET_ITEMS,
#if I_POCKET_MEDICINE_ENABLED == TRUE
    POCKET_MEDICINE,
#endif
    POCKET_POKE_BALLS,
#if I_POCKET_BATTLE_ITEMS_ENABLED == TRUE
    POCKET_BATTLE_ITEMS,
#endif
    POCKET_TM_HM,
#if I_POCKET_POWER_UP_ENABLED == TRUE
    POCKET_POWER_UP,
#endif
    POCKET_BERRIES,
#if I_POCKET_TREASURES_ENABLED == TRUE
    POCKET_TREASURES,
#endif
#if I_POCKET_MEGA_STONES_ENABLED == TRUE
    POCKET_MEGA_STONES,
#endif
#if I_POCKET_Z_CRYSTALS_ENABLED == TRUE
    POCKET_Z_CRYSTALS,
#endif
    POCKET_KEY_ITEMS,
};

// Default to POCKET_ITEMS if the specified pocket is disabled.
#if !I_POCKET_MEDICINE_ENABLED
#define POCKET_MEDICINE POCKET_ITEMS
#endif
#if !I_POCKET_BATTLE_ITEMS_ENABLED
#define POCKET_BATTLE_ITEMS POCKET_ITEMS
#endif
#if !I_POCKET_POWER_UP_ENABLED
#define POCKET_POWER_UP POCKET_ITEMS
#endif
#if !I_POCKET_TREASURES_ENABLED
#define POCKET_TREASURES POCKET_ITEMS
#endif
#if !I_POCKET_MEGA_STONES_ENABLED
#define POCKET_MEGA_STONES POCKET_BATTLE_ITEMS
#endif
#if !I_POCKET_Z_CRYSTALS_ENABLED
#define POCKET_Z_CRYSTALS POCKET_BATTLE_ITEMS
#endif

enum {
    ITEMS_POCKET,
#if I_POCKET_MEDICINE_ENABLED == TRUE
    MEDICINE_POCKET,
#endif
    BALLS_POCKET,
#if I_POCKET_BATTLE_ITEMS_ENABLED == TRUE
    BATTLEITEMS_POCKET,
#endif
    TMHM_POCKET,
#if I_POCKET_POWER_UP_ENABLED == TRUE
    POWERUP_POCKET,
#endif
    BERRIES_POCKET,
#if I_POCKET_TREASURES_ENABLED == TRUE
    TREASURES_POCKET,
#endif
#if I_POCKET_MEGA_STONES_ENABLED == TRUE
    MEGASTONES_POCKET,
#endif
#if I_POCKET_Z_CRYSTALS_ENABLED == TRUE
    ZCRYSTALS_POCKET,
#endif
    KEYITEMS_POCKET,
    POCKETS_COUNT,
};

#define REPEL_LURE_MASK         (1 << 15)
#define IS_LAST_USED_LURE(var)  (var & REPEL_LURE_MASK)
#define REPEL_LURE_STEPS(var)   (var & (REPEL_LURE_MASK - 1))
#define LURE_STEP_COUNT         (IS_LAST_USED_LURE(VarGet(VAR_REPEL_STEP_COUNT)) ? REPEL_LURE_STEPS(VarGet(VAR_REPEL_STEP_COUNT)) : 0)
#define REPEL_STEP_COUNT        (!IS_LAST_USED_LURE(VarGet(VAR_REPEL_STEP_COUNT)) ? REPEL_LURE_STEPS(VarGet(VAR_REPEL_STEP_COUNT)) : 0)

#endif // GUARD_ITEM_CONSTANTS_H
