#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_TownsAndRoutes
#define MAP_PETALBURG_CITY                        (0 | (0 << 8))
#define MAP_SLATEPORT_CITY                        (1 | (0 << 8))
#define MAP_MAUVILLE_CITY                         (2 | (0 << 8))
#define MAP_RUSTBORO_CITY                         (3 | (0 << 8))
#define MAP_FORTREE_CITY                          (4 | (0 << 8))
#define MAP_LILYCOVE_CITY                         (5 | (0 << 8))
#define MAP_MOSSDEEP_CITY                         (6 | (0 << 8))
#define MAP_SOOTOPOLIS_CITY                       (7 | (0 << 8))
#define MAP_EVER_GRANDE_CITY                      (8 | (0 << 8))
#define MAP_LITTLEROOT_TOWN                       (9 | (0 << 8))
#define MAP_OLDALE_TOWN                           (10 | (0 << 8))
#define MAP_DEWFORD_TOWN                          (11 | (0 << 8))
#define MAP_LAVARIDGE_TOWN                        (12 | (0 << 8))
#define MAP_FALLARBOR_TOWN                        (13 | (0 << 8))
#define MAP_VERDANTURF_TOWN                       (14 | (0 << 8))
#define MAP_PACIFIDLOG_TOWN                       (15 | (0 << 8))
#define MAP_ROUTE101                              (16 | (0 << 8))
#define MAP_ROUTE102                              (17 | (0 << 8))
#define MAP_ROUTE103                              (18 | (0 << 8))
#define MAP_ROUTE104                              (19 | (0 << 8))
#define MAP_ROUTE105                              (20 | (0 << 8))
#define MAP_ROUTE106                              (21 | (0 << 8))
#define MAP_ROUTE107                              (22 | (0 << 8))
#define MAP_ROUTE108                              (23 | (0 << 8))
#define MAP_ROUTE109                              (24 | (0 << 8))
#define MAP_ROUTE110                              (25 | (0 << 8))
#define MAP_ROUTE111                              (26 | (0 << 8))
#define MAP_ROUTE112                              (27 | (0 << 8))
#define MAP_ROUTE113                              (28 | (0 << 8))
#define MAP_ROUTE114                              (29 | (0 << 8))
#define MAP_ROUTE115                              (30 | (0 << 8))
#define MAP_ROUTE116                              (31 | (0 << 8))
#define MAP_ROUTE117                              (32 | (0 << 8))
#define MAP_ROUTE118                              (33 | (0 << 8))
#define MAP_ROUTE119                              (34 | (0 << 8))
#define MAP_ROUTE120                              (35 | (0 << 8))
#define MAP_ROUTE121                              (36 | (0 << 8))
#define MAP_ROUTE122                              (37 | (0 << 8))
#define MAP_ROUTE123                              (38 | (0 << 8))
#define MAP_ROUTE124                              (39 | (0 << 8))
#define MAP_ROUTE125                              (40 | (0 << 8))
#define MAP_ROUTE126                              (41 | (0 << 8))
#define MAP_ROUTE127                              (42 | (0 << 8))
#define MAP_ROUTE128                              (43 | (0 << 8))
#define MAP_ROUTE129                              (44 | (0 << 8))
#define MAP_ROUTE130                              (45 | (0 << 8))
#define MAP_ROUTE131                              (46 | (0 << 8))
#define MAP_ROUTE132                              (47 | (0 << 8))
#define MAP_ROUTE133                              (48 | (0 << 8))
#define MAP_ROUTE134                              (49 | (0 << 8))
#define MAP_UNDERWATER_ROUTE124                   (50 | (0 << 8))
#define MAP_UNDERWATER_ROUTE126                   (51 | (0 << 8))
#define MAP_UNDERWATER_ROUTE127                   (52 | (0 << 8))
#define MAP_UNDERWATER_ROUTE128                   (53 | (0 << 8))
#define MAP_UNDERWATER_ROUTE129                   (54 | (0 << 8))
#define MAP_UNDERWATER_ROUTE105                   (55 | (0 << 8))
#define MAP_UNDERWATER_ROUTE125                   (56 | (0 << 8))
#define MAP_SUNRISE_VILLAGE                       (57 | (0 << 8))
#define MAP_SUNRISE_VILLAGE_BEACH                 (58 | (0 << 8))
#define MAP_CHII_TOWN                             (59 | (0 << 8))
#define MAP_TRANQUIL_ROUTE                        (60 | (0 << 8))
#define MAP_SAKU_TOWN                             (61 | (0 << 8))
#define MAP_KURA_TOWN                             (62 | (0 << 8))
#define MAP_BEACHBOUND_ROUTE                      (63 | (0 << 8))
#define MAP_MAGURO_HARBOR                         (64 | (0 << 8))
#define MAP_WINDSWEPT_ROUTE                       (65 | (0 << 8))
#define MAP_SUNRISE_VILLAGE_PLAYERS_HOUSE_BEDROOM (66 | (0 << 8))
#define MAP_SILVERIDGE                            (67 | (0 << 8))
#define MAP_WINDY_CAPE                            (68 | (0 << 8))
#define MAP_WHITESLATE_ROUTE                      (69 | (0 << 8))
#define MAP_YIFU_CITY                             (70 | (0 << 8))
#define MAP_BELVEDERE_ROUTE                       (71 | (0 << 8))
#define MAP_SOULKEEP                              (72 | (0 << 8))
#define MAP_ORCHARD_PATH                          (73 | (0 << 8))
#define MAP_SEASTROLL_CHANNEL                     (74 | (0 << 8))
#define MAP_SCENIC_ROUTE                          (75 | (0 << 8))
#define MAP_SABERSIDE_TOWN                        (76 | (0 << 8))
#define MAP_HARVEST_SHRINE                        (77 | (0 << 8))
#define MAP_SOULKEEP_GRAVEYARD                    (78 | (0 << 8))
#define MAP_BEACHBOUND_ROUTE_DECAY                (79 | (0 << 8))
#define MAP_SABERSIDE_CHANNEL                     (80 | (0 << 8))
#define MAP_COREEF_ISLE                           (81 | (0 << 8))
#define MAP_OPEN_SEA_CORAL                        (82 | (0 << 8))
#define MAP_OPEN_SEA_HAVEN                        (83 | (0 << 8))
#define MAP_OPEN_SEA_ICY                          (84 | (0 << 8))
#define MAP_OPEN_SEA_LEAGUE                       (85 | (0 << 8))
#define MAP_HAVEN_ISLE                            (86 | (0 << 8))
#define MAP_MIDDLE_ISLE                           (87 | (0 << 8))
#define MAP_TOP_ISLE                              (88 | (0 << 8))
#define MAP_LONGTIDE_CHANNEL                      (89 | (0 << 8))
#define MAP_LONG_TIDE_CHANNEL_SOULKEEP            (90 | (0 << 8))
#define MAP_SEA_TURF_ROUTE                        (91 | (0 << 8))
#define MAP_HANABI_CITY                           (92 | (0 << 8))
#define MAP_PUDDLE_PATH                           (93 | (0 << 8))
#define MAP_DRAGONS_PASS                          (94 | (0 << 8))
#define MAP_DRYUGON                               (95 | (0 << 8))
#define MAP_BURNFOOT_PASS_BOTTOM                  (96 | (0 << 8))
#define MAP_STEEPSTONE_PASS_BOTTOM                (97 | (0 << 8))
#define MAP_BURNFOOT_PASS                         (98 | (0 << 8))
#define MAP_MT_KAZAN_EXTERIOR                     (99 | (0 << 8))
#define MAP_STEEPSTONE_PASS                       (100 | (0 << 8))
#define MAP_SHOGUNATE                             (101 | (0 << 8))
#define MAP_SCENIC_ROUTE_SABERSIDE                (102 | (0 << 8))
#define MAP_WINDY_CAPE2                           (103 | (0 << 8))

// gMapGroup_IndoorSunriseVillage
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F             (0 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F             (1 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F                 (2 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F                 (3 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB          (4 | (1 << 8))
#define MAP_SUNRISE_VILLAGE_PLAYERS_HOUSE_LR              (5 | (1 << 8))
#define MAP_SUNRISE_VILLAGE_ELDERS_HOUSE                  (6 | (1 << 8))
#define MAP_SUNRISE_VILLAGE_ELDERS_HOUSE_PRIVATE_QUARTERS (7 | (1 << 8))
#define MAP_SUNRISE_VILLAGE_RIVALS_HOUSE                  (8 | (1 << 8))
#define MAP_SUNRISE_VILLAGE_HOUSE1                        (9 | (1 << 8))

// gMapGroup_IndoorChii
#define MAP_CHII_TOWN_HOUSE1         (0 | (2 << 8))
#define MAP_CHII_TOWN_HOUSE2         (1 | (2 << 8))
#define MAP_CHII_TOWN_SCHOOL         (2 | (2 << 8))
#define MAP_CHII_TOWN_POKEMON_CENTER (3 | (2 << 8))

// gMapGroup_IndoorTranquilRoute
#define MAP_TRANQUIL_ROUTE_CUT_HOUSE (0 | (3 << 8))

// gMapGroup_IndoorSaku
#define MAP_SAKU_TOWN_POKEMON_CENTER (0 | (4 << 8))
#define MAP_SAKU_TOWN_BONSAI_SHOP    (1 | (4 << 8))
#define MAP_SAKU_TOWN_HOUSE1         (2 | (4 << 8))
#define MAP_SAKU_TOWN_HOUSE2         (3 | (4 << 8))
#define MAP_SAKU_TOWN_HOUSE3         (4 | (4 << 8))

// gMapGroup_IndoorKura
#define MAP_KURA_TOWN_HOUSE1 (0 | (5 << 8))
#define MAP_KURA_TOWN_HOUSE2 (1 | (5 << 8))
#define MAP_KURA_TOWN_HOUSE3 (2 | (5 << 8))
#define MAP_KURA_TOWN_DOJO   (3 | (5 << 8))

// gMapGroup_IndoorBeachboundRoute
#define MAP_BEACHBOUND_MAGURO_GATE (0 | (6 << 8))
#define MAP_KURA_BEACHBOUND_GATE   (1 | (6 << 8))

// gMapGroup_IndoorMaguro
#define MAP_MAGURO_HARBOR_HOUSE1 (0 | (7 << 8))
#define MAP_MAGURO_HARBOR_DOJO   (1 | (7 << 8))
#define MAP_MAGURO_HARBOR_HOUSE2 (2 | (7 << 8))
#define MAP_MAGURO_HARBOR_REFUGE (3 | (7 << 8))

// gMapGroup_IndoorSilveridge
#define MAP_SILVERIDGE_SCULPTORS_HOUSE (0 | (8 << 8))
#define MAP_SILVERIDGE_ELDERS_HOUSE    (1 | (8 << 8))
#define MAP_SILVERIDGE_HOUSE1          (2 | (8 << 8))
#define MAP_SILVERIDGE_REFUGE          (3 | (8 << 8))

// gMapGroup_IndoorOldale
#define MAP_OLDALE_TOWN_HOUSE1            (0 | (9 << 8))
#define MAP_OLDALE_TOWN_HOUSE2            (1 | (9 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F (2 | (9 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F (3 | (9 << 8))
#define MAP_OLDALE_TOWN_MART              (4 | (9 << 8))

// gMapGroup_IndoorDewford
#define MAP_DEWFORD_TOWN_HOUSE1            (0 | (10 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F (1 | (10 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F (2 | (10 << 8))
#define MAP_DEWFORD_TOWN_GYM               (3 | (10 << 8))
#define MAP_DEWFORD_TOWN_HALL              (4 | (10 << 8))
#define MAP_DEWFORD_TOWN_HOUSE2            (5 | (10 << 8))

// gMapGroup_IndoorLavaridge
#define MAP_LAVARIDGE_TOWN_HERB_SHOP         (0 | (11 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_1F            (1 | (11 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F           (2 | (11 << 8))
#define MAP_LAVARIDGE_TOWN_HOUSE             (3 | (11 << 8))
#define MAP_LAVARIDGE_TOWN_MART              (4 | (11 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (5 | (11 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F (6 | (11 << 8))

// gMapGroup_IndoorFallarbor
#define MAP_FALLARBOR_TOWN_MART                    (0 | (12 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (12 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (12 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (12 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       (4 | (12 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       (5 | (12 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (6 | (12 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (7 | (12 << 8))

// gMapGroup_IndoorVerdanturf
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (13 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (13 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (13 << 8))
#define MAP_VERDANTURF_TOWN_MART                    (3 | (13 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       (4 | (13 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       (5 | (13 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (6 | (13 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (7 | (13 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE                   (8 | (13 << 8))

// gMapGroup_IndoorPacifidlog
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0 | (14 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (1 | (14 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1            (2 | (14 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2            (3 | (14 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3            (4 | (14 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4            (5 | (14 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5            (6 | (14 << 8))

// gMapGroup_IndoorPetalburg
#define MAP_PETALBURG_CITY_WALLYS_HOUSE      (0 | (15 << 8))
#define MAP_PETALBURG_CITY_GYM               (1 | (15 << 8))
#define MAP_PETALBURG_CITY_HOUSE1            (2 | (15 << 8))
#define MAP_PETALBURG_CITY_HOUSE2            (3 | (15 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (4 | (15 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (5 | (15 << 8))
#define MAP_PETALBURG_CITY_MART              (6 | (15 << 8))

// gMapGroup_IndoorSlateport
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F      (0 | (16 << 8))
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F      (1 | (16 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY       (2 | (16 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR    (3 | (16 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM (4 | (16 << 8))
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE       (5 | (16 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB        (6 | (16 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F       (7 | (16 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F       (8 | (16 << 8))
#define MAP_SLATEPORT_CITY_HARBOR                  (9 | (16 << 8))
#define MAP_SLATEPORT_CITY_HOUSE                   (10 | (16 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F       (11 | (16 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F       (12 | (16 << 8))
#define MAP_SLATEPORT_CITY_MART                    (13 | (16 << 8))

// gMapGroup_IndoorMauville
#define MAP_MAUVILLE_CITY_GYM               (0 | (17 << 8))
#define MAP_MAUVILLE_CITY_BIKE_SHOP         (1 | (17 << 8))
#define MAP_MAUVILLE_CITY_HOUSE1            (2 | (17 << 8))
#define MAP_MAUVILLE_CITY_GAME_CORNER       (3 | (17 << 8))
#define MAP_MAUVILLE_CITY_HOUSE2            (4 | (17 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F (5 | (17 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F (6 | (17 << 8))
#define MAP_MAUVILLE_CITY_MART              (7 | (17 << 8))

// gMapGroup_IndoorRustboro
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F     (0 | (18 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F     (1 | (18 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F     (2 | (18 << 8))
#define MAP_RUSTBORO_CITY_GYM               (3 | (18 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL    (4 | (18 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F (5 | (18 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F (6 | (18 << 8))
#define MAP_RUSTBORO_CITY_MART              (7 | (18 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_1F          (8 | (18 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_2F          (9 | (18 << 8))
#define MAP_RUSTBORO_CITY_HOUSE1            (10 | (18 << 8))
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE     (11 | (18 << 8))
#define MAP_RUSTBORO_CITY_HOUSE2            (12 | (18 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F          (13 | (18 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F          (14 | (18 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F          (15 | (18 << 8))
#define MAP_RUSTBORO_CITY_HOUSE3            (16 | (18 << 8))

// gMapGroup_IndoorFortree
#define MAP_FORTREE_CITY_HOUSE1            (0 | (19 << 8))
#define MAP_FORTREE_CITY_GYM               (1 | (19 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F (2 | (19 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F (3 | (19 << 8))
#define MAP_FORTREE_CITY_MART              (4 | (19 << 8))
#define MAP_FORTREE_CITY_HOUSE2            (5 | (19 << 8))
#define MAP_FORTREE_CITY_HOUSE3            (6 | (19 << 8))
#define MAP_FORTREE_CITY_HOUSE4            (7 | (19 << 8))
#define MAP_FORTREE_CITY_HOUSE5            (8 | (19 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP   (9 | (19 << 8))

// gMapGroup_IndoorLilycove
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        (0 | (20 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        (1 | (20 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        (2 | (20 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        (3 | (20 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY             (4 | (20 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL              (5 | (20 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F         (6 | (20 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F         (7 | (20 << 8))
#define MAP_LILYCOVE_CITY_UNUSED_MART               (8 | (20 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  (9 | (20 << 8))
#define MAP_LILYCOVE_CITY_HARBOR                    (10 | (20 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       (11 | (20 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                    (12 | (20 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                    (13 | (20 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                    (14 | (20 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                    (15 | (20 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       (16 | (20 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       (17 | (20 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       (18 | (20 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       (19 | (20 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       (20 | (20 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  (21 | (20 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (22 | (20 << 8))

// gMapGroup_IndoorMossdeep
#define MAP_MOSSDEEP_CITY_GYM               (0 | (21 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE1            (1 | (21 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2            (2 | (21 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F (3 | (21 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F (4 | (21 << 8))
#define MAP_MOSSDEEP_CITY_MART              (5 | (21 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3            (6 | (21 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE     (7 | (21 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4            (8 | (21 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F   (9 | (21 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F   (10 | (21 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F    (11 | (21 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F   (12 | (21 << 8))

// gMapGroup_IndoorSootopolis
#define MAP_SOOTOPOLIS_CITY_GYM_1F                   (0 | (22 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_B1F                  (1 | (22 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F        (2 | (22 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F        (3 | (22 << 8))
#define MAP_SOOTOPOLIS_CITY_MART                     (4 | (22 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE1                   (5 | (22 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE2                   (6 | (22 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE3                   (7 | (22 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE4                   (8 | (22 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE5                   (9 | (22 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE6                   (10 | (22 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE7                   (11 | (22 << 8))
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE   (12 | (22 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  (13 | (22 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (14 | (22 << 8))

// gMapGroup_IndoorEverGrande
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (23 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (23 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (23 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (23 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (23 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (23 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (23 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (23 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (23 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (23 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (23 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (23 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (12 | (23 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (13 | (23 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (14 | (23 << 8))

// gMapGroup_IndoorRoute104
#define MAP_ROUTE104_MR_BRINEYS_HOUSE         (0 | (24 << 8))
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP (1 | (24 << 8))

// gMapGroup_IndoorRoute111
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE (0 | (25 << 8))
#define MAP_ROUTE111_OLD_LADYS_REST_STOP     (1 | (25 << 8))

// gMapGroup_IndoorRoute112
#define MAP_ROUTE112_CABLE_CAR_STATION   (0 | (26 << 8))
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION (1 | (26 << 8))

// gMapGroup_IndoorRoute114
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE  (0 | (27 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL (1 | (27 << 8))
#define MAP_ROUTE114_LANETTES_HOUSE        (2 | (27 << 8))

// gMapGroup_IndoorRoute116
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE (0 | (28 << 8))

// gMapGroup_IndoorRoute117
#define MAP_ROUTE117_POKEMON_DAY_CARE (0 | (29 << 8))

// gMapGroup_IndoorRoute121
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (0 | (30 << 8))

// gMapGroup_Dungeons
#define MAP_METEOR_FALLS_1F_1R                       (0 | (31 << 8))
#define MAP_METEOR_FALLS_1F_2R                       (1 | (31 << 8))
#define MAP_METEOR_FALLS_B1F_1R                      (2 | (31 << 8))
#define MAP_METEOR_FALLS_B1F_2R                      (3 | (31 << 8))
#define MAP_RUSTURF_TUNNEL                           (4 | (31 << 8))
#define MAP_UNDERWATER_SOOTOPOLIS_CITY               (5 | (31 << 8))
#define MAP_DESERT_RUINS                             (6 | (31 << 8))
#define MAP_GRANITE_CAVE_1F                          (7 | (31 << 8))
#define MAP_GRANITE_CAVE_B1F                         (8 | (31 << 8))
#define MAP_GRANITE_CAVE_B2F                         (9 | (31 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM                (10 | (31 << 8))
#define MAP_PETALBURG_WOODS                          (11 | (31 << 8))
#define MAP_MT_CHIMNEY                               (12 | (31 << 8))
#define MAP_JAGGED_PASS                              (13 | (31 << 8))
#define MAP_FIERY_PATH                               (14 | (31 << 8))
#define MAP_MT_PYRE_1F                               (15 | (31 << 8))
#define MAP_MT_PYRE_2F                               (16 | (31 << 8))
#define MAP_MT_PYRE_3F                               (17 | (31 << 8))
#define MAP_MT_PYRE_4F                               (18 | (31 << 8))
#define MAP_MT_PYRE_5F                               (19 | (31 << 8))
#define MAP_MT_PYRE_6F                               (20 | (31 << 8))
#define MAP_MT_PYRE_EXTERIOR                         (21 | (31 << 8))
#define MAP_MT_PYRE_SUMMIT                           (22 | (31 << 8))
#define MAP_AQUA_HIDEOUT_1F                          (23 | (31 << 8))
#define MAP_AQUA_HIDEOUT_B1F                         (24 | (31 << 8))
#define MAP_AQUA_HIDEOUT_B2F                         (25 | (31 << 8))
#define MAP_UNDERWATER_SEAFLOOR_CAVERN               (26 | (31 << 8))
#define MAP_SEAFLOOR_CAVERN_ENTRANCE                 (27 | (31 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM1                    (28 | (31 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM2                    (29 | (31 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM3                    (30 | (31 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM4                    (31 | (31 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM5                    (32 | (31 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM6                    (33 | (31 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM7                    (34 | (31 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM8                    (35 | (31 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM9                    (36 | (31 << 8))
#define MAP_CAVE_OF_ORIGIN_ENTRANCE                  (37 | (31 << 8))
#define MAP_CAVE_OF_ORIGIN_1F                        (38 | (31 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1 (39 | (31 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2 (40 | (31 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3 (41 | (31 << 8))
#define MAP_CAVE_OF_ORIGIN_B1F                       (42 | (31 << 8))
#define MAP_VICTORY_ROAD_1F                          (43 | (31 << 8))
#define MAP_VICTORY_ROAD_B1F                         (44 | (31 << 8))
#define MAP_VICTORY_ROAD_B2F                         (45 | (31 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM        (46 | (31 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM           (47 | (31 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM          (48 | (31 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM           (49 | (31 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM       (50 | (31 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM          (51 | (31 << 8))
#define MAP_NEW_MAUVILLE_ENTRANCE                    (52 | (31 << 8))
#define MAP_NEW_MAUVILLE_INSIDE                      (53 | (31 << 8))
#define MAP_ABANDONED_SHIP_DECK                      (54 | (31 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_1F              (55 | (31 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_1F                  (56 | (31 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F             (57 | (31 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_B1F                 (58 | (31 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_B1F                (59 | (31 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER1               (60 | (31 << 8))
#define MAP_ABANDONED_SHIP_ROOM_B1F                  (61 | (31 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_1F                 (62 | (31 << 8))
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE           (63 | (31 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER2               (64 | (31 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS    (65 | (31 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS        (66 | (31 << 8))
#define MAP_ISLAND_CAVE                              (67 | (31 << 8))
#define MAP_ANCIENT_TOMB                             (68 | (31 << 8))
#define MAP_UNDERWATER_ROUTE134                      (69 | (31 << 8))
#define MAP_UNDERWATER_SEALED_CHAMBER                (70 | (31 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM                (71 | (31 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM                (72 | (31 << 8))
#define MAP_SCORCHED_SLAB                            (73 | (31 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1            (74 | (31 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2            (75 | (31 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3            (76 | (31 << 8))
#define MAP_SKY_PILLAR_ENTRANCE                      (77 | (31 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                       (78 | (31 << 8))
#define MAP_SKY_PILLAR_1F                            (79 | (31 << 8))
#define MAP_SKY_PILLAR_2F                            (80 | (31 << 8))
#define MAP_SKY_PILLAR_3F                            (81 | (31 << 8))
#define MAP_SKY_PILLAR_4F                            (82 | (31 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM             (83 | (31 << 8))
#define MAP_SKY_PILLAR_5F                            (84 | (31 << 8))
#define MAP_SKY_PILLAR_TOP                           (85 | (31 << 8))
#define MAP_MAGMA_HIDEOUT_1F                         (86 | (31 << 8))
#define MAP_MAGMA_HIDEOUT_2F_1R                      (87 | (31 << 8))
#define MAP_MAGMA_HIDEOUT_2F_2R                      (88 | (31 << 8))
#define MAP_MAGMA_HIDEOUT_3F_1R                      (89 | (31 << 8))
#define MAP_MAGMA_HIDEOUT_3F_2R                      (90 | (31 << 8))
#define MAP_MAGMA_HIDEOUT_4F                         (91 | (31 << 8))
#define MAP_MAGMA_HIDEOUT_3F_3R                      (92 | (31 << 8))
#define MAP_MAGMA_HIDEOUT_2F_3R                      (93 | (31 << 8))
#define MAP_MIRAGE_TOWER_1F                          (94 | (31 << 8))
#define MAP_MIRAGE_TOWER_2F                          (95 | (31 << 8))
#define MAP_MIRAGE_TOWER_3F                          (96 | (31 << 8))
#define MAP_MIRAGE_TOWER_4F                          (97 | (31 << 8))
#define MAP_DESERT_UNDERPASS                         (98 | (31 << 8))
#define MAP_ARTISAN_CAVE_B1F                         (99 | (31 << 8))
#define MAP_ARTISAN_CAVE_1F                          (100 | (31 << 8))
#define MAP_UNDERWATER_MARINE_CAVE                   (101 | (31 << 8))
#define MAP_MARINE_CAVE_ENTRANCE                     (102 | (31 << 8))
#define MAP_MARINE_CAVE_END                          (103 | (31 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                      (104 | (31 << 8))
#define MAP_TERRA_CAVE_END                           (105 | (31 << 8))
#define MAP_ALTERING_CAVE                            (106 | (31 << 8))
#define MAP_METEOR_FALLS_STEVENS_CAVE                (107 | (31 << 8))
#define MAP_GINKO_WOODS                              (108 | (31 << 8))
#define MAP_SILVER_TUNNEL_1F                         (109 | (31 << 8))
#define MAP_SILVER_TUNNEL_2F                         (110 | (31 << 8))
#define MAP_UUME_FOREST                              (111 | (31 << 8))

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (32 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (32 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (32 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (32 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (32 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (32 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (32 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (32 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (32 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (32 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (32 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (32 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (32 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (32 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (32 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (32 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (32 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (32 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (32 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (32 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (32 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (32 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (32 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (32 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (32 << 8))
#define MAP_TRADE_CENTER             (25 | (32 << 8))
#define MAP_RECORD_CORNER            (26 | (32 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (32 << 8))
#define MAP_CONTEST_HALL             (28 | (32 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (29 | (32 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (30 | (32 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (31 | (32 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (32 | (32 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (33 | (32 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (34 | (32 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (35 | (32 << 8))
#define MAP_CONTEST_HALL_TOUGH       (36 | (32 << 8))
#define MAP_CONTEST_HALL_COOL        (37 | (32 << 8))
#define MAP_CONTEST_HALL_SMART       (38 | (32 << 8))
#define MAP_CONTEST_HALL_CUTE        (39 | (32 << 8))
#define MAP_INSIDE_OF_TRUCK          (40 | (32 << 8))
#define MAP_SS_TIDAL_CORRIDOR        (41 | (32 << 8))
#define MAP_SS_TIDAL_LOWER_DECK      (42 | (32 << 8))
#define MAP_SS_TIDAL_ROOMS           (43 | (32 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (44 | (32 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (45 | (32 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (46 | (32 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (47 | (32 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (48 | (32 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (49 | (32 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (50 | (32 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (51 | (32 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (52 | (32 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (53 | (32 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (54 | (32 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (55 | (32 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (56 | (32 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (57 | (32 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (58 | (32 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (59 | (32 << 8))
#define MAP_UNION_ROOM               (60 | (32 << 8))

// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (33 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (33 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (33 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (33 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (33 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (9 | (33 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (10 | (33 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (11 | (33 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (12 | (33 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (13 | (33 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (14 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (15 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (16 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (17 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (18 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (19 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (20 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (21 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (22 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (23 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (24 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (25 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (26 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (27 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (28 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (29 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (30 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (31 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (32 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (33 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (34 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (35 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (36 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (37 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (38 | (33 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (39 | (33 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (40 | (33 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (41 | (33 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (42 | (33 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (43 | (33 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (44 | (33 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (45 | (33 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (46 | (33 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (47 | (33 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (48 | (33 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (49 | (33 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (50 | (33 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (51 | (33 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (52 | (33 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (53 | (33 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (54 | (33 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (55 | (33 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (56 | (33 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (57 | (33 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (58 | (33 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (59 | (33 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (60 | (33 << 8))
#define MAP_TRAINER_HILL_1F                                 (61 | (33 << 8))
#define MAP_TRAINER_HILL_2F                                 (62 | (33 << 8))
#define MAP_TRAINER_HILL_3F                                 (63 | (33 << 8))
#define MAP_TRAINER_HILL_4F                                 (64 | (33 << 8))
#define MAP_TRAINER_HILL_ROOF                               (65 | (33 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (66 | (33 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (67 | (33 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (68 | (33 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (69 | (33 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (70 | (33 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (71 | (33 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (72 | (33 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (73 | (33 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (74 | (33 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (75 | (33 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (76 | (33 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (77 | (33 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (78 | (33 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (79 | (33 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (80 | (33 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (81 | (33 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (82 | (33 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (83 | (33 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (84 | (33 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (85 | (33 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (86 | (33 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (87 | (33 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (88 | (33 << 8))

// gMapGroup_IndoorRoute104Prototype
#define MAP_ROUTE104_PROTOTYPE                          (0 | (34 << 8))
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP (1 | (34 << 8))

// gMapGroup_IndoorRoute109
#define MAP_ROUTE109_SEASHORE_HOUSE (0 | (35 << 8))

// gMapGroup_IndoorRoute110
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                (0 | (36 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_END                     (1 | (36 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                (2 | (36 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                 (3 | (36 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                 (4 | (36 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                 (5 | (36 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                 (6 | (36 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                 (7 | (36 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                 (8 | (36 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                 (9 | (36 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                 (10 | (36 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (11 | (36 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (12 | (36 << 8))

// gMapGroup_IndoorRoute113
#define MAP_ROUTE113_GLASS_WORKSHOP (0 | (37 << 8))

// gMapGroup_IndoorRoute123
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE (0 | (38 << 8))

// gMapGroup_IndoorRoute119
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0 | (39 << 8))
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F (1 | (39 << 8))
#define MAP_ROUTE119_HOUSE                (2 | (39 << 8))

// gMapGroup_IndoorRoute124
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE (0 | (40 << 8))

#define MAP_GROUPS_COUNT 41

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
