#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_FloraSkyTowns
#define MAP_SMALL_TOWN     (0 | (0 << 8))
#define MAP_PUEL_CITY      (1 | (0 << 8))
#define MAP_MYSTIC_TOWN    (2 | (0 << 8))
#define MAP_PLATEPICS_CITY (3 | (0 << 8))
#define MAP_NEW_MAP2       (4 | (0 << 8))
#define MAP_POKEMON_LEAUGE (5 | (0 << 8))
#define MAP_TURZORO_CITY   (6 | (0 << 8))
#define MAP_HABUTEST_TOWN  (7 | (0 << 8))
#define MAP_SEAROUND_CITY  (8 | (0 << 8))
#define MAP_CHARPOS_ISLAND (9 | (0 << 8))
#define MAP_OCEPAC_TOWN    (10 | (0 << 8))
#define MAP_HOTASITA_CITY  (11 | (0 << 8))
#define MAP_PULHIA_CITY    (12 | (0 << 8))
#define MAP_MALIAS_CITY    (13 | (0 << 8))
#define MAP_TEAES_CITY     (14 | (0 << 8))
#define MAP_FROSTER_TOWN   (15 | (0 << 8))

// gMapGroup_FloraSkyRoutes
#define MAP_ROUTE_A         (0 | (1 << 8))
#define MAP_ROUTE_D         (1 | (1 << 8))
#define MAP_FOREST_ENTRANCE (2 | (1 << 8))
#define MAP_ROUTE_B         (3 | (1 << 8))
#define MAP_ROUTE_C         (4 | (1 << 8))
#define MAP_ROUTE_G         (5 | (1 << 8))
#define MAP_ROUTE_F         (6 | (1 << 8))
#define MAP_ROUTE_E         (7 | (1 << 8))
#define MAP_ROUTE_H         (8 | (1 << 8))
#define MAP_ROUTE_I         (9 | (1 << 8))
#define MAP_ROUTE_J         (10 | (1 << 8))
#define MAP_ROUTE_K         (11 | (1 << 8))
#define MAP_ROUTE_L         (12 | (1 << 8))
#define MAP_ROUTE_M         (13 | (1 << 8))
#define MAP_ROUTE_N         (14 | (1 << 8))
#define MAP_ROUTE_P         (15 | (1 << 8))
#define MAP_ROUTE_V         (16 | (1 << 8))
#define MAP_ROUTE_AC        (17 | (1 << 8))
#define MAP_ROUTE_AB        (18 | (1 << 8))
#define MAP_ROUTE_Q         (19 | (1 << 8))
#define MAP_ROUTE_W         (20 | (1 << 8))
#define MAP_ROUTE_U         (21 | (1 << 8))
#define MAP_ROUTE_T         (22 | (1 << 8))
#define MAP_ROUTE_AA        (23 | (1 << 8))
#define MAP_ROUTE_Z         (24 | (1 << 8))
#define MAP_ROUTE_Y         (25 | (1 << 8))
#define MAP_ROUTE_X         (26 | (1 << 8))
#define MAP_ROUTE_R         (27 | (1 << 8))
#define MAP_ROUTE_S         (28 | (1 << 8))
#define MAP_ROUTE_O         (29 | (1 << 8))
#define MAP_ROUTE_AF        (30 | (1 << 8))
#define MAP_ROUTE_AE        (31 | (1 << 8))
#define MAP_MOUNT_BLIZZARD  (32 | (1 << 8))

// gMapGroup_IndoorSmallTown
#define MAP_NEW_MAP1                (0 | (2 << 8))
#define MAP_MALE_PLAYER_HOUSE2F     (1 | (2 << 8))
#define MAP_FEMALE_PLAYER_HOUSE1F   (2 | (2 << 8))
#define MAP_FEMALE_PLAYER_HOUSE2F   (3 | (2 << 8))
#define MAP_FEMALE_PHOUSE2F         (4 | (2 << 8))
#define MAP_PROFFESOR_LAB           (5 | (2 << 8))
#define MAP_SMALL_TOWN_DAY_CARE     (6 | (2 << 8))
#define MAP_SMALL_TOWN_POKEMON_MART (7 | (2 << 8))

// gMapGroup_IndoorRouteA
#define MAP_ROUTE_AHOUSE (0 | (3 << 8))

// gMapGroup_IndoorRouteB
#define MAP_ROUTE_BHOUSE (0 | (4 << 8))
#define MAP_LOST_CAVE    (1 | (4 << 8))

// gMapGroup_IndoorRouteC
#define MAP_ROUTE_CHOUSE (0 | (5 << 8))

// gMapGroup_IndoorRouteD
#define MAP_ROUTE_DFLOWER_SHOP (0 | (6 << 8))

// gMapGroup_IndoorUnionGate
#define MAP_UNION_GATE (0 | (7 << 8))

// gMapGroup_IndoorPuelCity
#define MAP_PUEL_CITY_GYM                 (0 | (8 << 8))
#define MAP_PUEL_CITY_HOUSES              (1 | (8 << 8))
#define MAP_PUEL_CITY_PKMN_CENTRE1F       (2 | (8 << 8))
#define MAP_PUEL_CITY_PKMN_CENTRE2F       (3 | (8 << 8))
#define MAP_PUEL_CITY_MUSEUM1F            (4 | (8 << 8))
#define MAP_PUEL_CITY_MUSEUM2F            (5 | (8 << 8))
#define MAP_PUEL_CITY_MUSEUM_AQUA_HIDEOUT (6 | (8 << 8))
#define MAP_PUEL_CITY_MART                (7 | (8 << 8))

// gMapGroup_IndoorMysticTown
#define MAP_MYSTIC_TOWN_HOUSE_WITH_HOLE (0 | (9 << 8))
#define MAP_MYSTIC_TOWN_PKMN_CENTRE1F   (1 | (9 << 8))
#define MAP_MYSTIC_TOWN_PKMN_CENTRE2F   (2 | (9 << 8))
#define MAP_MYSTIC_TOWN_HOUSE           (3 | (9 << 8))
#define MAP_MYSTIC_TOWN_SMALL_CAVE      (4 | (9 << 8))
#define MAP_MYSTIC_TOWN_SHOP            (5 | (9 << 8))

// gMapGroup_IndoorForestEntrance
#define MAP_FOREST_ENTRANCE_HOUSE            (0 | (10 << 8))
#define MAP_FOREST_ENTRANCE_POKEMON_CENTRE1F (1 | (10 << 8))
#define MAP_FOREST_ENTRANCE_PKMN_CENTRE2F    (2 | (10 << 8))

// gMapGroup_MountainFullMoon
#define MAP_MOUNT_FULL_MOON_MAIN_INTERIOR              (0 | (11 << 8))
#define MAP_MOUNT_FULL_MOON_INTERIOR_CAVEDOWNRIGHTSIDE (1 | (11 << 8))
#define MAP_MOUNT_MOON_CAVE_STARTER_PICK               (2 | (11 << 8))
#define MAP_MOUNT_MOON_DEEP_INTERIOR                   (3 | (11 << 8))
#define MAP_MOUNT_FULL_MOON_DEEP_CAVE_DIALGA           (4 | (11 << 8))
#define MAP_MOUNT_FULL_MOON_PEAK                       (5 | (11 << 8))
#define MAP_MOUNT_FULL_MOON_DEEPEST_INTERIOR           (6 | (11 << 8))
#define MAP_MOUNT_FULL_MOON_DEEP_CAVE_CRESELLIA        (7 | (11 << 8))

// gMapGroup_BeeBugForest
#define MAP_BEE_BUG_FOREST (0 | (12 << 8))

// gMapGroup_PolarForest
#define MAP_POLAR_FOREST_BOTTOM_RIGHT (0 | (13 << 8))
#define MAP_POLAR_FOREST_LEFT         (1 | (13 << 8))
#define MAP_POLAR_FOREST_DOWN         (2 | (13 << 8))
#define MAP_POLAR_FOREST_DOWN_LEFT    (3 | (13 << 8))

// gMapGroup_DeepForest
#define MAP_DEEP_FOREST (0 | (14 << 8))

// gMapGroup_TownsAndRoutes
#define MAP_PETALBURG_CITY      (0 | (15 << 8))
#define MAP_SLATEPORT_CITY      (1 | (15 << 8))
#define MAP_MAUVILLE_CITY       (2 | (15 << 8))
#define MAP_RUSTBORO_CITY       (3 | (15 << 8))
#define MAP_FORTREE_CITY        (4 | (15 << 8))
#define MAP_LILYCOVE_CITY       (5 | (15 << 8))
#define MAP_MOSSDEEP_CITY       (6 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY     (7 | (15 << 8))
#define MAP_EVER_GRANDE_CITY    (8 | (15 << 8))
#define MAP_LITTLEROOT_TOWN     (9 | (15 << 8))
#define MAP_OLDALE_TOWN         (10 | (15 << 8))
#define MAP_DEWFORD_TOWN        (11 | (15 << 8))
#define MAP_LAVARIDGE_TOWN      (12 | (15 << 8))
#define MAP_FALLARBOR_TOWN      (13 | (15 << 8))
#define MAP_VERDANTURF_TOWN     (14 | (15 << 8))
#define MAP_PACIFIDLOG_TOWN     (15 | (15 << 8))
#define MAP_ROUTE101            (16 | (15 << 8))
#define MAP_ROUTE102            (17 | (15 << 8))
#define MAP_ROUTE103            (18 | (15 << 8))
#define MAP_ROUTE104            (19 | (15 << 8))
#define MAP_ROUTE105            (20 | (15 << 8))
#define MAP_ROUTE106            (21 | (15 << 8))
#define MAP_ROUTE107            (22 | (15 << 8))
#define MAP_ROUTE108            (23 | (15 << 8))
#define MAP_ROUTE109            (24 | (15 << 8))
#define MAP_ROUTE110            (25 | (15 << 8))
#define MAP_ROUTE111            (26 | (15 << 8))
#define MAP_ROUTE112            (27 | (15 << 8))
#define MAP_ROUTE113            (28 | (15 << 8))
#define MAP_ROUTE114            (29 | (15 << 8))
#define MAP_ROUTE115            (30 | (15 << 8))
#define MAP_ROUTE116            (31 | (15 << 8))
#define MAP_ROUTE117            (32 | (15 << 8))
#define MAP_ROUTE118            (33 | (15 << 8))
#define MAP_ROUTE119            (34 | (15 << 8))
#define MAP_ROUTE120            (35 | (15 << 8))
#define MAP_ROUTE121            (36 | (15 << 8))
#define MAP_ROUTE122            (37 | (15 << 8))
#define MAP_ROUTE123            (38 | (15 << 8))
#define MAP_ROUTE124            (39 | (15 << 8))
#define MAP_ROUTE125            (40 | (15 << 8))
#define MAP_ROUTE126            (41 | (15 << 8))
#define MAP_ROUTE127            (42 | (15 << 8))
#define MAP_ROUTE128            (43 | (15 << 8))
#define MAP_ROUTE129            (44 | (15 << 8))
#define MAP_ROUTE130            (45 | (15 << 8))
#define MAP_ROUTE131            (46 | (15 << 8))
#define MAP_ROUTE132            (47 | (15 << 8))
#define MAP_ROUTE133            (48 | (15 << 8))
#define MAP_ROUTE134            (49 | (15 << 8))
#define MAP_UNDERWATER_ROUTE124 (50 | (15 << 8))
#define MAP_UNDERWATER_ROUTE126 (51 | (15 << 8))
#define MAP_UNDERWATER_ROUTE127 (52 | (15 << 8))
#define MAP_UNDERWATER_ROUTE128 (53 | (15 << 8))
#define MAP_UNDERWATER_ROUTE129 (54 | (15 << 8))
#define MAP_UNDERWATER_ROUTE105 (55 | (15 << 8))
#define MAP_UNDERWATER_ROUTE125 (56 | (15 << 8))

// gMapGroup_IndoorLittleroot
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (16 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (16 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (16 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (16 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (16 << 8))

// gMapGroup_IndoorOldale
#define MAP_OLDALE_TOWN_HOUSE1            (0 | (17 << 8))
#define MAP_OLDALE_TOWN_HOUSE2            (1 | (17 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F (2 | (17 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F (3 | (17 << 8))
#define MAP_OLDALE_TOWN_MART              (4 | (17 << 8))

// gMapGroup_IndoorDewford
#define MAP_DEWFORD_TOWN_HOUSE1            (0 | (18 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F (1 | (18 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F (2 | (18 << 8))
#define MAP_DEWFORD_TOWN_GYM               (3 | (18 << 8))
#define MAP_DEWFORD_TOWN_HALL              (4 | (18 << 8))
#define MAP_DEWFORD_TOWN_HOUSE2            (5 | (18 << 8))

// gMapGroup_IndoorLavaridge
#define MAP_LAVARIDGE_TOWN_HERB_SHOP         (0 | (19 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_1F            (1 | (19 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F           (2 | (19 << 8))
#define MAP_LAVARIDGE_TOWN_HOUSE             (3 | (19 << 8))
#define MAP_LAVARIDGE_TOWN_MART              (4 | (19 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (5 | (19 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F (6 | (19 << 8))

// gMapGroup_IndoorFallarbor
#define MAP_FALLARBOR_TOWN_MART                    (0 | (20 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (20 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (20 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (20 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       (4 | (20 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       (5 | (20 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (6 | (20 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (7 | (20 << 8))

// gMapGroup_IndoorVerdanturf
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (21 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (21 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (21 << 8))
#define MAP_VERDANTURF_TOWN_MART                    (3 | (21 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       (4 | (21 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       (5 | (21 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (6 | (21 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (7 | (21 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE                   (8 | (21 << 8))

// gMapGroup_IndoorPacifidlog
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0 | (22 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (1 | (22 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1            (2 | (22 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2            (3 | (22 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3            (4 | (22 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4            (5 | (22 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5            (6 | (22 << 8))

// gMapGroup_IndoorPetalburg
#define MAP_PETALBURG_CITY_WALLYS_HOUSE      (0 | (23 << 8))
#define MAP_PETALBURG_CITY_GYM               (1 | (23 << 8))
#define MAP_PETALBURG_CITY_HOUSE1            (2 | (23 << 8))
#define MAP_PETALBURG_CITY_HOUSE2            (3 | (23 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (4 | (23 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (5 | (23 << 8))
#define MAP_PETALBURG_CITY_MART              (6 | (23 << 8))

// gMapGroup_IndoorSlateport
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F      (0 | (24 << 8))
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F      (1 | (24 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY       (2 | (24 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR    (3 | (24 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM (4 | (24 << 8))
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE       (5 | (24 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB        (6 | (24 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F       (7 | (24 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F       (8 | (24 << 8))
#define MAP_SLATEPORT_CITY_HARBOR                  (9 | (24 << 8))
#define MAP_SLATEPORT_CITY_HOUSE                   (10 | (24 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F       (11 | (24 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F       (12 | (24 << 8))
#define MAP_SLATEPORT_CITY_MART                    (13 | (24 << 8))

// gMapGroup_IndoorMauville
#define MAP_MAUVILLE_CITY_GYM               (0 | (25 << 8))
#define MAP_MAUVILLE_CITY_BIKE_SHOP         (1 | (25 << 8))
#define MAP_MAUVILLE_CITY_HOUSE1            (2 | (25 << 8))
#define MAP_MAUVILLE_CITY_GAME_CORNER       (3 | (25 << 8))
#define MAP_MAUVILLE_CITY_HOUSE2            (4 | (25 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F (5 | (25 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F (6 | (25 << 8))
#define MAP_MAUVILLE_CITY_MART              (7 | (25 << 8))

// gMapGroup_IndoorRustboro
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F     (0 | (26 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F     (1 | (26 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F     (2 | (26 << 8))
#define MAP_RUSTBORO_CITY_GYM               (3 | (26 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL    (4 | (26 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F (5 | (26 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F (6 | (26 << 8))
#define MAP_RUSTBORO_CITY_MART              (7 | (26 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_1F          (8 | (26 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_2F          (9 | (26 << 8))
#define MAP_RUSTBORO_CITY_HOUSE1            (10 | (26 << 8))
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE     (11 | (26 << 8))
#define MAP_RUSTBORO_CITY_HOUSE2            (12 | (26 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F          (13 | (26 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F          (14 | (26 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F          (15 | (26 << 8))
#define MAP_RUSTBORO_CITY_HOUSE3            (16 | (26 << 8))

// gMapGroup_IndoorFortree
#define MAP_FORTREE_CITY_HOUSE1            (0 | (27 << 8))
#define MAP_FORTREE_CITY_GYM               (1 | (27 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F (2 | (27 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F (3 | (27 << 8))
#define MAP_FORTREE_CITY_MART              (4 | (27 << 8))
#define MAP_FORTREE_CITY_HOUSE2            (5 | (27 << 8))
#define MAP_FORTREE_CITY_HOUSE3            (6 | (27 << 8))
#define MAP_FORTREE_CITY_HOUSE4            (7 | (27 << 8))
#define MAP_FORTREE_CITY_HOUSE5            (8 | (27 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP   (9 | (27 << 8))

// gMapGroup_IndoorLilycove
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        (0 | (28 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        (1 | (28 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        (2 | (28 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        (3 | (28 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY             (4 | (28 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL              (5 | (28 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F         (6 | (28 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F         (7 | (28 << 8))
#define MAP_LILYCOVE_CITY_UNUSED_MART               (8 | (28 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  (9 | (28 << 8))
#define MAP_LILYCOVE_CITY_HARBOR                    (10 | (28 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       (11 | (28 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                    (12 | (28 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                    (13 | (28 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                    (14 | (28 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                    (15 | (28 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       (16 | (28 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       (17 | (28 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       (18 | (28 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       (19 | (28 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       (20 | (28 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  (21 | (28 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (22 | (28 << 8))

// gMapGroup_IndoorMossdeep
#define MAP_MOSSDEEP_CITY_GYM               (0 | (29 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE1            (1 | (29 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2            (2 | (29 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F (3 | (29 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F (4 | (29 << 8))
#define MAP_MOSSDEEP_CITY_MART              (5 | (29 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3            (6 | (29 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE     (7 | (29 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4            (8 | (29 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F   (9 | (29 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F   (10 | (29 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F    (11 | (29 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F   (12 | (29 << 8))

// gMapGroup_IndoorSootopolis
#define MAP_SOOTOPOLIS_CITY_GYM_1F                   (0 | (30 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_B1F                  (1 | (30 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F        (2 | (30 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F        (3 | (30 << 8))
#define MAP_SOOTOPOLIS_CITY_MART                     (4 | (30 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE1                   (5 | (30 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE2                   (6 | (30 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE3                   (7 | (30 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE4                   (8 | (30 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE5                   (9 | (30 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE6                   (10 | (30 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE7                   (11 | (30 << 8))
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE   (12 | (30 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  (13 | (30 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (14 | (30 << 8))

// gMapGroup_IndoorEverGrande
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (31 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (31 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (31 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (31 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (31 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (31 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (31 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (31 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (31 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (31 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (31 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (31 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (12 | (31 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (13 | (31 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (14 | (31 << 8))

// gMapGroup_IndoorRoute104
#define MAP_ROUTE104_MR_BRINEYS_HOUSE         (0 | (32 << 8))
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP (1 | (32 << 8))

// gMapGroup_IndoorRoute111
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE (0 | (33 << 8))
#define MAP_ROUTE111_OLD_LADYS_REST_STOP     (1 | (33 << 8))

// gMapGroup_IndoorRoute112
#define MAP_ROUTE112_CABLE_CAR_STATION   (0 | (34 << 8))
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION (1 | (34 << 8))

// gMapGroup_IndoorRoute114
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE  (0 | (35 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL (1 | (35 << 8))
#define MAP_ROUTE114_LANETTES_HOUSE        (2 | (35 << 8))

// gMapGroup_IndoorRoute116
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE (0 | (36 << 8))

// gMapGroup_IndoorRoute117
#define MAP_ROUTE117_POKEMON_DAY_CARE (0 | (37 << 8))

// gMapGroup_IndoorRoute121
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (0 | (38 << 8))

// gMapGroup_Dungeons
#define MAP_METEOR_FALLS_1F_1R                       (0 | (39 << 8))
#define MAP_METEOR_FALLS_1F_2R                       (1 | (39 << 8))
#define MAP_METEOR_FALLS_B1F_1R                      (2 | (39 << 8))
#define MAP_METEOR_FALLS_B1F_2R                      (3 | (39 << 8))
#define MAP_RUSTURF_TUNNEL                           (4 | (39 << 8))
#define MAP_UNDERWATER_SOOTOPOLIS_CITY               (5 | (39 << 8))
#define MAP_DESERT_RUINS                             (6 | (39 << 8))
#define MAP_GRANITE_CAVE_1F                          (7 | (39 << 8))
#define MAP_GRANITE_CAVE_B1F                         (8 | (39 << 8))
#define MAP_GRANITE_CAVE_B2F                         (9 | (39 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM                (10 | (39 << 8))
#define MAP_PETALBURG_WOODS                          (11 | (39 << 8))
#define MAP_MT_CHIMNEY                               (12 | (39 << 8))
#define MAP_JAGGED_PASS                              (13 | (39 << 8))
#define MAP_FIERY_PATH                               (14 | (39 << 8))
#define MAP_MT_PYRE_1F                               (15 | (39 << 8))
#define MAP_MT_PYRE_2F                               (16 | (39 << 8))
#define MAP_MT_PYRE_3F                               (17 | (39 << 8))
#define MAP_MT_PYRE_4F                               (18 | (39 << 8))
#define MAP_MT_PYRE_5F                               (19 | (39 << 8))
#define MAP_MT_PYRE_6F                               (20 | (39 << 8))
#define MAP_MT_PYRE_EXTERIOR                         (21 | (39 << 8))
#define MAP_MT_PYRE_SUMMIT                           (22 | (39 << 8))
#define MAP_AQUA_HIDEOUT_1F                          (23 | (39 << 8))
#define MAP_AQUA_HIDEOUT_B1F                         (24 | (39 << 8))
#define MAP_AQUA_HIDEOUT_B2F                         (25 | (39 << 8))
#define MAP_UNDERWATER_SEAFLOOR_CAVERN               (26 | (39 << 8))
#define MAP_SEAFLOOR_CAVERN_ENTRANCE                 (27 | (39 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM1                    (28 | (39 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM2                    (29 | (39 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM3                    (30 | (39 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM4                    (31 | (39 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM5                    (32 | (39 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM6                    (33 | (39 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM7                    (34 | (39 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM8                    (35 | (39 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM9                    (36 | (39 << 8))
#define MAP_CAVE_OF_ORIGIN_ENTRANCE                  (37 | (39 << 8))
#define MAP_CAVE_OF_ORIGIN_1F                        (38 | (39 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1 (39 | (39 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2 (40 | (39 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3 (41 | (39 << 8))
#define MAP_CAVE_OF_ORIGIN_B1F                       (42 | (39 << 8))
#define MAP_VICTORY_ROAD_1F                          (43 | (39 << 8))
#define MAP_VICTORY_ROAD_B1F                         (44 | (39 << 8))
#define MAP_VICTORY_ROAD_B2F                         (45 | (39 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM        (46 | (39 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM           (47 | (39 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM          (48 | (39 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM           (49 | (39 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM       (50 | (39 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM          (51 | (39 << 8))
#define MAP_NEW_MAUVILLE_ENTRANCE                    (52 | (39 << 8))
#define MAP_NEW_MAUVILLE_INSIDE                      (53 | (39 << 8))
#define MAP_ABANDONED_SHIP_DECK                      (54 | (39 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_1F              (55 | (39 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_1F                  (56 | (39 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F             (57 | (39 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_B1F                 (58 | (39 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_B1F                (59 | (39 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER1               (60 | (39 << 8))
#define MAP_ABANDONED_SHIP_ROOM_B1F                  (61 | (39 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_1F                 (62 | (39 << 8))
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE           (63 | (39 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER2               (64 | (39 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS    (65 | (39 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS        (66 | (39 << 8))
#define MAP_ISLAND_CAVE                              (67 | (39 << 8))
#define MAP_ANCIENT_TOMB                             (68 | (39 << 8))
#define MAP_UNDERWATER_ROUTE134                      (69 | (39 << 8))
#define MAP_UNDERWATER_SEALED_CHAMBER                (70 | (39 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM                (71 | (39 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM                (72 | (39 << 8))
#define MAP_SCORCHED_SLAB                            (73 | (39 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1            (74 | (39 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2            (75 | (39 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3            (76 | (39 << 8))
#define MAP_SKY_PILLAR_ENTRANCE                      (77 | (39 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                       (78 | (39 << 8))
#define MAP_SKY_PILLAR_1F                            (79 | (39 << 8))
#define MAP_SKY_PILLAR_2F                            (80 | (39 << 8))
#define MAP_SKY_PILLAR_3F                            (81 | (39 << 8))
#define MAP_SKY_PILLAR_4F                            (82 | (39 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM             (83 | (39 << 8))
#define MAP_SKY_PILLAR_5F                            (84 | (39 << 8))
#define MAP_SKY_PILLAR_TOP                           (85 | (39 << 8))
#define MAP_MAGMA_HIDEOUT_1F                         (86 | (39 << 8))
#define MAP_MAGMA_HIDEOUT_2F_1R                      (87 | (39 << 8))
#define MAP_MAGMA_HIDEOUT_2F_2R                      (88 | (39 << 8))
#define MAP_MAGMA_HIDEOUT_3F_1R                      (89 | (39 << 8))
#define MAP_MAGMA_HIDEOUT_3F_2R                      (90 | (39 << 8))
#define MAP_MAGMA_HIDEOUT_4F                         (91 | (39 << 8))
#define MAP_MAGMA_HIDEOUT_3F_3R                      (92 | (39 << 8))
#define MAP_MAGMA_HIDEOUT_2F_3R                      (93 | (39 << 8))
#define MAP_MIRAGE_TOWER_1F                          (94 | (39 << 8))
#define MAP_MIRAGE_TOWER_2F                          (95 | (39 << 8))
#define MAP_MIRAGE_TOWER_3F                          (96 | (39 << 8))
#define MAP_MIRAGE_TOWER_4F                          (97 | (39 << 8))
#define MAP_DESERT_UNDERPASS                         (98 | (39 << 8))
#define MAP_ARTISAN_CAVE_B1F                         (99 | (39 << 8))
#define MAP_ARTISAN_CAVE_1F                          (100 | (39 << 8))
#define MAP_UNDERWATER_MARINE_CAVE                   (101 | (39 << 8))
#define MAP_MARINE_CAVE_ENTRANCE                     (102 | (39 << 8))
#define MAP_MARINE_CAVE_END                          (103 | (39 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                      (104 | (39 << 8))
#define MAP_TERRA_CAVE_END                           (105 | (39 << 8))
#define MAP_ALTERING_CAVE                            (106 | (39 << 8))
#define MAP_METEOR_FALLS_STEVENS_CAVE                (107 | (39 << 8))

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (40 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (40 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (40 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (40 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (40 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (40 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (40 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (40 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (40 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (40 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (40 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (40 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (40 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (40 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (40 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (40 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (40 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (40 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (40 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (40 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (40 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (40 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (40 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (40 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (40 << 8))
#define MAP_TRADE_CENTER             (25 | (40 << 8))
#define MAP_RECORD_CORNER            (26 | (40 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (40 << 8))
#define MAP_CONTEST_HALL             (28 | (40 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (29 | (40 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (30 | (40 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (31 | (40 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (32 | (40 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (33 | (40 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (34 | (40 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (35 | (40 << 8))
#define MAP_CONTEST_HALL_TOUGH       (36 | (40 << 8))
#define MAP_CONTEST_HALL_COOL        (37 | (40 << 8))
#define MAP_CONTEST_HALL_SMART       (38 | (40 << 8))
#define MAP_CONTEST_HALL_CUTE        (39 | (40 << 8))
#define MAP_INSIDE_OF_TRUCK          (40 | (40 << 8))
#define MAP_SS_TIDAL_CORRIDOR        (41 | (40 << 8))
#define MAP_SS_TIDAL_LOWER_DECK      (42 | (40 << 8))
#define MAP_SS_TIDAL_ROOMS           (43 | (40 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (44 | (40 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (45 | (40 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (46 | (40 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (47 | (40 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (48 | (40 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (49 | (40 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (50 | (40 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (51 | (40 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (52 | (40 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (53 | (40 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (54 | (40 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (55 | (40 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (56 | (40 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (57 | (40 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (58 | (40 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (59 | (40 << 8))
#define MAP_UNION_ROOM               (60 | (40 << 8))

// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (41 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (41 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (41 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (41 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (41 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (9 | (41 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (10 | (41 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (11 | (41 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (12 | (41 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (13 | (41 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (14 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (15 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (16 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (17 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (18 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (19 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (20 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (21 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (22 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (23 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (24 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (25 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (26 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (27 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (28 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (29 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (30 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (31 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (32 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (33 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (34 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (35 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (36 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (37 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (38 | (41 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (39 | (41 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (40 | (41 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (41 | (41 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (42 | (41 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (43 | (41 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (44 | (41 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (45 | (41 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (46 | (41 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (47 | (41 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (48 | (41 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (49 | (41 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (50 | (41 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (51 | (41 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (52 | (41 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (53 | (41 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (54 | (41 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (55 | (41 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (56 | (41 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (57 | (41 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (58 | (41 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (59 | (41 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (60 | (41 << 8))
#define MAP_TRAINER_HILL_1F                                 (61 | (41 << 8))
#define MAP_TRAINER_HILL_2F                                 (62 | (41 << 8))
#define MAP_TRAINER_HILL_3F                                 (63 | (41 << 8))
#define MAP_TRAINER_HILL_4F                                 (64 | (41 << 8))
#define MAP_TRAINER_HILL_ROOF                               (65 | (41 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (66 | (41 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (67 | (41 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (68 | (41 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (69 | (41 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (70 | (41 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (71 | (41 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (72 | (41 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (73 | (41 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (74 | (41 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (75 | (41 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (76 | (41 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (77 | (41 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (78 | (41 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (79 | (41 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (80 | (41 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (81 | (41 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (82 | (41 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (83 | (41 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (84 | (41 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (85 | (41 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (86 | (41 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (87 | (41 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (88 | (41 << 8))

// gMapGroup_IndoorRoute104Prototype
#define MAP_ROUTE104_PROTOTYPE                          (0 | (42 << 8))
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP (1 | (42 << 8))

// gMapGroup_IndoorRoute109
#define MAP_ROUTE109_SEASHORE_HOUSE (0 | (43 << 8))

// gMapGroup_IndoorRoute110
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                (0 | (44 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_END                     (1 | (44 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                (2 | (44 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                 (3 | (44 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                 (4 | (44 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                 (5 | (44 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                 (6 | (44 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                 (7 | (44 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                 (8 | (44 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                 (9 | (44 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                 (10 | (44 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (11 | (44 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (12 | (44 << 8))

// gMapGroup_IndoorRoute113
#define MAP_ROUTE113_GLASS_WORKSHOP (0 | (45 << 8))

// gMapGroup_IndoorRoute123
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE (0 | (46 << 8))

// gMapGroup_IndoorRoute119
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0 | (47 << 8))
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F (1 | (47 << 8))
#define MAP_ROUTE119_HOUSE                (2 | (47 << 8))

// gMapGroup_IndoorRoute124
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE (0 | (48 << 8))

#define MAP_GROUPS_COUNT 49

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
