#ifndef GUARD_CONSTANTS_MUGSHOTS_H
#define GUARD_CONSTANTS_MUGSHOTS_H

//Add your mugshot constants here
#define MUGSHOT_BLAINE 0
#define MUGSHOT_LEAF 1
#define MUGSHOT_KRIS 2
#define MUGSHOT_GOLD 3
#define MUGSHOT_RED 4
#define MUGSHOT_BLUE 5
#define MUGSHOT_AGATHA 6
#define MUGSHOT_LANCE 7
#define MUGSHOT_BRUNO 8
#define MUGSHOT_BROCK 9 
#define MUGSHOT_MISTY 10
#define MUGSHOT_WILL 11
#define MUGSHOT_LORLEI 12
#define MUGSHOT_BUGSY 13
#define MUGSHOT_MORTY 14
#define MUGSHOT_SABRINA 15
#define MUGSHOT_PRYCE 16
#define MUGSHOT_STEVEN 17
#define MUGSHOT_MAY 18
#define MUGSHOT_BRENDAN 19
#define MUGSHOT_ERIKA 20
#define MUGSHOT_JASMINE 21
#define MUGSHOT_WHITNEY 22
#define MUGSHOT_KAREN 23
#define MUGSHOT_JANINE 24
#define MUGSHOT_CLAIRE 25
#define MUGSHOT_SURGE 26
#define MUGSHOT_CHUCK 27
#define MUGSHOT_KOGA 28
#define MUGSHOT_SILVER 29
#define MUGSHOT_FALKNER 30
#define MUGSHOT_PROTON 31
#define MUGSHOT_PETREL 32
#define MUGSHOT_LUCAS 33
#define MUGSHOT_GHETSIS 34




#endif