#ifndef GUARD_CONSTANTS_SPECIES_H
#define GUARD_CONSTANTS_SPECIES_H

#include "constants/pokemon_config.h"

#define SPECIES_NONE                                         0
#define SPECIES_BULBASAUR                                    1
#define SPECIES_IVYSAUR                                      2
#define SPECIES_VENUSAUR                                     3
#define SPECIES_CHARMANDER                                   4
#define SPECIES_CHARMELEON                                   5
#define SPECIES_CHARIZARD                                    6
#define SPECIES_SQUIRTLE                                     7
#define SPECIES_WARTORTLE                                    8
#define SPECIES_BLASTOISE                                    9
#define SPECIES_CATERPIE                                     10
#define SPECIES_METAPOD                                      11
#define SPECIES_BUTTERFREE                                   12
#define SPECIES_WEEDLE                                       13
#define SPECIES_KAKUNA                                       14
#define SPECIES_BEEDRILL                                     15
#define SPECIES_PIDGEY                                       16
#define SPECIES_PIDGEOTTO                                    17
#define SPECIES_PIDGEOT                                      18
#define SPECIES_RATTATA                                      19
#define SPECIES_RATICATE                                     20
#define SPECIES_SPEAROW                                      21
#define SPECIES_FEAROW                                       22
#define SPECIES_EKANS                                        23
#define SPECIES_ARBOK                                        24
#define SPECIES_PIKACHU                                      25
#define SPECIES_RAICHU                                       26
#define SPECIES_SANDSHREW                                    27
#define SPECIES_SANDSLASH                                    28
#define SPECIES_NIDORAN_F                                    29
#define SPECIES_NIDORINA                                     30
#define SPECIES_NIDOQUEEN                                    31
#define SPECIES_NIDORAN_M                                    32
#define SPECIES_NIDORINO                                     33
#define SPECIES_NIDOKING                                     34
#define SPECIES_CLEFAIRY                                     35
#define SPECIES_CLEFABLE                                     36
#define SPECIES_VULPIX                                       37
#define SPECIES_NINETALES                                    38
#define SPECIES_JIGGLYPUFF                                   39
#define SPECIES_WIGGLYTUFF                                   40
#define SPECIES_ZUBAT                                        41
#define SPECIES_GOLBAT                                       42
#define SPECIES_ODDISH                                       43
#define SPECIES_GLOOM                                        44
#define SPECIES_VILEPLUME                                    45
#define SPECIES_PARAS                                        46
#define SPECIES_PARASECT                                     47
#define SPECIES_VENONAT                                      48
#define SPECIES_VENOMOTH                                     49
#define SPECIES_DIGLETT                                      50
#define SPECIES_DUGTRIO                                      51
#define SPECIES_MEOWTH                                       52
#define SPECIES_PERSIAN                                      53
#define SPECIES_PSYDUCK                                      54
#define SPECIES_GOLDUCK                                      55
#define SPECIES_MANKEY                                       56
#define SPECIES_PRIMEAPE                                     57
#define SPECIES_GROWLITHE                                    58
#define SPECIES_ARCANINE                                     59
#define SPECIES_POLIWAG                                      60
#define SPECIES_POLIWHIRL                                    61
#define SPECIES_POLIWRATH                                    62
#define SPECIES_ABRA                                         63
#define SPECIES_KADABRA                                      64
#define SPECIES_ALAKAZAM                                     65
#define SPECIES_MACHOP                                       66
#define SPECIES_MACHOKE                                      67
#define SPECIES_MACHAMP                                      68
#define SPECIES_BELLSPROUT                                   69
#define SPECIES_WEEPINBELL                                   70
#define SPECIES_VICTREEBEL                                   71
#define SPECIES_TENTACOOL                                    72
#define SPECIES_TENTACRUEL                                   73
#define SPECIES_GEODUDE                                      74
#define SPECIES_GRAVELER                                     75
#define SPECIES_GOLEM                                        76
#define SPECIES_PONYTA                                       77
#define SPECIES_RAPIDASH                                     78
#define SPECIES_SLOWPOKE                                     79
#define SPECIES_SLOWBRO                                      80
#define SPECIES_MAGNEMITE                                    81
#define SPECIES_MAGNETON                                     82
#define SPECIES_FARFETCHD                                    83
#define SPECIES_DODUO                                        84
#define SPECIES_DODRIO                                       85
#define SPECIES_SEEL                                         86
#define SPECIES_DEWGONG                                      87
#define SPECIES_GRIMER                                       88
#define SPECIES_MUK                                          89
#define SPECIES_SHELLDER                                     90
#define SPECIES_CLOYSTER                                     91
#define SPECIES_GASTLY                                       92
#define SPECIES_HAUNTER                                      93
#define SPECIES_GENGAR                                       94
#define SPECIES_ONIX                                         95
#define SPECIES_DROWZEE                                      96
#define SPECIES_HYPNO                                        97
#define SPECIES_KRABBY                                       98
#define SPECIES_KINGLER                                      99
#define SPECIES_VOLTORB                                      100
#define SPECIES_ELECTRODE                                    101
#define SPECIES_EXEGGCUTE                                    102
#define SPECIES_EXEGGUTOR                                    103
#define SPECIES_CUBONE                                       104
#define SPECIES_MAROWAK                                      105
#define SPECIES_HITMONLEE                                    106
#define SPECIES_HITMONCHAN                                   107
#define SPECIES_LICKITUNG                                    108
#define SPECIES_KOFFING                                      109
#define SPECIES_WEEZING                                      110
#define SPECIES_RHYHORN                                      111
#define SPECIES_RHYDON                                       112
#define SPECIES_CHANSEY                                      113
#define SPECIES_TANGELA                                      114
#define SPECIES_KANGASKHAN                                   115
#define SPECIES_HORSEA                                       116
#define SPECIES_SEADRA                                       117
#define SPECIES_GOLDEEN                                      118
#define SPECIES_SEAKING                                      119
#define SPECIES_STARYU                                       120
#define SPECIES_STARMIE                                      121
#define SPECIES_MR_MIME                                      122
#define SPECIES_SCYTHER                                      123
#define SPECIES_JYNX                                         124
#define SPECIES_ELECTABUZZ                                   125
#define SPECIES_MAGMAR                                       126
#define SPECIES_PINSIR                                       127
#define SPECIES_TAUROS                                       128
#define SPECIES_MAGIKARP                                     129
#define SPECIES_GYARADOS                                     130
#define SPECIES_LAPRAS                                       131
#define SPECIES_DITTO                                        132
#define SPECIES_EEVEE                                        133
#define SPECIES_VAPOREON                                     134
#define SPECIES_JOLTEON                                      135
#define SPECIES_FLAREON                                      136
#define SPECIES_PORYGON                                      137
#define SPECIES_OMANYTE                                      138
#define SPECIES_OMASTAR                                      139
#define SPECIES_KABUTO                                       140
#define SPECIES_KABUTOPS                                     141
#define SPECIES_AERODACTYL                                   142
#define SPECIES_SNORLAX                                      143
#define SPECIES_ARTICUNO                                     144
#define SPECIES_ZAPDOS                                       145
#define SPECIES_MOLTRES                                      146
#define SPECIES_DRATINI                                      147
#define SPECIES_DRAGONAIR                                    148
#define SPECIES_DRAGONITE                                    149
#define SPECIES_MEWTWO                                       150
#define SPECIES_MEW                                          151
#define SPECIES_CHIKORITA                                    152
#define SPECIES_BAYLEEF                                      153
#define SPECIES_MEGANIUM                                     154
#define SPECIES_CYNDAQUIL                                    155
#define SPECIES_QUILAVA                                      156
#define SPECIES_TYPHLOSION                                   157
#define SPECIES_TOTODILE                                     158
#define SPECIES_CROCONAW                                     159
#define SPECIES_FERALIGATR                                   160
#define SPECIES_SENTRET                                      161
#define SPECIES_FURRET                                       162
#define SPECIES_HOOTHOOT                                     163
#define SPECIES_NOCTOWL                                      164
#define SPECIES_LEDYBA                                       165
#define SPECIES_LEDIAN                                       166
#define SPECIES_SPINARAK                                     167
#define SPECIES_ARIADOS                                      168
#define SPECIES_CROBAT                                       169
#define SPECIES_CHINCHOU                                     170
#define SPECIES_LANTURN                                      171
#define SPECIES_PICHU                                        172
#define SPECIES_CLEFFA                                       173
#define SPECIES_IGGLYBUFF                                    174
#define SPECIES_TOGEPI                                       175
#define SPECIES_TOGETIC                                      176
#define SPECIES_NATU                                         177
#define SPECIES_XATU                                         178
#define SPECIES_MAREEP                                       179
#define SPECIES_FLAAFFY                                      180
#define SPECIES_AMPHAROS                                     181
#define SPECIES_BELLOSSOM                                    182
#define SPECIES_MARILL                                       183
#define SPECIES_AZUMARILL                                    184
#define SPECIES_SUDOWOODO                                    185
#define SPECIES_POLITOED                                     186
#define SPECIES_HOPPIP                                       187
#define SPECIES_SKIPLOOM                                     188
#define SPECIES_JUMPLUFF                                     189
#define SPECIES_AIPOM                                        190
#define SPECIES_SUNKERN                                      191
#define SPECIES_SUNFLORA                                     192
#define SPECIES_YANMA                                        193
#define SPECIES_WOOPER                                       194
#define SPECIES_QUAGSIRE                                     195
#define SPECIES_ESPEON                                       196
#define SPECIES_UMBREON                                      197
#define SPECIES_MURKROW                                      198
#define SPECIES_SLOWKING                                     199
#define SPECIES_MISDREAVUS                                   200
#define SPECIES_UNOWN                                        201
#define SPECIES_UNOWN_A                                      SPECIES_UNOWN
#define SPECIES_UNOWN_B                                      202
#define SPECIES_UNOWN_C                                      203
#define SPECIES_UNOWN_D                                      204
#define SPECIES_UNOWN_E                                      205
#define SPECIES_UNOWN_F                                      206
#define SPECIES_UNOWN_G                                      207
#define SPECIES_UNOWN_H                                      208
#define SPECIES_UNOWN_I                                      209
#define SPECIES_UNOWN_J                                      210
#define SPECIES_UNOWN_K                                      211
#define SPECIES_UNOWN_L                                      212
#define SPECIES_UNOWN_M                                      213
#define SPECIES_UNOWN_N                                      214
#define SPECIES_UNOWN_O                                      215
#define SPECIES_UNOWN_P                                      216
#define SPECIES_UNOWN_Q                                      217
#define SPECIES_UNOWN_R                                      218
#define SPECIES_UNOWN_S                                      219
#define SPECIES_UNOWN_T                                      220
#define SPECIES_UNOWN_U                                      221
#define SPECIES_UNOWN_V                                      222
#define SPECIES_UNOWN_W                                      223
#define SPECIES_UNOWN_X                                      224
#define SPECIES_UNOWN_Y                                      225
#define SPECIES_UNOWN_Z                                      226
#define SPECIES_UNOWN_EMARK                                  227
#define SPECIES_UNOWN_QMARK                                  228
#define SPECIES_WOBBUFFET                                    229
#define SPECIES_GIRAFARIG                                    230
#define SPECIES_PINECO                                       231
#define SPECIES_FORRETRESS                                   232
#define SPECIES_DUNSPARCE                                    233
#define SPECIES_GLIGAR                                       234
#define SPECIES_STEELIX                                      235
#define SPECIES_SNUBBULL                                     236
#define SPECIES_GRANBULL                                     237
#define SPECIES_QWILFISH                                     238
#define SPECIES_SCIZOR                                       239
#define SPECIES_SHUCKLE                                      240
#define SPECIES_HERACROSS                                    241
#define SPECIES_SNEASEL                                      242
#define SPECIES_TEDDIURSA                                    243
#define SPECIES_URSARING                                     244
#define SPECIES_SLUGMA                                       245
#define SPECIES_MAGCARGO                                     246
#define SPECIES_SWINUB                                       247
#define SPECIES_PILOSWINE                                    248
#define SPECIES_CORSOLA                                      249
#define SPECIES_REMORAID                                     250
#define SPECIES_OCTILLERY                                    251
#define SPECIES_DELIBIRD                                     252
#define SPECIES_MANTINE                                      253
#define SPECIES_SKARMORY                                     254
#define SPECIES_HOUNDOUR                                     255
#define SPECIES_HOUNDOOM                                     256
#define SPECIES_KINGDRA                                      257
#define SPECIES_PHANPY                                       258
#define SPECIES_DONPHAN                                      259
#define SPECIES_PORYGON2                                     260
#define SPECIES_STANTLER                                     261
#define SPECIES_SMEARGLE                                     262
#define SPECIES_TYROGUE                                      263
#define SPECIES_HITMONTOP                                    264
#define SPECIES_SMOOCHUM                                     265
#define SPECIES_ELEKID                                       266
#define SPECIES_MAGBY                                        267
#define SPECIES_MILTANK                                      268
#define SPECIES_BLISSEY                                      269
#define SPECIES_RAIKOU                                       270
#define SPECIES_ENTEI                                        271
#define SPECIES_SUICUNE                                      272
#define SPECIES_LARVITAR                                     273
#define SPECIES_PUPITAR                                      274
#define SPECIES_TYRANITAR                                    275
#define SPECIES_LUGIA                                        276
#define SPECIES_HO_OH                                        277
#define SPECIES_CELEBI                                       278
#define SPECIES_TREECKO                                      279
#define SPECIES_GROVYLE                                      280
#define SPECIES_SCEPTILE                                     281
#define SPECIES_TORCHIC                                      282
#define SPECIES_COMBUSKEN                                    283
#define SPECIES_BLAZIKEN                                     284
#define SPECIES_MUDKIP                                       285
#define SPECIES_MARSHTOMP                                    286
#define SPECIES_SWAMPERT                                     287
#define SPECIES_POOCHYENA                                    288
#define SPECIES_MIGHTYENA                                    289
#define SPECIES_ZIGZAGOON                                    290
#define SPECIES_LINOONE                                      291
#define SPECIES_WURMPLE                                      292
#define SPECIES_SILCOON                                      293
#define SPECIES_BEAUTIFLY                                    294
#define SPECIES_CASCOON                                      295
#define SPECIES_DUSTOX                                       296
#define SPECIES_LOTAD                                        297
#define SPECIES_LOMBRE                                       298
#define SPECIES_LUDICOLO                                     299
#define SPECIES_SEEDOT                                       300
#define SPECIES_NUZLEAF                                      301
#define SPECIES_SHIFTRY                                      302
#define SPECIES_TAILLOW                                      303
#define SPECIES_SWELLOW                                      304
#define SPECIES_WINGULL                                      305
#define SPECIES_PELIPPER                                     306
#define SPECIES_RALTS                                        307
#define SPECIES_KIRLIA                                       308
#define SPECIES_GARDEVOIR                                    309
#define SPECIES_SURSKIT                                      310
#define SPECIES_MASQUERAIN                                   311
#define SPECIES_SHROOMISH                                    312
#define SPECIES_BRELOOM                                      313
#define SPECIES_SLAKOTH                                      314
#define SPECIES_VIGOROTH                                     315
#define SPECIES_SLAKING                                      316
#define SPECIES_NINCADA                                      317
#define SPECIES_NINJASK                                      318
#define SPECIES_SHEDINJA                                     319
#define SPECIES_WHISMUR                                      320
#define SPECIES_LOUDRED                                      321
#define SPECIES_EXPLOUD                                      322
#define SPECIES_MAKUHITA                                     323
#define SPECIES_HARIYAMA                                     324
#define SPECIES_AZURILL                                      325
#define SPECIES_NOSEPASS                                     326
#define SPECIES_SKITTY                                       327
#define SPECIES_DELCATTY                                     328
#define SPECIES_SABLEYE                                      329
#define SPECIES_MAWILE                                       330
#define SPECIES_ARON                                         331
#define SPECIES_LAIRON                                       332
#define SPECIES_AGGRON                                       333
#define SPECIES_MEDITITE                                     334
#define SPECIES_MEDICHAM                                     335
#define SPECIES_ELECTRIKE                                    336
#define SPECIES_MANECTRIC                                    337
#define SPECIES_PLUSLE                                       338
#define SPECIES_MINUN                                        339
#define SPECIES_VOLBEAT                                      340
#define SPECIES_ILLUMISE                                     341
#define SPECIES_ROSELIA                                      342
#define SPECIES_GULPIN                                       343
#define SPECIES_SWALOT                                       344
#define SPECIES_CARVANHA                                     345
#define SPECIES_SHARPEDO                                     346
#define SPECIES_WAILMER                                      347
#define SPECIES_WAILORD                                      348
#define SPECIES_NUMEL                                        349
#define SPECIES_CAMERUPT                                     350
#define SPECIES_TORKOAL                                      351
#define SPECIES_SPOINK                                       352
#define SPECIES_GRUMPIG                                      353
#define SPECIES_SPINDA                                       354
#define SPECIES_TRAPINCH                                     355
#define SPECIES_VIBRAVA                                      356
#define SPECIES_FLYGON                                       357
#define SPECIES_CACNEA                                       358
#define SPECIES_CACTURNE                                     359
#define SPECIES_SWABLU                                       360
#define SPECIES_ALTARIA                                      361
#define SPECIES_ZANGOOSE                                     362
#define SPECIES_SEVIPER                                      363
#define SPECIES_LUNATONE                                     364
#define SPECIES_SOLROCK                                      365
#define SPECIES_BARBOACH                                     366
#define SPECIES_WHISCASH                                     367
#define SPECIES_CORPHISH                                     368
#define SPECIES_CRAWDAUNT                                    369
#define SPECIES_BALTOY                                       370
#define SPECIES_CLAYDOL                                      371
#define SPECIES_LILEEP                                       372
#define SPECIES_CRADILY                                      373
#define SPECIES_ANORITH                                      374
#define SPECIES_ARMALDO                                      375
#define SPECIES_FEEBAS                                       376
#define SPECIES_MILOTIC                                      377
#define SPECIES_CASTFORM                                     378
#define SPECIES_CASTFORM_NORMAL                              SPECIES_CASTFORM
#define SPECIES_CASTFORM_SUNNY                               379
#define SPECIES_CASTFORM_RAINY                               380
#define SPECIES_CASTFORM_SNOWY                               381
#define SPECIES_KECLEON                                      382
#define SPECIES_SHUPPET                                      383
#define SPECIES_BANETTE                                      384
#define SPECIES_DUSKULL                                      385
#define SPECIES_DUSCLOPS                                     386
#define SPECIES_TROPIUS                                      387
#define SPECIES_CHIMECHO                                     388
#define SPECIES_ABSOL                                        389
#define SPECIES_WYNAUT                                       390
#define SPECIES_SNORUNT                                      391
#define SPECIES_GLALIE                                       392
#define SPECIES_SPHEAL                                       393
#define SPECIES_SEALEO                                       394
#define SPECIES_WALREIN                                      395
#define SPECIES_CLAMPERL                                     396
#define SPECIES_HUNTAIL                                      397
#define SPECIES_GOREBYSS                                     398
#define SPECIES_RELICANTH                                    399
#define SPECIES_LUVDISC                                      400
#define SPECIES_BAGON                                        401
#define SPECIES_SHELGON                                      402
#define SPECIES_SALAMENCE                                    403
#define SPECIES_BELDUM                                       404
#define SPECIES_METANG                                       405
#define SPECIES_METAGROSS                                    406
#define SPECIES_REGIROCK                                     407
#define SPECIES_REGICE                                       408
#define SPECIES_REGISTEEL                                    409
#define SPECIES_LATIAS                                       410
#define SPECIES_LATIOS                                       411
#define SPECIES_KYOGRE                                       412
#define SPECIES_GROUDON                                      413
#define SPECIES_RAYQUAZA                                     414
#define SPECIES_JIRACHI                                      415
#define SPECIES_DEOXYS                                       416
#define SPECIES_DEOXYS_NORMAL                                SPECIES_DEOXYS
#define SPECIES_DEOXYS_ATTACK                                417
#define SPECIES_DEOXYS_DEFENSE                               418
#define SPECIES_DEOXYS_SPEED                                 419
// XD: Gale of Darkness
#define SPECIES_LUGIA_SHADOW                                 420 // Todo
// Diamond and Pearl
#define SPECIES_TURTWIG                                      421
#define SPECIES_GROTLE                                       422
#define SPECIES_TORTERRA                                     423
#define SPECIES_CHIMCHAR                                     424
#define SPECIES_MONFERNO                                     425
#define SPECIES_INFERNAPE                                    426
#define SPECIES_PIPLUP                                       427
#define SPECIES_PRINPLUP                                     428
#define SPECIES_EMPOLEON                                     429
#define SPECIES_STARLY                                       430
#define SPECIES_STARAVIA                                     431
#define SPECIES_STARAPTOR                                    432
#define SPECIES_BIDOOF                                       433
#define SPECIES_BIBAREL                                      434
#define SPECIES_KRICKETOT                                    435
#define SPECIES_KRICKETUNE                                   436
#define SPECIES_SHINX                                        437
#define SPECIES_LUXIO                                        438
#define SPECIES_LUXRAY                                       439
#define SPECIES_BUDEW                                        440
#define SPECIES_ROSERADE                                     441
#define SPECIES_CRANIDOS                                     442
#define SPECIES_RAMPARDOS                                    443
#define SPECIES_SHIELDON                                     444
#define SPECIES_BASTIODON                                    445
#define SPECIES_BURMY                                        446
#define SPECIES_BURMY_PLANT_CLOAK                            SPECIES_BURMY
#define SPECIES_BURMY_SANDY_CLOAK                            447
#define SPECIES_BURMY_TRASH_CLOAK                            448
#define SPECIES_WORMADAM                                     449
#define SPECIES_WORMADAM_PLANT_CLOAK                         SPECIES_WORMADAM
#define SPECIES_WORMADAM_SANDY_CLOAK                         450
#define SPECIES_WORMADAM_TRASH_CLOAK                         451
#define SPECIES_MOTHIM                                       452
#define SPECIES_COMBEE                                       453
#define SPECIES_VESPIQUEN                                    454
#define SPECIES_PACHIRISU                                    455
#define SPECIES_BUIZEL                                       456
#define SPECIES_FLOATZEL                                     457
#define SPECIES_CHERUBI                                      458
#define SPECIES_CHERRIM                                      459
#define SPECIES_CHERRIM_OVERCAST                             SPECIES_CHERRIM
#define SPECIES_CHERRIM_SUNSHINE                             460
#define SPECIES_SHELLOS                                      461
#define SPECIES_SHELLOS_WEST_SEA                             SPECIES_SHELLOS
#define SPECIES_SHELLOS_EAST_SEA                             462
#define SPECIES_GASTRODON                                    463
#define SPECIES_GASTRODON_WEST_SEA                           SPECIES_GASTRODON
#define SPECIES_GASTRODON_EAST_SEA                           464
#define SPECIES_AMBIPOM                                      465
#define SPECIES_DRIFLOON                                     466
#define SPECIES_DRIFBLIM                                     467
#define SPECIES_BUNEARY                                      468
#define SPECIES_LOPUNNY                                      469
#define SPECIES_MISMAGIUS                                    470
#define SPECIES_HONCHKROW                                    471
#define SPECIES_GLAMEOW                                      472
#define SPECIES_PURUGLY                                      473
#define SPECIES_CHINGLING                                    474
#define SPECIES_STUNKY                                       475
#define SPECIES_SKUNTANK                                     476
#define SPECIES_BRONZOR                                      477
#define SPECIES_BRONZONG                                     478
#define SPECIES_BONSLY                                       479
#define SPECIES_MIME_JR                                      480
#define SPECIES_HAPPINY                                      481
#define SPECIES_CHATOT                                       482
#define SPECIES_SPIRITOMB                                    483
#define SPECIES_GIBLE                                        484
#define SPECIES_GABITE                                       485
#define SPECIES_GARCHOMP                                     486
#define SPECIES_MUNCHLAX                                     487
#define SPECIES_RIOLU                                        488
#define SPECIES_LUCARIO                                      489
#define SPECIES_HIPPOPOTAS                                   490
#define SPECIES_HIPPOWDON                                    491
#define SPECIES_SKORUPI                                      492
#define SPECIES_DRAPION                                      493
#define SPECIES_CROAGUNK                                     494
#define SPECIES_TOXICROAK                                    495
#define SPECIES_CARNIVINE                                    496
#define SPECIES_FINNEON                                      497
#define SPECIES_LUMINEON                                     498
#define SPECIES_MANTYKE                                      499
#define SPECIES_SNOVER                                       500
#define SPECIES_ABOMASNOW                                    501
#define SPECIES_WEAVILE                                      502
#define SPECIES_MAGNEZONE                                    503
#define SPECIES_LICKILICKY                                   504
#define SPECIES_RHYPERIOR                                    505
#define SPECIES_TANGROWTH                                    506
#define SPECIES_ELECTIVIRE                                   507
#define SPECIES_MAGMORTAR                                    508
#define SPECIES_TOGEKISS                                     509
#define SPECIES_YANMEGA                                      510
#define SPECIES_LEAFEON                                      511
#define SPECIES_GLACEON                                      512
#define SPECIES_GLISCOR                                      513
#define SPECIES_MAMOSWINE                                    514
#define SPECIES_PORYGON_Z                                    515
#define SPECIES_GALLADE                                      516
#define SPECIES_PROBOPASS                                    517
#define SPECIES_DUSKNOIR                                     518
#define SPECIES_FROSLASS                                     519
#define SPECIES_ROTOM                                        520
#define SPECIES_UXIE                                         521
#define SPECIES_MESPRIT                                      522
#define SPECIES_AZELF                                        523
#define SPECIES_DIALGA                                       524
#define SPECIES_PALKIA                                       525
#define SPECIES_HEATRAN                                      526
#define SPECIES_REGIGIGAS                                    527
#define SPECIES_GIRATINA                                     528
#define SPECIES_CRESSELIA                                    529
#define SPECIES_PHIONE                                       530
#define SPECIES_MANAPHY                                      531
#define SPECIES_DARKRAI                                      532
#define SPECIES_SHAYMIN                                      533
#define SPECIES_ARCEUS                                       534
#define SPECIES_ARCEUS_NORMAL                                SPECIES_ARCEUS
#define SPECIES_ARCEUS_FIGHTING                              535
#define SPECIES_ARCEUS_FLYING                                536
#define SPECIES_ARCEUS_POISON                                537
#define SPECIES_ARCEUS_GROUND                                538
#define SPECIES_ARCEUS_ROCK                                  539
#define SPECIES_ARCEUS_BUG                                   540
#define SPECIES_ARCEUS_GHOST                                 541
#define SPECIES_ARCEUS_STEEL                                 542
#define SPECIES_ARCEUS_FIRE                                  543
#define SPECIES_ARCEUS_WATER                                 544
#define SPECIES_ARCEUS_GRASS                                 545
#define SPECIES_ARCEUS_ELECTRIC                              546
#define SPECIES_ARCEUS_PSYCHIC                               547
#define SPECIES_ARCEUS_ICE                                   548
#define SPECIES_ARCEUS_DRAGON                                549
#define SPECIES_ARCEUS_DARK                                  550
// Platinum
#define SPECIES_ROTOM_HEAT                                   551
#define SPECIES_ROTOM_WASH                                   552
#define SPECIES_ROTOM_FROST                                  553
#define SPECIES_ROTOM_FAN                                    554
#define SPECIES_ROTOM_MOW                                    555
#define SPECIES_GIRATINA_ORIGIN                              556
#define SPECIES_SHAYMIN_SKY                                  557
// HeartGold and SoulSilver
#define SPECIES_PICHU_SPIKY_EARED                            558
// Black and White
#define SPECIES_VICTINI                                      559
#define SPECIES_SNIVY                                        560
#define SPECIES_SERVINE                                      561
#define SPECIES_SERPERIOR                                    562
#define SPECIES_TEPIG                                        563
#define SPECIES_PIGNITE                                      564
#define SPECIES_EMBOAR                                       565
#define SPECIES_OSHAWOTT                                     566
#define SPECIES_DEWOTT                                       567
#define SPECIES_SAMUROTT                                     568
#define SPECIES_PATRAT                                       569
#define SPECIES_WATCHOG                                      570
#define SPECIES_LILLIPUP                                     571
#define SPECIES_HERDIER                                      572
#define SPECIES_STOUTLAND                                    573
#define SPECIES_PURRLOIN                                     574
#define SPECIES_LIEPARD                                      575
#define SPECIES_PANSAGE                                      576
#define SPECIES_SIMISAGE                                     577
#define SPECIES_PANSEAR                                      578
#define SPECIES_SIMISEAR                                     579
#define SPECIES_PANPOUR                                      580
#define SPECIES_SIMIPOUR                                     581
#define SPECIES_MUNNA                                        582
#define SPECIES_MUSHARNA                                     583
#define SPECIES_PIDOVE                                       584
#define SPECIES_TRANQUILL                                    585
#define SPECIES_UNFEZANT                                     586
#define SPECIES_BLITZLE                                      587
#define SPECIES_ZEBSTRIKA                                    588
#define SPECIES_ROGGENROLA                                   589
#define SPECIES_BOLDORE                                      590
#define SPECIES_GIGALITH                                     591
#define SPECIES_WOOBAT                                       592
#define SPECIES_SWOOBAT                                      593
#define SPECIES_DRILBUR                                      594
#define SPECIES_EXCADRILL                                    595
#define SPECIES_AUDINO                                       596
#define SPECIES_TIMBURR                                      597
#define SPECIES_GURDURR                                      598
#define SPECIES_CONKELDURR                                   599
#define SPECIES_TYMPOLE                                      600
#define SPECIES_PALPITOAD                                    601
#define SPECIES_SEISMITOAD                                   602
#define SPECIES_THROH                                        603
#define SPECIES_SAWK                                         604
#define SPECIES_SEWADDLE                                     605
#define SPECIES_SWADLOON                                     606
#define SPECIES_LEAVANNY                                     607
#define SPECIES_VENIPEDE                                     608
#define SPECIES_WHIRLIPEDE                                   609
#define SPECIES_SCOLIPEDE                                    610
#define SPECIES_COTTONEE                                     611
#define SPECIES_WHIMSICOTT                                   612
#define SPECIES_PETILIL                                      613
#define SPECIES_LILLIGANT                                    614
#define SPECIES_BASCULIN                                     615
#define SPECIES_BASCULIN_RED_STRIPED                         SPECIES_BASCULIN
#define SPECIES_BASCULIN_BLUE_STRIPED                        616
#define SPECIES_SANDILE                                      617
#define SPECIES_KROKOROK                                     618
#define SPECIES_KROOKODILE                                   619
#define SPECIES_DARUMAKA                                     620
#define SPECIES_DARMANITAN                                   621
#define SPECIES_DARMANITAN_STANDARD_MODE                     SPECIES_DARMANITAN
#define SPECIES_DARMANITAN_ZEN_MODE                          622
#define SPECIES_MARACTUS                                     623
#define SPECIES_DWEBBLE                                      624
#define SPECIES_CRUSTLE                                      625
#define SPECIES_SCRAGGY                                      626
#define SPECIES_SCRAFTY                                      627
#define SPECIES_SIGILYPH                                     628
#define SPECIES_YAMASK                                       629
#define SPECIES_COFAGRIGUS                                   630
#define SPECIES_TIRTOUGA                                     631
#define SPECIES_CARRACOSTA                                   632
#define SPECIES_ARCHEN                                       633
#define SPECIES_ARCHEOPS                                     634
#define SPECIES_TRUBBISH                                     635
#define SPECIES_GARBODOR                                     636
#define SPECIES_ZORUA                                        637
#define SPECIES_ZOROARK                                      638
#define SPECIES_MINCCINO                                     639
#define SPECIES_CINCCINO                                     640
#define SPECIES_GOTHITA                                      641
#define SPECIES_GOTHORITA                                    642
#define SPECIES_GOTHITELLE                                   643
#define SPECIES_SOLOSIS                                      644
#define SPECIES_DUOSION                                      645
#define SPECIES_REUNICLUS                                    646
#define SPECIES_DUCKLETT                                     647
#define SPECIES_SWANNA                                       648
#define SPECIES_VANILLITE                                    649
#define SPECIES_VANILLISH                                    650
#define SPECIES_VANILLUXE                                    651
#define SPECIES_DEERLING                                     652
#define SPECIES_DEERLING_SPRING                              SPECIES_DEERLING
#define SPECIES_DEERLING_SUMMER                              653
#define SPECIES_DEERLING_AUTUMN                              654
#define SPECIES_DEERLING_WINTER                              655
#define SPECIES_SAWSBUCK                                     656
#define SPECIES_SAWSBUCK_SPRING                              SPECIES_SAWSBUCK
#define SPECIES_SAWSBUCK_SUMMER                              657
#define SPECIES_SAWSBUCK_AUTUMN                              658
#define SPECIES_SAWSBUCK_WINTER                              659
#define SPECIES_EMOLGA                                       660
#define SPECIES_KARRABLAST                                   661
#define SPECIES_ESCAVALIER                                   662
#define SPECIES_FOONGUS                                      663
#define SPECIES_AMOONGUSS                                    664
#define SPECIES_FRILLISH                                     665
#define SPECIES_JELLICENT                                    666
#define SPECIES_ALOMOMOLA                                    667
#define SPECIES_JOLTIK                                       668
#define SPECIES_GALVANTULA                                   669
#define SPECIES_FERROSEED                                    670
#define SPECIES_FERROTHORN                                   671
#define SPECIES_KLINK                                        672
#define SPECIES_KLANG                                        673
#define SPECIES_KLINKLANG                                    674
#define SPECIES_TYNAMO                                       675
#define SPECIES_EELEKTRIK                                    676
#define SPECIES_EELEKTROSS                                   677
#define SPECIES_ELGYEM                                       678
#define SPECIES_BEHEEYEM                                     679
#define SPECIES_LITWICK                                      680
#define SPECIES_LAMPENT                                      681
#define SPECIES_CHANDELURE                                   682
#define SPECIES_AXEW                                         683
#define SPECIES_FRAXURE                                      684
#define SPECIES_HAXORUS                                      685
#define SPECIES_CUBCHOO                                      686
#define SPECIES_BEARTIC                                      687
#define SPECIES_CRYOGONAL                                    688
#define SPECIES_SHELMET                                      689
#define SPECIES_ACCELGOR                                     690
#define SPECIES_STUNFISK                                     691
#define SPECIES_MIENFOO                                      692
#define SPECIES_MIENSHAO                                     693
#define SPECIES_DRUDDIGON                                    694
#define SPECIES_GOLETT                                       695
#define SPECIES_GOLURK                                       696
#define SPECIES_PAWNIARD                                     697
#define SPECIES_BISHARP                                      698
#define SPECIES_BOUFFALANT                                   699
#define SPECIES_RUFFLET                                      700
#define SPECIES_BRAVIARY                                     701
#define SPECIES_VULLABY                                      702
#define SPECIES_MANDIBUZZ                                    703
#define SPECIES_HEATMOR                                      704
#define SPECIES_DURANT                                       705
#define SPECIES_DEINO                                        706
#define SPECIES_ZWEILOUS                                     707
#define SPECIES_HYDREIGON                                    708
#define SPECIES_LARVESTA                                     709
#define SPECIES_VOLCARONA                                    710
#define SPECIES_COBALION                                     711
#define SPECIES_TERRAKION                                    712
#define SPECIES_VIRIZION                                     713
#define SPECIES_TORNADUS                                     714
#define SPECIES_TORNADUS_INCARNATE                           SPECIES_TORNADUS
#define SPECIES_THUNDURUS                                    715
#define SPECIES_THUNDURUS_INCARNATE                          SPECIES_THUNDURUS
#define SPECIES_RESHIRAM                                     716
#define SPECIES_ZEKROM                                       717
#define SPECIES_LANDORUS                                     718
#define SPECIES_LANDORUS_INCARNATE                           SPECIES_LANDORUS
#define SPECIES_KYUREM                                       719
#define SPECIES_KELDEO                                       720
#define SPECIES_KELDEO_ORDINARY                              SPECIES_KELDEO
#define SPECIES_MELOETTA                                     721
#define SPECIES_MELOETTA_ARIA                                SPECIES_MELOETTA
#define SPECIES_MELOETTA_PIROUETTE                           722
#define SPECIES_GENESECT                                     723
#define SPECIES_GENESECT_DOUSE_DRIVE                         724
#define SPECIES_GENESECT_SHOCK_DRIVE                         725
#define SPECIES_GENESECT_BURN_DRIVE                          726
#define SPECIES_GENESECT_CHILL_DRIVE                         727
// Black 2 and White 2
#define SPECIES_TORNADUS_THERIAN                             728
#define SPECIES_THUNDURUS_THERIAN                            729
#define SPECIES_LANDORUS_THERIAN                             730
#define SPECIES_KYUREM_WHITE                                 731
#define SPECIES_KYUREM_BLACK                                 732
#define SPECIES_KELDEO_RESOLUTE                              733
// X and Y
#define SPECIES_CHESPIN                                      734
#define SPECIES_QUILLADIN                                    735
#define SPECIES_CHESNAUGHT                                   736
#define SPECIES_FENNEKIN                                     737
#define SPECIES_BRAIXEN                                      738
#define SPECIES_DELPHOX                                      739
#define SPECIES_FROAKIE                                      740
#define SPECIES_FROGADIER                                    741
#define SPECIES_GRENINJA                                     742
#define SPECIES_BUNNELBY                                     743
#define SPECIES_DIGGERSBY                                    744
#define SPECIES_FLETCHLING                                   745
#define SPECIES_FLETCHINDER                                  746
#define SPECIES_TALONFLAME                                   747
#define SPECIES_SCATTERBUG                                   748
#define SPECIES_SPEWPA                                       749
#define SPECIES_VIVILLON                                     750
#define SPECIES_VIVILLON_ICY_SNOW                            SPECIES_VIVILLON
#define SPECIES_VIVILLON_POLAR                               751
#define SPECIES_VIVILLON_TUNDRA                              752
#define SPECIES_VIVILLON_CONTINENTAL                         753
#define SPECIES_VIVILLON_GARDEN                              754
#define SPECIES_VIVILLON_ELEGANT                             755
#define SPECIES_VIVILLON_MEADOW                              756
#define SPECIES_VIVILLON_MODERN                              757
#define SPECIES_VIVILLON_MARINE                              758
#define SPECIES_VIVILLON_ARCHIPELAGO                         759
#define SPECIES_VIVILLON_HIGH_PLAINS                         760
#define SPECIES_VIVILLON_SANDSTORM                           761
#define SPECIES_VIVILLON_RIVER                               762
#define SPECIES_VIVILLON_MONSOON                             763
#define SPECIES_VIVILLON_SAVANNA                             764
#define SPECIES_VIVILLON_SUN                                 765
#define SPECIES_VIVILLON_OCEAN                               766
#define SPECIES_VIVILLON_JUNGLE                              767
#define SPECIES_VIVILLON_FANCY                               768
#define SPECIES_VIVILLON_POKE_BALL                           769
#define SPECIES_LITLEO                                       770
#define SPECIES_PYROAR                                       771
#define SPECIES_FLABEBE                                      772
#define SPECIES_FLABEBE_RED_FLOWER                           SPECIES_FLABEBE
#define SPECIES_FLABEBE_YELLOW_FLOWER                        773
#define SPECIES_FLABEBE_ORANGE_FLOWER                        774
#define SPECIES_FLABEBE_BLUE_FLOWER                          775
#define SPECIES_FLABEBE_WHITE_FLOWER                         776
#define SPECIES_FLOETTE                                      777
#define SPECIES_FLOETTE_RED_FLOWER                           SPECIES_FLOETTE
#define SPECIES_FLOETTE_YELLOW_FLOWER                        778
#define SPECIES_FLOETTE_ORANGE_FLOWER                        779
#define SPECIES_FLOETTE_BLUE_FLOWER                          780
#define SPECIES_FLOETTE_WHITE_FLOWER                         781
#define SPECIES_FLOETTE_ETERNAL_FLOWER                       782
#define SPECIES_FLORGES                                      783
#define SPECIES_FLORGES_RED_FLOWER                           SPECIES_FLORGES
#define SPECIES_FLORGES_YELLOW_FLOWER                        784
#define SPECIES_FLORGES_ORANGE_FLOWER                        785
#define SPECIES_FLORGES_BLUE_FLOWER                          786
#define SPECIES_FLORGES_WHITE_FLOWER                         787
#define SPECIES_SKIDDO                                       788
#define SPECIES_GOGOAT                                       789
#define SPECIES_PANCHAM                                      790
#define SPECIES_PANGORO                                      791
#define SPECIES_FURFROU                                      792
#define SPECIES_FURFROU_NATURAL                              SPECIES_FURFROU
#define SPECIES_FURFROU_HEART_TRIM                           793
#define SPECIES_FURFROU_STAR_TRIM                            794
#define SPECIES_FURFROU_DIAMOND_TRIM                         795
#define SPECIES_FURFROU_DEBUTANTE_TRIM                       796
#define SPECIES_FURFROU_MATRON_TRIM                          797
#define SPECIES_FURFROU_DANDY_TRIM                           798
#define SPECIES_FURFROU_LA_REINE_TRIM                        799
#define SPECIES_FURFROU_KABUKI_TRIM                          800
#define SPECIES_FURFROU_PHARAOH_TRIM                         801
#define SPECIES_ESPURR                                       802
#define SPECIES_MEOWSTIC                                     803
#define SPECIES_MEOWSTIC_MALE                                SPECIES_MEOWSTIC
#define SPECIES_MEOWSTIC_FEMALE                              804
#define SPECIES_HONEDGE                                      805
#define SPECIES_DOUBLADE                                     806
#define SPECIES_AEGISLASH                                    807
#define SPECIES_AEGISLASH_BLADE                              808
#define SPECIES_SPRITZEE                                     809
#define SPECIES_AROMATISSE                                   810
#define SPECIES_SWIRLIX                                      811
#define SPECIES_SLURPUFF                                     812
#define SPECIES_INKAY                                        813
#define SPECIES_MALAMAR                                      814
#define SPECIES_BINACLE                                      815
#define SPECIES_BARBARACLE                                   816
#define SPECIES_SKRELP                                       817
#define SPECIES_DRAGALGE                                     818
#define SPECIES_CLAUNCHER                                    819
#define SPECIES_CLAWITZER                                    820
#define SPECIES_HELIOPTILE                                   821
#define SPECIES_HELIOLISK                                    822
#define SPECIES_TYRUNT                                       823
#define SPECIES_TYRANTRUM                                    824
#define SPECIES_AMAURA                                       825
#define SPECIES_AURORUS                                      826
#define SPECIES_SYLVEON                                      827
#define SPECIES_HAWLUCHA                                     828
#define SPECIES_DEDENNE                                      829
#define SPECIES_CARBINK                                      830
#define SPECIES_GOOMY                                        831
#define SPECIES_SLIGGOO                                      832
#define SPECIES_GOODRA                                       833
#define SPECIES_KLEFKI                                       834
#define SPECIES_PHANTUMP                                     835
#define SPECIES_TREVENANT                                    836
#define SPECIES_PUMPKABOO                                    837
#define SPECIES_PUMPKABOO_AVERAGE                            SPECIES_PUMPKABOO
#define SPECIES_PUMPKABOO_SMALL                              838
#define SPECIES_PUMPKABOO_LARGE                              839
#define SPECIES_PUMPKABOO_SUPER                              840
#define SPECIES_GOURGEIST                                    841
#define SPECIES_GOURGEIST_AVERAGE                            SPECIES_GOURGEIST
#define SPECIES_GOURGEIST_SMALL                              842
#define SPECIES_GOURGEIST_LARGE                              843
#define SPECIES_GOURGEIST_SUPER                              844
#define SPECIES_BERGMITE                                     845
#define SPECIES_AVALUGG                                      846
#define SPECIES_NOIBAT                                       847
#define SPECIES_NOIVERN                                      848
#define SPECIES_XERNEAS                                      849
#define SPECIES_XERNEAS_NEUTRAL                              SPECIES_XERNEAS
#define SPECIES_XERNEAS_ACTIVE                               850
#define SPECIES_YVELTAL                                      851
#define SPECIES_ZYGARDE                                      852
#define SPECIES_DIANCIE                                      853
#define SPECIES_HOOPA                                        854
#define SPECIES_VOLCANION                                    855
#define SPECIES_VENUSAUR_MEGA                                856
#define SPECIES_CHARIZARD_MEGA_X                             857
#define SPECIES_CHARIZARD_MEGA_Y                             858
#define SPECIES_BLASTOISE_MEGA                               859
#define SPECIES_ALAKAZAM_MEGA                                860
#define SPECIES_GENGAR_MEGA                                  861
#define SPECIES_KANGASKHAN_MEGA                              862
#define SPECIES_PINSIR_MEGA                                  863
#define SPECIES_GYARADOS_MEGA                                864
#define SPECIES_AERODACTYL_MEGA                              865
#define SPECIES_MEWTWO_MEGA_X                                866
#define SPECIES_MEWTWO_MEGA_Y                                867
#define SPECIES_AMPHAROS_MEGA                                868
#define SPECIES_SCIZOR_MEGA                                  869
#define SPECIES_HERACROSS_MEGA                               870
#define SPECIES_HOUNDOOM_MEGA                                871
#define SPECIES_TYRANITAR_MEGA                               872
#define SPECIES_BLAZIKEN_MEGA                                873
#define SPECIES_GARDEVOIR_MEGA                               874
#define SPECIES_MAWILE_MEGA                                  875
#define SPECIES_AGGRON_MEGA                                  876
#define SPECIES_MEDICHAM_MEGA                                877
#define SPECIES_MANECTRIC_MEGA                               878
#define SPECIES_BANETTE_MEGA                                 879
#define SPECIES_ABSOL_MEGA                                   880
#define SPECIES_LATIAS_MEGA                                  881
#define SPECIES_LATIOS_MEGA                                  882
#define SPECIES_GARCHOMP_MEGA                                883
#define SPECIES_LUCARIO_MEGA                                 884
#define SPECIES_ABOMASNOW_MEGA                               885
#define SPECIES_ARCEUS_FAIRY                                 886
// Omega Ruby and Alpha Sapphire
#define SPECIES_BEEDRILL_MEGA                                887
#define SPECIES_PIDGEOT_MEGA                                 888
#define SPECIES_PIKACHU_COSPLAY                              889
#define SPECIES_PIKACHU_ROCK_STAR                            890
#define SPECIES_PIKACHU_BELLE                                891
#define SPECIES_PIKACHU_POP_STAR                             892
#define SPECIES_PIKACHU_PH_D                                 893
#define SPECIES_PIKACHU_LIBRE                                894
#define SPECIES_SLOWBRO_MEGA                                 895
#define SPECIES_STEELIX_MEGA                                 896
#define SPECIES_SCEPTILE_MEGA                                897
#define SPECIES_SWAMPERT_MEGA                                898
#define SPECIES_SABLEYE_MEGA                                 899
#define SPECIES_SHARPEDO_MEGA                                900
#define SPECIES_CAMERUPT_MEGA                                901
#define SPECIES_ALTARIA_MEGA                                 902
#define SPECIES_GLALIE_MEGA                                  903
#define SPECIES_SALAMENCE_MEGA                               904
#define SPECIES_METAGROSS_MEGA                               905
#define SPECIES_KYOGRE_PRIMAL                                906
#define SPECIES_GROUDON_PRIMAL                               907
#define SPECIES_RAYQUAZA_MEGA                                908
#define SPECIES_LOPUNNY_MEGA                                 909
#define SPECIES_GALLADE_MEGA                                 910
#define SPECIES_AUDINO_MEGA                                  911
#define SPECIES_DIANCIE_MEGA                                 912
#define SPECIES_HOOPA_UNBOUND                                913
// Sun and Moon
#define SPECIES_ROWLET                                       914
#define SPECIES_DARTRIX                                      915
#define SPECIES_DECIDUEYE                                    916
#define SPECIES_LITTEN                                       917
#define SPECIES_TORRACAT                                     918
#define SPECIES_INCINEROAR                                   919
#define SPECIES_POPPLIO                                      920
#define SPECIES_BRIONNE                                      921
#define SPECIES_PRIMARINA                                    922
#define SPECIES_PIKIPEK                                      923
#define SPECIES_TRUMBEAK                                     924
#define SPECIES_TOUCANNON                                    925
#define SPECIES_YUNGOOS                                      926
#define SPECIES_GUMSHOOS                                     927
#define SPECIES_GRUBBIN                                      928
#define SPECIES_CHARJABUG                                    929
#define SPECIES_VIKAVOLT                                     930
#define SPECIES_CRABRAWLER                                   931
#define SPECIES_CRABOMINABLE                                 932
#define SPECIES_ORICORIO                                     933
#define SPECIES_ORICORIO_POM_POM                             934
#define SPECIES_ORICORIO_PAU                                 935
#define SPECIES_ORICORIO_SENSU                               936
#define SPECIES_CUTIEFLY                                     937
#define SPECIES_RIBOMBEE                                     938
#define SPECIES_ROCKRUFF                                     939
#define SPECIES_LYCANROC                                     940
#define SPECIES_LYCANROC_MIDNIGHT                            941
#define SPECIES_WISHIWASHI                                   942
#define SPECIES_WISHIWASHI_SCHOOL                            943
#define SPECIES_MAREANIE                                     944
#define SPECIES_TOXAPEX                                      945
#define SPECIES_MUDBRAY                                      946
#define SPECIES_MUDSDALE                                     947
#define SPECIES_DEWPIDER                                     948
#define SPECIES_ARAQUANID                                    949
#define SPECIES_FOMANTIS                                     950
#define SPECIES_LURANTIS                                     951
#define SPECIES_MORELULL                                     952
#define SPECIES_SHIINOTIC                                    953
#define SPECIES_SALANDIT                                     954
#define SPECIES_SALAZZLE                                     955
#define SPECIES_STUFFUL                                      956
#define SPECIES_BEWEAR                                       957
#define SPECIES_BOUNSWEET                                    958
#define SPECIES_STEENEE                                      959
#define SPECIES_TSAREENA                                     960
#define SPECIES_COMFEY                                       961
#define SPECIES_ORANGURU                                     962
#define SPECIES_PASSIMIAN                                    963
#define SPECIES_WIMPOD                                       964
#define SPECIES_GOLISOPOD                                    965
#define SPECIES_SANDYGAST                                    966
#define SPECIES_PALOSSAND                                    967
#define SPECIES_PYUKUMUKU                                    968
#define SPECIES_TYPE_NULL                                    969
#define SPECIES_SILVALLY                                     970
#define SPECIES_SILVALLY_FIGHTING                            971
#define SPECIES_SILVALLY_FLYING                              972
#define SPECIES_SILVALLY_POISON                              973
#define SPECIES_SILVALLY_GROUND                              974
#define SPECIES_SILVALLY_ROCK                                975
#define SPECIES_SILVALLY_BUG                                 976
#define SPECIES_SILVALLY_GHOST                               977
#define SPECIES_SILVALLY_STEEL                               978
#define SPECIES_SILVALLY_FIRE                                979
#define SPECIES_SILVALLY_WATER                               980
#define SPECIES_SILVALLY_GRASS                               981
#define SPECIES_SILVALLY_ELECTRIC                            982
#define SPECIES_SILVALLY_PSYCHIC                             983
#define SPECIES_SILVALLY_ICE                                 984
#define SPECIES_SILVALLY_DRAGON                              985
#define SPECIES_SILVALLY_DARK                                986
#define SPECIES_SILVALLY_FAIRY                               987
#define SPECIES_MINIOR                                       988
#define SPECIES_MINIOR_METEOR_ORANGE                         989
#define SPECIES_MINIOR_METEOR_YELLOW                         990
#define SPECIES_MINIOR_METEOR_GREEN                          991
#define SPECIES_MINIOR_METEOR_BLUE                           992
#define SPECIES_MINIOR_METEOR_INDIGO                         993
#define SPECIES_MINIOR_METEOR_VIOLET                         994
#define SPECIES_MINIOR_CORE_RED                              995
#define SPECIES_MINIOR_CORE_ORANGE                           996
#define SPECIES_MINIOR_CORE_YELLOW                           997
#define SPECIES_MINIOR_CORE_GREEN                            998
#define SPECIES_MINIOR_CORE_BLUE                             999
#define SPECIES_MINIOR_CORE_INDIGO                           1000
#define SPECIES_MINIOR_CORE_VIOLET                           1001
#define SPECIES_KOMALA                                       1002
#define SPECIES_TURTONATOR                                   1003
#define SPECIES_TOGEDEMARU                                   1004
#define SPECIES_MIMIKYU                                      1005
#define SPECIES_MIMIKYU_BUSTED                               1006
#define SPECIES_BRUXISH                                      1007
#define SPECIES_DRAMPA                                       1008
#define SPECIES_DHELMISE                                     1009
#define SPECIES_JANGMO_O                                     1010
#define SPECIES_HAKAMO_O                                     1011
#define SPECIES_KOMMO_O                                      1012
#define SPECIES_TAPU_KOKO                                    1013
#define SPECIES_TAPU_LELE                                    1014
#define SPECIES_TAPU_BULU                                    1015
#define SPECIES_TAPU_FINI                                    1016
#define SPECIES_COSMOG                                       1017
#define SPECIES_COSMOEM                                      1018
#define SPECIES_SOLGALEO                                     1019
#define SPECIES_LUNALA                                       1020
#define SPECIES_NIHILEGO                                     1021
#define SPECIES_BUZZWOLE                                     1022
#define SPECIES_PHEROMOSA                                    1023
#define SPECIES_XURKITREE                                    1024
#define SPECIES_CELESTEELA                                   1025
#define SPECIES_KARTANA                                      1026
#define SPECIES_GUZZLORD                                     1027
#define SPECIES_NECROZMA                                     1028
#define SPECIES_MAGEARNA                                     1029
#define SPECIES_MAGEARNA_ORIGINAL_COLOR                      1030
#define SPECIES_MARSHADOW                                    1031
#define SPECIES_RATTATA_ALOLAN                               1032
#define SPECIES_RATICATE_ALOLAN                              1033
#define SPECIES_PIKACHU_ORIGINAL_CAP                         1034
#define SPECIES_PIKACHU_HOENN_CAP                            1035
#define SPECIES_PIKACHU_SINNOH_CAP                           1036
#define SPECIES_PIKACHU_UNOVA_CAP                            1037
#define SPECIES_PIKACHU_KALOS_CAP                            1038
#define SPECIES_PIKACHU_ALOLA_CAP                            1039
#define SPECIES_RAICHU_ALOLAN                                1040
#define SPECIES_SANDSHREW_ALOLAN                             1041
#define SPECIES_SANDSLASH_ALOLAN                             1042
#define SPECIES_VULPIX_ALOLAN                                1043
#define SPECIES_NINETALES_ALOLAN                             1044
#define SPECIES_DIGLETT_ALOLAN                               1045
#define SPECIES_DUGTRIO_ALOLAN                               1046
#define SPECIES_MEOWTH_ALOLAN                                1047
#define SPECIES_PERSIAN_ALOLAN                               1048
#define SPECIES_GEODUDE_ALOLAN                               1049
#define SPECIES_GRAVELER_ALOLAN                              1050
#define SPECIES_GOLEM_ALOLAN                                 1051
#define SPECIES_GRIMER_ALOLAN                                1052
#define SPECIES_MUK_ALOLAN                                   1053
#define SPECIES_EXEGGUTOR_ALOLAN                             1054
#define SPECIES_MAROWAK_ALOLAN                               1055
#define SPECIES_GRENINJA_BATTLE_BOND                         1056
#define SPECIES_GRENINJA_ASH                                 1057
#define SPECIES_ZYGARDE_10                                   1058
#define SPECIES_ZYGARDE_10_POWER_CONSTRUCT                   1059
#define SPECIES_ZYGARDE_50_POWER_CONSTRUCT                   1060
#define SPECIES_ZYGARDE_COMPLETE                             1061
// Ultra Sun and Ultra Moon
#define SPECIES_POIPOLE                                      1062
#define SPECIES_NAGANADEL                                    1063
#define SPECIES_STAKATAKA                                    1064
#define SPECIES_BLACEPHALON                                  1065
#define SPECIES_ZERAORA                                      1066
#define SPECIES_PIKACHU_PARTNER_CAP                          1067
#define SPECIES_ROCKRUFF_OWN_TEMPO                           1068
#define SPECIES_LYCANROC_DUSK                                1069
#define SPECIES_NECROZMA_DUSK_MANE                           1070
#define SPECIES_NECROZMA_DAWN_WINGS                          1071
#define SPECIES_NECROZMA_ULTRA                               1072
// Let's Go Pikachu and Eevee
#define SPECIES_MELTAN                                       1073
#define SPECIES_MELMETAL                                     1074
#define SPECIES_PIKACHU_PARTNER                              1075 // Todo
#define SPECIES_EEVEE_PARTNER                                1076 // Todo
// Sword and Shield
#define SPECIES_GROOKEY                                      1077
#define SPECIES_THWACKEY                                     1078
#define SPECIES_RILLABOOM                                    1079
#define SPECIES_SCORBUNNY                                    1080
#define SPECIES_RABOOT                                       1081
#define SPECIES_CINDERACE                                    1082
#define SPECIES_SOBBLE                                       1083
#define SPECIES_DRIZZILE                                     1084
#define SPECIES_INTELEON                                     1085
#define SPECIES_SKWOVET                                      1086
#define SPECIES_GREEDENT                                     1087
#define SPECIES_ROOKIDEE                                     1088
#define SPECIES_CORVISQUIRE                                  1089
#define SPECIES_CORVIKNIGHT                                  1090
#define SPECIES_CORVIKNIGHT_GIGANTAMAX                       1091
#define SPECIES_BLIPBUG                                      1092
#define SPECIES_DOTTLER                                      1093
#define SPECIES_ORBEETLE                                     1094
#define SPECIES_ORBEETLE_GIGANTAMAX                          1095
#define SPECIES_NICKIT                                       1096
#define SPECIES_THIEVUL                                      1097
#define SPECIES_GOSSIFLEUR                                   1098
#define SPECIES_ELDEGOSS                                     1099
#define SPECIES_WOOLOO                                       1100
#define SPECIES_DUBWOOL                                      1101
#define SPECIES_CHEWTLE                                      1102
#define SPECIES_DREDNAW                                      1103
#define SPECIES_DREDNAW_GIGANTAMAX                           1104
#define SPECIES_YAMPER                                       1105
#define SPECIES_BOLTUND                                      1106
#define SPECIES_ROLYCOLY                                     1107
#define SPECIES_CARKOL                                       1108
#define SPECIES_COALOSSAL                                    1109
#define SPECIES_COALOSSAL_GIGANTAMAX                         1110
#define SPECIES_APPLIN                                       1111
#define SPECIES_FLAPPLE                                      1112
#define SPECIES_FLAPPLE_GIGANTAMAX                           1113
#define SPECIES_APPLETUN                                     1114
#define SPECIES_APPLETUN_GIGANTAMAX                          1115
#define SPECIES_SILICOBRA                                    1116
#define SPECIES_SANDACONDA                                   1117
#define SPECIES_SANDACONDA_GIGANTAMAX                        1118
#define SPECIES_CRAMORANT                                    1119
#define SPECIES_CRAMORANT_GULPING                            1120
#define SPECIES_CRAMORANT_GORGING                            1121
#define SPECIES_ARROKUDA                                     1122
#define SPECIES_BARRASKEWDA                                  1123
#define SPECIES_TOXEL                                        1124
#define SPECIES_TOXTRICITY                                   1125
#define SPECIES_TOXTRICITY_AMPED                             SPECIES_TOXTRICITY
#define SPECIES_TOXTRICITY_AMPED_GIGANTAMAX                  1126
#define SPECIES_TOXTRICITY_LOW_KEY                           1127
#define SPECIES_TOXTRICITY_LOW_KEY_GIGANTAMAX                1128
#define SPECIES_SIZZLIPEDE                                   1129
#define SPECIES_CENTISKORCH                                  1130
#define SPECIES_CENTISKORCH_GIGANTAMAX                       1131
#define SPECIES_CLOBBOPUS                                    1132
#define SPECIES_GRAPPLOCT                                    1133
#define SPECIES_SINISTEA                                     1134
#define SPECIES_SINISTEA_PHONY                               SPECIES_SINISTEA
#define SPECIES_SINISTEA_ANTIQUE                             1135
#define SPECIES_POLTEAGEIST                                  1136
#define SPECIES_POLTEAGEIST_PHONY                            SPECIES_POLTEAGEIST
#define SPECIES_POLTEAGEIST_ANTIQUE                          1137
#define SPECIES_HATENNA                                      1138
#define SPECIES_HATTREM                                      1139
#define SPECIES_HATTERENE                                    1140
#define SPECIES_HATTERENE_GIGANTAMAX                         1141
#define SPECIES_IMPIDIMP                                     1142
#define SPECIES_MORGREM                                      1143
#define SPECIES_GRIMMSNARL                                   1144
#define SPECIES_GRIMMSNARL_GIGANTAMAX                        1145
#define SPECIES_OBSTAGOON                                    1146
#define SPECIES_PERRSERKER                                   1147
#define SPECIES_CURSOLA                                      1148
#define SPECIES_SIRFETCHD                                    1149
#define SPECIES_MR_RIME                                      1150
#define SPECIES_RUNERIGUS                                    1151
#define SPECIES_MILCERY                                      1152
#define SPECIES_ALCREMIE                                     1153
#define SPECIES_ALCREMIE_STRAWBERRY_VANILLA_CREAM            SPECIES_ALCREMIE
#define SPECIES_ALCREMIE_STRAWBERRY_VANILLA_CREAM_GIGANTAMAX 1154
#define SPECIES_ALCREMIE_STRAWBERRY_RUBY_CREAM               1155
#define SPECIES_ALCREMIE_STRAWBERRY_RUBY_CREAM_GIGANTAMAX    1156
#define SPECIES_ALCREMIE_STRAWBERRY_MATCHA_CREAM             1157
#define SPECIES_ALCREMIE_STRAWBERRY_MATCHA_CREAM_GIGANTAMAX  1158
#define SPECIES_ALCREMIE_STRAWBERRY_MINT_CREAM               1159
#define SPECIES_ALCREMIE_STRAWBERRY_MINT_CREAM_GIGANTAMAX    1160
#define SPECIES_ALCREMIE_STRAWBERRY_LEMON_CREAM              1161
#define SPECIES_ALCREMIE_STRAWBERRY_LEMON_CREAM_GIGANTAMAX   1162
#define SPECIES_ALCREMIE_STRAWBERRY_SALTED_CREAM             1163
#define SPECIES_ALCREMIE_STRAWBERRY_SALTED_CREAM_GIGANTAMAX  1164
#define SPECIES_ALCREMIE_STRAWBERRY_RUBY_SWIRL               1165
#define SPECIES_ALCREMIE_STRAWBERRY_RUBY_SWIRL_GIGANTAMAX    1166
#define SPECIES_ALCREMIE_STRAWBERRY_CARAMEL_SWIRL            1167
#define SPECIES_ALCREMIE_STRAWBERRY_CARAMEL_SWIRL_GIGANTAMAX 1168
#define SPECIES_ALCREMIE_STRAWBERRY_RAINBOW_SWIRL            1169
#define SPECIES_ALCREMIE_STRAWBERRY_RAINBOW_SWIRL_GIGANTAMAX 1170
#define SPECIES_ALCREMIE_BERRY_VANILLA_CREAM                 1171
#define SPECIES_ALCREMIE_BERRY_VANILLA_CREAM_GIGANTAMAX      1172
#define SPECIES_ALCREMIE_BERRY_RUBY_CREAM                    1173
#define SPECIES_ALCREMIE_BERRY_RUBY_CREAM_GIGANTAMAX         1174
#define SPECIES_ALCREMIE_BERRY_MATCHA_CREAM                  1175
#define SPECIES_ALCREMIE_BERRY_MATCHA_CREAM_GIGANTAMAX       1176
#define SPECIES_ALCREMIE_BERRY_MINT_CREAM                    1177
#define SPECIES_ALCREMIE_BERRY_MINT_CREAM_GIGANTAMAX         1178
#define SPECIES_ALCREMIE_BERRY_LEMON_CREAM                   1179
#define SPECIES_ALCREMIE_BERRY_LEMON_CREAM_GIGANTAMAX        1180
#define SPECIES_ALCREMIE_BERRY_SALTED_CREAM                  1181
#define SPECIES_ALCREMIE_BERRY_SALTED_CREAM_GIGANTAMAX       1182
#define SPECIES_ALCREMIE_BERRY_RUBY_SWIRL                    1183
#define SPECIES_ALCREMIE_BERRY_RUBY_SWIRL_GIGANTAMAX         1184
#define SPECIES_ALCREMIE_BERRY_CARAMEL_SWIRL                 1185
#define SPECIES_ALCREMIE_BERRY_CARAMEL_SWIRL_GIGANTAMAX      1186
#define SPECIES_ALCREMIE_BERRY_RAINBOW_SWIRL                 1187
#define SPECIES_ALCREMIE_BERRY_RAINBOW_SWIRL_GIGANTAMAX      1188
#define SPECIES_ALCREMIE_LOVE_VANILLA_CREAM                  1189
#define SPECIES_ALCREMIE_LOVE_VANILLA_CREAM_GIGANTAMAX       1190
#define SPECIES_ALCREMIE_LOVE_RUBY_CREAM                     1191
#define SPECIES_ALCREMIE_LOVE_RUBY_CREAM_GIGANTAMAX          1192
#define SPECIES_ALCREMIE_LOVE_MATCHA_CREAM                   1193
#define SPECIES_ALCREMIE_LOVE_MATCHA_CREAM_GIGANTAMAX        1194
#define SPECIES_ALCREMIE_LOVE_MINT_CREAM                     1195
#define SPECIES_ALCREMIE_LOVE_MINT_CREAM_GIGANTAMAX          1196
#define SPECIES_ALCREMIE_LOVE_LEMON_CREAM                    1197
#define SPECIES_ALCREMIE_LOVE_LEMON_CREAM_GIGANTAMAX         1198
#define SPECIES_ALCREMIE_LOVE_SALTED_CREAM                   1199
#define SPECIES_ALCREMIE_LOVE_SALTED_CREAM_GIGANTAMAX        1200
#define SPECIES_ALCREMIE_LOVE_RUBY_SWIRL                     1201
#define SPECIES_ALCREMIE_LOVE_RUBY_SWIRL_GIGANTAMAX          1202
#define SPECIES_ALCREMIE_LOVE_CARAMEL_SWIRL                  1203
#define SPECIES_ALCREMIE_LOVE_CARAMEL_SWIRL_GIGANTAMAX       1204
#define SPECIES_ALCREMIE_LOVE_RAINBOW_SWIRL                  1205
#define SPECIES_ALCREMIE_LOVE_RAINBOW_SWIRL_GIGANTAMAX       1206
#define SPECIES_ALCREMIE_STAR_VANILLA_CREAM                  1207
#define SPECIES_ALCREMIE_STAR_VANILLA_CREAM_GIGANTAMAX       1208
#define SPECIES_ALCREMIE_STAR_RUBY_CREAM                     1209
#define SPECIES_ALCREMIE_STAR_RUBY_CREAM_GIGANTAMAX          1210
#define SPECIES_ALCREMIE_STAR_MATCHA_CREAM                   1211
#define SPECIES_ALCREMIE_STAR_MATCHA_CREAM_GIGANTAMAX        1212
#define SPECIES_ALCREMIE_STAR_MINT_CREAM                     1213
#define SPECIES_ALCREMIE_STAR_MINT_CREAM_GIGANTAMAX          1214
#define SPECIES_ALCREMIE_STAR_LEMON_CREAM                    1215
#define SPECIES_ALCREMIE_STAR_LEMON_CREAM_GIGANTAMAX         1216
#define SPECIES_ALCREMIE_STAR_SALTED_CREAM                   1217
#define SPECIES_ALCREMIE_STAR_SALTED_CREAM_GIGANTAMAX        1218
#define SPECIES_ALCREMIE_STAR_RUBY_SWIRL                     1219
#define SPECIES_ALCREMIE_STAR_RUBY_SWIRL_GIGANTAMAX          1220
#define SPECIES_ALCREMIE_STAR_CARAMEL_SWIRL                  1221
#define SPECIES_ALCREMIE_STAR_CARAMEL_SWIRL_GIGANTAMAX       1222
#define SPECIES_ALCREMIE_STAR_RAINBOW_SWIRL                  1223
#define SPECIES_ALCREMIE_STAR_RAINBOW_SWIRL_GIGANTAMAX       1224
#define SPECIES_ALCREMIE_CLOVER_VANILLA_CREAM                1225
#define SPECIES_ALCREMIE_CLOVER_VANILLA_CREAM_GIGANTAMAX     1226
#define SPECIES_ALCREMIE_CLOVER_RUBY_CREAM                   1227
#define SPECIES_ALCREMIE_CLOVER_RUBY_CREAM_GIGANTAMAX        1228
#define SPECIES_ALCREMIE_CLOVER_MATCHA_CREAM                 1229
#define SPECIES_ALCREMIE_CLOVER_MATCHA_CREAM_GIGANTAMAX      1230
#define SPECIES_ALCREMIE_CLOVER_MINT_CREAM                   1231
#define SPECIES_ALCREMIE_CLOVER_MINT_CREAM_GIGANTAMAX        1232
#define SPECIES_ALCREMIE_CLOVER_LEMON_CREAM                  1233
#define SPECIES_ALCREMIE_CLOVER_LEMON_CREAM_GIGANTAMAX       1234
#define SPECIES_ALCREMIE_CLOVER_SALTED_CREAM                 1235
#define SPECIES_ALCREMIE_CLOVER_SALTED_CREAM_GIGANTAMAX      1236
#define SPECIES_ALCREMIE_CLOVER_RUBY_SWIRL                   1237
#define SPECIES_ALCREMIE_CLOVER_RUBY_SWIRL_GIGANTAMAX        1238
#define SPECIES_ALCREMIE_CLOVER_CARAMEL_SWIRL                1239
#define SPECIES_ALCREMIE_CLOVER_CARAMEL_SWIRL_GIGANTAMAX     1240
#define SPECIES_ALCREMIE_CLOVER_RAINBOW_SWIRL                1241
#define SPECIES_ALCREMIE_CLOVER_RAINBOW_SWIRL_GIGANTAMAX     1242
#define SPECIES_ALCREMIE_FLOWER_VANILLA_CREAM                1243
#define SPECIES_ALCREMIE_FLOWER_VANILLA_CREAM_GIGANTAMAX     1244
#define SPECIES_ALCREMIE_FLOWER_RUBY_CREAM                   1245
#define SPECIES_ALCREMIE_FLOWER_RUBY_CREAM_GIGANTAMAX        1246
#define SPECIES_ALCREMIE_FLOWER_MATCHA_CREAM                 1247
#define SPECIES_ALCREMIE_FLOWER_MATCHA_CREAM_GIGANTAMAX      1248
#define SPECIES_ALCREMIE_FLOWER_MINT_CREAM                   1249
#define SPECIES_ALCREMIE_FLOWER_MINT_CREAM_GIGANTAMAX        1250
#define SPECIES_ALCREMIE_FLOWER_LEMON_CREAM                  1251
#define SPECIES_ALCREMIE_FLOWER_LEMON_CREAM_GIGANTAMAX       1252
#define SPECIES_ALCREMIE_FLOWER_SALTED_CREAM                 1253
#define SPECIES_ALCREMIE_FLOWER_SALTED_CREAM_GIGANTAMAX      1254
#define SPECIES_ALCREMIE_FLOWER_RUBY_SWIRL                   1255
#define SPECIES_ALCREMIE_FLOWER_RUBY_SWIRL_GIGANTAMAX        1256
#define SPECIES_ALCREMIE_FLOWER_CARAMEL_SWIRL                1257
#define SPECIES_ALCREMIE_FLOWER_CARAMEL_SWIRL_GIGANTAMAX     1258
#define SPECIES_ALCREMIE_FLOWER_RAINBOW_SWIRL                1259
#define SPECIES_ALCREMIE_FLOWER_RAINBOW_SWIRL_GIGANTAMAX     1260
#define SPECIES_ALCREMIE_RIBBON_VANILLA_CREAM                1261
#define SPECIES_ALCREMIE_RIBBON_VANILLA_CREAM_GIGANTAMAX     1262
#define SPECIES_ALCREMIE_RIBBON_RUBY_CREAM                   1263
#define SPECIES_ALCREMIE_RIBBON_RUBY_CREAM_GIGANTAMAX        1264
#define SPECIES_ALCREMIE_RIBBON_MATCHA_CREAM                 1265
#define SPECIES_ALCREMIE_RIBBON_MATCHA_CREAM_GIGANTAMAX      1266
#define SPECIES_ALCREMIE_RIBBON_MINT_CREAM                   1267
#define SPECIES_ALCREMIE_RIBBON_MINT_CREAM_GIGANTAMAX        1268
#define SPECIES_ALCREMIE_RIBBON_LEMON_CREAM                  1269
#define SPECIES_ALCREMIE_RIBBON_LEMON_CREAM_GIGANTAMAX       1270
#define SPECIES_ALCREMIE_RIBBON_SALTED_CREAM                 1271
#define SPECIES_ALCREMIE_RIBBON_SALTED_CREAM_GIGANTAMAX      1272
#define SPECIES_ALCREMIE_RIBBON_RUBY_SWIRL                   1273
#define SPECIES_ALCREMIE_RIBBON_RUBY_SWIRL_GIGANTAMAX        1274
#define SPECIES_ALCREMIE_RIBBON_CARAMEL_SWIRL                1275
#define SPECIES_ALCREMIE_RIBBON_CARAMEL_SWIRL_GIGANTAMAX     1276
#define SPECIES_ALCREMIE_RIBBON_RAINBOW_SWIRL                1277
#define SPECIES_ALCREMIE_RIBBON_RAINBOW_SWIRL_GIGANTAMAX     1278
#define SPECIES_FALINKS                                      1279
#define SPECIES_PINCURCHIN                                   1280
#define SPECIES_SNOM                                         1281
#define SPECIES_FROSMOTH                                     1282
#define SPECIES_STONJOURNER                                  1283
#define SPECIES_EISCUE                                       1284
#define SPECIES_EISCUE_ICE_FACE                              SPECIES_EISCUE
#define SPECIES_EISCUE_NOICE_FACE                            1285
#define SPECIES_INDEEDEE                                     1286
#define SPECIES_INDEEDEE_MALE                                SPECIES_INDEEDEE
#define SPECIES_INDEEDEE_FEMALE                              1287
#define SPECIES_MORPEKO                                      1288
#define SPECIES_MORPEKO_FULL_BELLY                           SPECIES_MORPEKO
#define SPECIES_MORPEKO_HANGRY                               1289
#define SPECIES_CUFANT                                       1290
#define SPECIES_COPPERAJAH                                   1291
#define SPECIES_COPPERAJAH_GIGANTAMAX                        1292
#define SPECIES_DRACOZOLT                                    1293
#define SPECIES_ARCTOZOLT                                    1294
#define SPECIES_DRACOVISH                                    1295
#define SPECIES_ARCTOVISH                                    1296
#define SPECIES_DURALUDON                                    1297
#define SPECIES_DURALUDON_GIGANTAMAX                         1298
#define SPECIES_DREEPY                                       1299
#define SPECIES_DRAKLOAK                                     1300
#define SPECIES_DRAGAPULT                                    1301
#define SPECIES_ZACIAN                                       1302
#define SPECIES_ZACIAN_HERO_OF_MANY_BATTLES                  SPECIES_ZACIAN
#define SPECIES_ZACIAN_CROWNED_SWORD                         1303
#define SPECIES_ZAMAZENTA                                    1304
#define SPECIES_ZAMAZENTA_HERO_OF_MANY_BATTLES               SPECIES_ZAMAZENTA
#define SPECIES_ZAMAZENTA_CROWNED_SHIELD                     1305
#define SPECIES_ETERNATUS                                    1306
#define SPECIES_ETERNATUS_ETERNAMAX                          1307
#define SPECIES_CHARIZARD_GIGANTAMAX                         1308
#define SPECIES_BUTTERFREE_GIGANTAMAX                        1309
#define SPECIES_PIKACHU_WORLD_CAP                            1310
#define SPECIES_PIKACHU_GIGANTAMAX                           1311
#define SPECIES_MEOWTH_GIGANTAMAX                            1312
#define SPECIES_MEOWTH_GALARIAN                              1313
#define SPECIES_MACHAMP_GIGANTAMAX                           1314
#define SPECIES_PONYTA_GALARIAN                              1315
#define SPECIES_RAPIDASH_GALARIAN                            1316
#define SPECIES_FARFETCHD_GALARIAN                           1317
#define SPECIES_GENGAR_GIGANTAMAX                            1318
#define SPECIES_KINGLER_GIGANTAMAX                           1319
#define SPECIES_WEEZING_GALARIAN                             1320
#define SPECIES_MR_MIME_GALARIAN                             1321
#define SPECIES_LAPRAS_GIGANTAMAX                            1322
#define SPECIES_EEVEE_GIGANTAMAX                             1323
#define SPECIES_SNORLAX_GIGANTAMAX                           1324
#define SPECIES_CORSOLA_GALARIAN                             1325
#define SPECIES_ZIGZAGOON_GALARIAN                           1326
#define SPECIES_LINOONE_GALARIAN                             1327
#define SPECIES_DARUMAKA_GALARIAN                            1328
#define SPECIES_DARMANITAN_GALARIAN                          1329
#define SPECIES_DARMANITAN_GALARIAN_ZEN_MODE                 1330
#define SPECIES_YAMASK_GALARIAN                              1331
#define SPECIES_GARBODOR_GIGANTAMAX                          1332
#define SPECIES_STUNFISK_GALARIAN                            1333
#define SPECIES_MELMETAL_GIGANTAMAX                          1334
// Sword and Shield 1.1.0
#define SPECIES_SLOWPOKE_GALARIAN                            1335
// The Isle of Armor
#define SPECIES_KUBFU                                        1336
#define SPECIES_URSHIFU                                      1337
#define SPECIES_URSHIFU_SINGLE_STRIKE_STYLE                  SPECIES_URSHIFU
#define SPECIES_URSHIFU_SINGLE_STRIKE_STYLE_GIGANTAMAX       1338
#define SPECIES_URSHIFU_RAPID_STRIKE_STYLE                   1339
#define SPECIES_URSHIFU_RAPID_STRIKE_STYLE_GIGANTAMAX        1340
#define SPECIES_ZARUDE                                       1341
#define SPECIES_ZARUDE_DADA                                  1342
#define SPECIES_VENUSAUR_GIGANTAMAX                          1343
#define SPECIES_BLASTOISE_GIGANTAMAX                         1344
#define SPECIES_SLOWBRO_GALARIAN                             1345
#define SPECIES_RILLABOOM_GIGANTAMAX                         1346
#define SPECIES_CINDERACE_GIGANTAMAX                         1347
#define SPECIES_INTELEON_GIGANTAMAX                          1348
// The Crown Tundra
#define SPECIES_REGIELEKI                                    1349
#define SPECIES_REGIDRAGO                                    1350
#define SPECIES_GLASTRIER                                    1351
#define SPECIES_SPECTRIER                                    1352
#define SPECIES_CALYREX                                      1353
#define SPECIES_CALYREX_ICE_RIDER                            1354
#define SPECIES_CALYREX_SHADOW_RIDER                         1355
#define SPECIES_ARTICUNO_GALARIAN                            1356
#define SPECIES_ZAPDOS_GALARIAN                              1357
#define SPECIES_MOLTRES_GALARIAN                             1358
#define SPECIES_SLOWKING_GALARIAN                            1359
// Legends: Arceus
#define SPECIES_WYRDEER                                      1360
#define SPECIES_KLEAVOR                                      1361
#define SPECIES_URSALUNA                                     1362
#define SPECIES_BASCULEGION                                  1363
#define SPECIES_SNEASLER                                     1364
#define SPECIES_OVERQWIL                                     1365
#define SPECIES_ENAMORUS                                     1366
#define SPECIES_ENAMORUS_THERIAN                             1367
#define SPECIES_GROWLITHE_HISUIAN                            1368
#define SPECIES_ARCANINE_HISUIAN                             1369
#define SPECIES_VOLTORB_HISUIAN                              1370
#define SPECIES_ELECTRODE_HISUIAN                            1371
#define SPECIES_TYPHLOSION_HISUIAN                           1372
#define SPECIES_QWILFISH_HISUIAN                             1373
#define SPECIES_SNEASEL_HISUIAN                              1374
#define SPECIES_DIALGA_ORIGIN                                1375
#define SPECIES_PALKIA_ORIGIN                                1376
#define SPECIES_SAMUROTT_HISUIAN                             1377
#define SPECIES_LILLIGANT_HISUIAN                            1378
#define SPECIES_BASCULIN_WHITE_STRIPED                       1379
#define SPECIES_ZORUA_HISUIAN                                1380
#define SPECIES_ZOROARK_HISUIAN                              1381
#define SPECIES_BRAVIARY_HISUIAN                             1382
#define SPECIES_SLIGGOO_HISUIAN                              1383
#define SPECIES_GOODRA_HISUIAN                               1384
#define SPECIES_AVALUGG_HISUIAN                              1385
#define SPECIES_DECIDUEYE_HISUIAN                            1386

#define SPECIES_EGG                                          SPECIES_DECIDUEYE_HISUIAN + 1

#define NUM_SPECIES SPECIES_EGG

#endif  // GUARD_CONSTANTS_SPECIES_H
