ChiiTown_House2_MapScripts::
	.byte 0


ChiiTown_House2_Child::
# 8 "data/maps/ChiiTown_House2/scripts.pory"
	msgbox ChiiTown_House2_Child_Text_0, MSGBOX_NPC
	return


ChiiTown_House2_Parent::
# 16 "data/maps/ChiiTown_House2/scripts.pory"
	msgbox ChiiTown_House2_Parent_Text_0, MSGBOX_NPC
	return


ChiiTown_House2_Child_Text_0:
# 9 "data/maps/ChiiTown_House2/scripts.pory"
	.string "Mama said there's a BIIIG library in a\n"
	.string "town far away from here!\p"
	.string "One day, I'll read ALLLL the books in\n"
	.string "that library!$"

ChiiTown_House2_Parent_Text_0:
# 17 "data/maps/ChiiTown_House2/scripts.pory"
	.string "My daughter loves reading. I don't read\n"
	.string "her bedtime stories, she reads them to\l"
	.string "me!$"
