Silveridge_House2_MapScripts::
	.byte 0


Silveridge_House2_EventScript_Woman::
# 6 "data/maps/Silveridge_House2/scripts.pory"
	lock
# 7 "data/maps/Silveridge_House2/scripts.pory"
	faceplayer
# 8 "data/maps/Silveridge_House2/scripts.pory"
	speakername Silveridge_House2_EventScript_Woman_Text_0
# 9 "data/maps/Silveridge_House2/scripts.pory"
	msgbox Silveridge_House2_EventScript_Woman_Text_1
# 12 "data/maps/Silveridge_House2/scripts.pory"
	closemessage
# 13 "data/maps/Silveridge_House2/scripts.pory"
	release
	return


Silveridge_House2_EventScript_Woman_Text_0:
# 8 "data/maps/Silveridge_House2/scripts.pory"
	.string "Woman$"

Silveridge_House2_EventScript_Woman_Text_1:
# 10 "data/maps/Silveridge_House2/scripts.pory"
	.string "TODO EVA$"
