PetalburgClub_2F_MapScripts::
	.byte 0

@ Battle format: four trainers in a row with no healing, final trainer
@ each time is Aaron
@ The first time you beat each of the four trainers you get a unique reward:
@ 1 Badge: Revive, Full Restore, Nugget, Leftovers
@ 3 Badges: Adamant Mint, Max Revive, Jolly Mint, Macho Brace (? remove from route 111)
@ 5 Badges:
@ 7 Badges:

@ Each time trainers become more difficult
@ Battles can be re-run after initially defeating and will reward a nugget at the end
@ and/or EV reducing berries
