gText_Birch_Welcome::
	.string "Hello there!\n"
	.string "Welcome to the POKéMON-Lottery.\l"
	.string "have you participated before? Let me\l"
	.string "quickly explain what this is all about.\p"
	.string "Each week I, BIRCH the POKéMON\n"
	.string "PROFESSOR, give away one of three\l"
	.string "POKéMON to a random person who has\l"
	.string "entered the draw.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is the prize POKéMON last week's\n"
	.string "winner chose from their selection.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "It's a LOTAD, a Grass-Water Type which\n"
	.string "will evolve twice if raised well, that\l"
	.string "theme follows through with all our\l"
	.string "giveaways.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Meaning the winner and their POKéMON\n"
	.string "have the chance to grow closer and\l"
	.string "stronger alongside each other,\l"
	.string "resulting in better battle synergies.\p"
	.string "...\p"
	.string "...well that's the theory I am trying to\n"
	.string "prove.\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "…anyways, are you in?\p"
	.string "...\p"
	.string "I will need to know a bit of\n"
	.string "information about you.\p"
	.string "Would you like to be represented by a\l"
	.string "BOY or GIRL sprite?\p"
	.string "$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Alright that's all the info we need.\n"
	.string "You're {PLAYER}{KUN} who's just about to\l"
	.string "move from PETALBURG CITY to\l"
	.string "LITTLEROOT. Thanks for the\l"
	.string "registration. Make sure to tune in when\l"
	.string "we announce the winner live on TV.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Oh! You are moving to LITTLEROOT right\n"
	.string "now? That's why you were headed for\l"
	.string "that truck.\p"
	.string "If you are lucky with traffic and quick\n"
	.string "in setting up your Television you might\l"
	.string "still be able to catch this weeks\l"
	.string "lottery live.\p"
	.string "Safe travels!\p"
	.string "$"
