Text_PictureBookShelf:
	.string "There's a set of POKéMON picture books.$"

Text_BookShelf:
	.string "It's filled with all sorts of books.$"

Text_PokemonCenterBookShelf:
	.string "POKéMON magazines!\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "ADORABLE POKéMON…$"

Text_Vase:
	.string "This vase looks expensive…\n"
	.string "Peered inside…\p"
	.string "But, it was empty.$"

Text_EmptyTrashCan:
	.string "It's empty.$"

Text_ShopShelf:
	.string "The shelves brim with all sorts of\n"
	.string "POKéMON merchandise.$"

Text_Blueprint:
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"

Text_ClayPot:
	.string "A simple clay pot.\p"
	.string "{PLAYER} suddenly feels an urge to\nbreak it.$"

Text_Furnace:
	.string "The fire dances in the furnace.\p"
	.string "…Hey, there's a Slugma in here!$"

Text_EmptyBasket:
	.string "A woven basket.$"
	
Text_BasketRyss:
	.string "A basket filled with Ryss berries.$"
	
Text_Bonsai:
	.string "It's a bonsai.\n"
	.string "Its shape is exquisite.$"
	
Text_Uumegiri:
	.string "Those uumegiri look delicious!$"
	
Text_Teacup:
	.string "A cup of fragrant green tea.$"

