Text_PictureBookShelf:
	.string "There's a set of POKéMON picture books.$"

Text_BookShelf:
	.string "It's filled with all sorts of books.$"

Text_Blood:
	.string "The blood splatters on the ground, its\n"
	.string "vivid red stark against everything\l"
	.string "else.$"
 Text_M_grave:
   .string "R.I.P\p"
	.string "{COLOR BLUE}{SHADOW LIGHT_GRAY}Elysia Aurora Valente\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}There is a message left on the grave.\p"
	.string "{COLOR BLUE}{SHADOW LIGHT_GRAY}Mom, your legacy lives on through me,\n"
	.string "and every breath I take will be in\l"
	.string "pursuit of your vengeance. The {COLOR RED}{SHADOW LIGHT_GRAY}Crimson\l"
	.string "Requiem {COLOR BLUE}{SHADOW LIGHT_GRAY}has begun, and it will not end\l"
	.string "until justice is served.$"


Text_PokemonCenterBookShelf:
	.string "POKéMON magazines!\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "ADORABLE POKéMON…$"

Text_Vase:
	.string "This vase looks expensive…\n"
	.string "Peered inside…\p"
	.string "But, it was empty.$"

Text_EmptyTrashCan:
	.string "It's empty.$"

Text_ShopShelf:
	.string "The shelves brim with all sorts of\n"
	.string "POKéMON merchandise.$"

Text_Blueprint:
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"
