gText_WouldYouLikeToRestYourPkmn::
	.string "Hello, and welcome to\n"
	.string "the Pokémon CENTER.\p"
	.string "We restore your tired Pokémon\n"
	.string "to full health.\p"
	.string "Would you like to rest your Pokémon?$"

gText_IllTakeYourPkmn::
	.string "Okay, I'll take your Pokémon\n"
	.string "for a few seconds.$"

gText_RestoredPkmnToFullHealth::
	.string "Thank you for waiting.\p"
	.string "We've restored your Pokémon\n"
	.string "to full health.$"

gText_WeHopeToSeeYouAgain::
	.string "We hope to see you again!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to\n"
	.string "the Pokémon CENTER.\p"
	.string "We restore your tired Pokémon\n"
	.string "to full health.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD Card?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER Card before, but, {PLAYER},\l"
	.string "you're the first Trainer I've ever\l"
	.string "seen with a GOLD Card!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your Pokémon!$"

gText_NoticesGoldChallengeCard::
	.string "Th-those cards…\n"
	.string "Could it be… The GOLD Card?!\p"
	.string "A-and the Challenge Card too!?\p"
	.string "It's like they were meant to\n"
	.string "be together!\p"
	.string "Oh, the colors are radiant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several Challengers with\n"
	.string "a SILVER Card before, but, {PLAYER},\l"
	.string "you're the first Challenger I've ever\l"
	.string "seen with a GOLD Card!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your Pokémon!$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Allow me, {PLAYER}$"

gText_ThankYouForWaiting::
	.string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2::
	.string "We hope to see you again!$"
