gText_ImTheBattleMaster::
    .string "Greetings…\p"
    .string "I am the Battle Master.\p"
    .string "Would you like me to change\n"
    .string "your battle experience?$"

gText_AnythingElseHm::
    .string "Hm…\p"
    .string "Anything else?$"

gText_WouldYouLikeMeToDo::
    .string "What would you like me\n"
    .string "to do?$"

gText_OkItIsOn::
    .string "Ok…\p"
    .string "I have added the cap.$"

gText_OkItIsOff::
    .string "Ok…\p"
    .string "I have removed the cap.$"

gText_ExplainSoftCap::
    .string "A soft level cap…\p"
    .string "It will reduce the amount of\n"
    .string "experience your Pokémon gain\p"
    .string "as they begin to surpass the\n"
    .string "level of your next opponent…\p"
    .string "They will gain less and less\n"
    .string "experience as you further\p"
    .string "surpass your foe.$"

gText_ExplainHardCap::
    .string "A hard level cap…\p"
    .string "It will prevent your Pokémon\n"
    .string "from gaining any levels once\p"
    .string "they have reached the level of\n"
    .string "your next foe.\p"
    .string "This is a much greater challenge\n"
    .string "than a soft level cap.$"

gText_ReturnToChangeExperience::
    .string "So be it…\p"
    .string "Return to me if you wish to\n"
    .string "change your battle experience.$"

