#ifndef GUARD_CONFIG_SPECIES_FAMILIES_H
#define GUARD_CONFIG_SPECIES_FAMILIES_H

// To disable specific families, replace P_GEN_x_POKEMON with FALSE.

#define FAMILY_BULBASAUR                 P_GEN_1_POKEMON
#define FAMILY_CHARMANDER                P_GEN_1_POKEMON
#define FAMILY_SQUIRTLE                  P_GEN_1_POKEMON
#define FAMILY_CATERPIE                  P_GEN_1_POKEMON
#define FAMILY_WEEDLE                    P_GEN_1_POKEMON
#define FAMILY_PIDGEY                    P_GEN_1_POKEMON
#define FAMILY_RATTATA                   P_GEN_1_POKEMON
#define FAMILY_SPEAROW                   P_GEN_1_POKEMON
#define FAMILY_EKANS                     P_GEN_1_POKEMON
#define FAMILY_PIKACHU                   P_GEN_1_POKEMON
#define FAMILY_SANDSHREW                 P_GEN_1_POKEMON
#define FAMILY_NIDORAN                   P_GEN_1_POKEMON
#define FAMILY_CLEFAIRY                  P_GEN_1_POKEMON
#define FAMILY_VULPIX                    P_GEN_1_POKEMON
#define FAMILY_JIGGLYPUFF                P_GEN_1_POKEMON
#define FAMILY_ZUBAT                     P_GEN_1_POKEMON
#define FAMILY_ODDISH                    P_GEN_1_POKEMON
#define FAMILY_PARAS                     P_GEN_1_POKEMON
#define FAMILY_VENONAT                   P_GEN_1_POKEMON
#define FAMILY_DIGLETT                   P_GEN_1_POKEMON
#define FAMILY_MEOWTH                    P_GEN_1_POKEMON
#define FAMILY_PSYDUCK                   P_GEN_1_POKEMON
#define FAMILY_MANKEY                    P_GEN_1_POKEMON
#define FAMILY_GROWLITHE                 P_GEN_1_POKEMON
#define FAMILY_POLIWAG                   P_GEN_1_POKEMON
#define FAMILY_ABRA                      P_GEN_1_POKEMON
#define FAMILY_MACHOP                    P_GEN_1_POKEMON
#define FAMILY_BELLSPROUT                P_GEN_1_POKEMON
#define FAMILY_TENTACOOL                 P_GEN_1_POKEMON
#define FAMILY_GEODUDE                   P_GEN_1_POKEMON
#define FAMILY_PONYTA                    P_GEN_1_POKEMON
#define FAMILY_SLOWPOKE                  P_GEN_1_POKEMON
#define FAMILY_MAGNEMITE                 P_GEN_1_POKEMON
#define FAMILY_FARFETCHD                 P_GEN_1_POKEMON
#define FAMILY_DODUO                     P_GEN_1_POKEMON
#define FAMILY_SEEL                      P_GEN_1_POKEMON
#define FAMILY_GRIMER                    P_GEN_1_POKEMON
#define FAMILY_SHELLDER                  P_GEN_1_POKEMON
#define FAMILY_GASTLY                    P_GEN_1_POKEMON
#define FAMILY_ONIX                      P_GEN_1_POKEMON
#define FAMILY_DROWZEE                   P_GEN_1_POKEMON
#define FAMILY_KRABBY                    P_GEN_1_POKEMON
#define FAMILY_VOLTORB                   P_GEN_1_POKEMON
#define FAMILY_EXEGGCUTE                 P_GEN_1_POKEMON
#define FAMILY_CUBONE                    P_GEN_1_POKEMON
#define FAMILY_HITMONS                   P_GEN_1_POKEMON
#define FAMILY_LICKITUNG                 P_GEN_1_POKEMON
#define FAMILY_KOFFING                   P_GEN_1_POKEMON
#define FAMILY_RHYHORN                   P_GEN_1_POKEMON
#define FAMILY_CHANSEY                   P_GEN_1_POKEMON
#define FAMILY_TANGELA                   P_GEN_1_POKEMON
#define FAMILY_KANGASKHAN                P_GEN_1_POKEMON
#define FAMILY_HORSEA                    P_GEN_1_POKEMON
#define FAMILY_GOLDEEN                   P_GEN_1_POKEMON
#define FAMILY_STARYU                    P_GEN_1_POKEMON
#define FAMILY_MR_MIME                   P_GEN_1_POKEMON
#define FAMILY_SCYTHER                   P_GEN_1_POKEMON
#define FAMILY_JYNX                      P_GEN_1_POKEMON
#define FAMILY_ELECTABUZZ                P_GEN_1_POKEMON
#define FAMILY_MAGMAR                    P_GEN_1_POKEMON
#define FAMILY_PINSIR                    P_GEN_1_POKEMON
#define FAMILY_TAUROS                    P_GEN_1_POKEMON
#define FAMILY_MAGIKARP                  P_GEN_1_POKEMON
#define FAMILY_LAPRAS                    P_GEN_1_POKEMON
#define FAMILY_DITTO                     P_GEN_1_POKEMON
#define FAMILY_EEVEE                     P_GEN_1_POKEMON
#define FAMILY_PORYGON                   P_GEN_1_POKEMON
#define FAMILY_OMANYTE                   P_GEN_1_POKEMON
#define FAMILY_KABUTO                    P_GEN_1_POKEMON
#define FAMILY_AERODACTYL                P_GEN_1_POKEMON
#define FAMILY_SNORLAX                   P_GEN_1_POKEMON
#define FAMILY_ARTICUNO                  P_GEN_1_POKEMON
#define FAMILY_ZAPDOS                    P_GEN_1_POKEMON
#define FAMILY_MOLTRES                   P_GEN_1_POKEMON
#define FAMILY_DRATINI                   P_GEN_1_POKEMON
#define FAMILY_MEWTWO                    P_GEN_1_POKEMON
#define FAMILY_MEW                       P_GEN_1_POKEMON

#define FAMILY_CHIKORITA                 P_GEN_2_POKEMON
#define FAMILY_CYNDAQUIL                 P_GEN_2_POKEMON
#define FAMILY_TOTODILE                  P_GEN_2_POKEMON
#define FAMILY_SENTRET                   P_GEN_2_POKEMON
#define FAMILY_HOOTHOOT                  P_GEN_2_POKEMON
#define FAMILY_LEDYBA                    P_GEN_2_POKEMON
#define FAMILY_SPINARAK                  P_GEN_2_POKEMON
#define FAMILY_CHINCHOU                  P_GEN_2_POKEMON
#define FAMILY_TOGEPI                    P_GEN_2_POKEMON
#define FAMILY_NATU                      P_GEN_2_POKEMON
#define FAMILY_MAREEP                    P_GEN_2_POKEMON
#define FAMILY_MARILL                    P_GEN_2_POKEMON
#define FAMILY_SUDOWOODO                 P_GEN_2_POKEMON
#define FAMILY_HOPPIP                    P_GEN_2_POKEMON
#define FAMILY_AIPOM                     P_GEN_2_POKEMON
#define FAMILY_SUNKERN                   P_GEN_2_POKEMON
#define FAMILY_YANMA                     P_GEN_2_POKEMON
#define FAMILY_WOOPER                    P_GEN_2_POKEMON
#define FAMILY_MURKROW                   P_GEN_2_POKEMON
#define FAMILY_MISDREAVUS                P_GEN_2_POKEMON
#define FAMILY_UNOWN                     P_GEN_2_POKEMON
#define FAMILY_WOBBUFFET                 P_GEN_2_POKEMON
#define FAMILY_GIRAFARIG                 P_GEN_2_POKEMON
#define FAMILY_PINECO                    P_GEN_2_POKEMON
#define FAMILY_DUNSPARCE                 P_GEN_2_POKEMON
#define FAMILY_GLIGAR                    P_GEN_2_POKEMON
#define FAMILY_SNUBBULL                  P_GEN_2_POKEMON
#define FAMILY_QWILFISH                  P_GEN_2_POKEMON
#define FAMILY_SHUCKLE                   P_GEN_2_POKEMON
#define FAMILY_HERACROSS                 P_GEN_2_POKEMON
#define FAMILY_SNEASEL                   P_GEN_2_POKEMON
#define FAMILY_TEDDIURSA                 P_GEN_2_POKEMON
#define FAMILY_SLUGMA                    P_GEN_2_POKEMON
#define FAMILY_SWINUB                    P_GEN_2_POKEMON
#define FAMILY_CORSOLA                   P_GEN_2_POKEMON
#define FAMILY_REMORAID                  P_GEN_2_POKEMON
#define FAMILY_DELIBIRD                  P_GEN_2_POKEMON
#define FAMILY_MANTINE                   P_GEN_2_POKEMON
#define FAMILY_SKARMORY                  P_GEN_2_POKEMON
#define FAMILY_HOUNDOUR                  P_GEN_2_POKEMON
#define FAMILY_PHANPY                    P_GEN_2_POKEMON
#define FAMILY_STANTLER                  P_GEN_2_POKEMON
#define FAMILY_SMEARGLE                  P_GEN_2_POKEMON
#define FAMILY_MILTANK                   P_GEN_2_POKEMON
#define FAMILY_RAIKOU                    P_GEN_2_POKEMON
#define FAMILY_ENTEI                     P_GEN_2_POKEMON
#define FAMILY_SUICUNE                   P_GEN_2_POKEMON
#define FAMILY_LARVITAR                  P_GEN_2_POKEMON
#define FAMILY_LUGIA                     P_GEN_2_POKEMON
#define FAMILY_HO_OH                     P_GEN_2_POKEMON
#define FAMILY_CELEBI                    P_GEN_2_POKEMON

#endif // GUARD_CONFIG_SPECIES_FAMILIES_H
