#ifndef GUARD_CONFIG_SPECIES_FAMILIES_H
#define GUARD_CONFIG_SPECIES_FAMILIES_H

// To disable specific families, replace P_GEN_x_POKEMON with FALSE.

#define FAMILY_BULBASAUR                 P_GEN_1_POKEMON
#define FAMILY_CHARMANDER                P_GEN_1_POKEMON
#define FAMILY_SQUIRTLE                  P_GEN_1_POKEMON
#define FAMILY_CATERPIE                  P_GEN_1_POKEMON
#define FAMILY_WEEDLE                    P_GEN_1_POKEMON
#define FAMILY_PIDGEY                    P_GEN_1_POKEMON
#define FAMILY_RATTATA                   P_GEN_1_POKEMON
#define FAMILY_SPEAROW                   P_GEN_1_POKEMON
#define FAMILY_EKANS                     P_GEN_1_POKEMON
#define FAMILY_PIKACHU                   P_GEN_1_POKEMON
#define FAMILY_SANDSHREW                 P_GEN_1_POKEMON
#define FAMILY_NIDORAN                   P_GEN_1_POKEMON
#define FAMILY_CLEFAIRY                  P_GEN_1_POKEMON
#define FAMILY_VULPIX                    P_GEN_1_POKEMON
#define FAMILY_JIGGLYPUFF                P_GEN_1_POKEMON
#define FAMILY_ZUBAT                     P_GEN_1_POKEMON
#define FAMILY_ODDISH                    P_GEN_1_POKEMON
#define FAMILY_PARAS                     P_GEN_1_POKEMON
#define FAMILY_VENONAT                   P_GEN_1_POKEMON
#define FAMILY_DIGLETT                   P_GEN_1_POKEMON
#define FAMILY_MEOWTH                    P_GEN_1_POKEMON
#define FAMILY_PSYDUCK                   P_GEN_1_POKEMON
#define FAMILY_MANKEY                    P_GEN_1_POKEMON
#define FAMILY_GROWLITHE                 P_GEN_1_POKEMON
#define FAMILY_POLIWAG                   P_GEN_1_POKEMON
#define FAMILY_ABRA                      P_GEN_1_POKEMON
#define FAMILY_MACHOP                    P_GEN_1_POKEMON
#define FAMILY_BELLSPROUT                P_GEN_1_POKEMON
#define FAMILY_TENTACOOL                 P_GEN_1_POKEMON
#define FAMILY_GEODUDE                   P_GEN_1_POKEMON
#define FAMILY_PONYTA                    P_GEN_1_POKEMON
#define FAMILY_SLOWPOKE                  P_GEN_1_POKEMON
#define FAMILY_MAGNEMITE                 P_GEN_1_POKEMON
#define FAMILY_FARFETCHD                 P_GEN_1_POKEMON
#define FAMILY_DODUO                     P_GEN_1_POKEMON
#define FAMILY_SEEL                      P_GEN_1_POKEMON
#define FAMILY_GRIMER                    P_GEN_1_POKEMON
#define FAMILY_SHELLDER                  P_GEN_1_POKEMON
#define FAMILY_GASTLY                    P_GEN_1_POKEMON
#define FAMILY_ONIX                      P_GEN_1_POKEMON
#define FAMILY_DROWZEE                   P_GEN_1_POKEMON
#define FAMILY_KRABBY                    P_GEN_1_POKEMON
#define FAMILY_VOLTORB                   P_GEN_1_POKEMON
#define FAMILY_EXEGGCUTE                 P_GEN_1_POKEMON
#define FAMILY_CUBONE                    P_GEN_1_POKEMON
#define FAMILY_HITMONS                   P_GEN_1_POKEMON
#define FAMILY_LICKITUNG                 P_GEN_1_POKEMON
#define FAMILY_KOFFING                   P_GEN_1_POKEMON
#define FAMILY_RHYHORN                   P_GEN_1_POKEMON
#define FAMILY_CHANSEY                   P_GEN_1_POKEMON
#define FAMILY_TANGELA                   P_GEN_1_POKEMON
#define FAMILY_KANGASKHAN                P_GEN_1_POKEMON
#define FAMILY_HORSEA                    P_GEN_1_POKEMON
#define FAMILY_GOLDEEN                   P_GEN_1_POKEMON
#define FAMILY_STARYU                    P_GEN_1_POKEMON
#define FAMILY_MR_MIME                   P_GEN_1_POKEMON
#define FAMILY_SCYTHER                   P_GEN_1_POKEMON
#define FAMILY_JYNX                      P_GEN_1_POKEMON
#define FAMILY_ELECTABUZZ                P_GEN_1_POKEMON
#define FAMILY_MAGMAR                    P_GEN_1_POKEMON
#define FAMILY_PINSIR                    P_GEN_1_POKEMON
#define FAMILY_TAUROS                    P_GEN_1_POKEMON
#define FAMILY_MAGIKARP                  P_GEN_1_POKEMON
#define FAMILY_LAPRAS                    P_GEN_1_POKEMON
#define FAMILY_DITTO                     P_GEN_1_POKEMON
#define FAMILY_EEVEE                     P_GEN_1_POKEMON
#define FAMILY_PORYGON                   P_GEN_1_POKEMON
#define FAMILY_OMANYTE                   P_GEN_1_POKEMON
#define FAMILY_KABUTO                    P_GEN_1_POKEMON
#define FAMILY_AERODACTYL                P_GEN_1_POKEMON
#define FAMILY_SNORLAX                   P_GEN_1_POKEMON
#define FAMILY_ARTICUNO                  P_GEN_1_POKEMON
#define FAMILY_ZAPDOS                    P_GEN_1_POKEMON
#define FAMILY_MOLTRES                   P_GEN_1_POKEMON
#define FAMILY_DRATINI                   P_GEN_1_POKEMON
#define FAMILY_MEWTWO                    P_GEN_1_POKEMON
#define FAMILY_MEW                       P_GEN_1_POKEMON

#define FAMILY_CHIKORITA                 P_GEN_2_POKEMON
#define FAMILY_CYNDAQUIL                 P_GEN_2_POKEMON
#define FAMILY_TOTODILE                  P_GEN_2_POKEMON
#define FAMILY_SENTRET                   P_GEN_2_POKEMON
#define FAMILY_HOOTHOOT                  P_GEN_2_POKEMON
#define FAMILY_LEDYBA                    P_GEN_2_POKEMON
#define FAMILY_SPINARAK                  P_GEN_2_POKEMON
#define FAMILY_CHINCHOU                  P_GEN_2_POKEMON
#define FAMILY_TOGEPI                    P_GEN_2_POKEMON
#define FAMILY_NATU                      P_GEN_2_POKEMON
#define FAMILY_MAREEP                    P_GEN_2_POKEMON
#define FAMILY_MARILL                    P_GEN_2_POKEMON
#define FAMILY_SUDOWOODO                 P_GEN_2_POKEMON
#define FAMILY_HOPPIP                    P_GEN_2_POKEMON
#define FAMILY_AIPOM                     P_GEN_2_POKEMON
#define FAMILY_SUNKERN                   P_GEN_2_POKEMON
#define FAMILY_YANMA                     P_GEN_2_POKEMON
#define FAMILY_WOOPER                    P_GEN_2_POKEMON
#define FAMILY_MURKROW                   P_GEN_2_POKEMON
#define FAMILY_MISDREAVUS                P_GEN_2_POKEMON
#define FAMILY_UNOWN                     P_GEN_2_POKEMON
#define FAMILY_WOBBUFFET                 P_GEN_2_POKEMON
#define FAMILY_GIRAFARIG                 P_GEN_2_POKEMON
#define FAMILY_PINECO                    P_GEN_2_POKEMON
#define FAMILY_DUNSPARCE                 P_GEN_2_POKEMON
#define FAMILY_GLIGAR                    P_GEN_2_POKEMON
#define FAMILY_SNUBBULL                  P_GEN_2_POKEMON
#define FAMILY_QWILFISH                  P_GEN_2_POKEMON
#define FAMILY_SHUCKLE                   P_GEN_2_POKEMON
#define FAMILY_HERACROSS                 P_GEN_2_POKEMON
#define FAMILY_SNEASEL                   P_GEN_2_POKEMON
#define FAMILY_TEDDIURSA                 P_GEN_2_POKEMON
#define FAMILY_SLUGMA                    P_GEN_2_POKEMON
#define FAMILY_SWINUB                    P_GEN_2_POKEMON
#define FAMILY_CORSOLA                   P_GEN_2_POKEMON
#define FAMILY_REMORAID                  P_GEN_2_POKEMON
#define FAMILY_DELIBIRD                  P_GEN_2_POKEMON
#define FAMILY_MANTINE                   P_GEN_2_POKEMON
#define FAMILY_SKARMORY                  P_GEN_2_POKEMON
#define FAMILY_HOUNDOUR                  P_GEN_2_POKEMON
#define FAMILY_PHANPY                    P_GEN_2_POKEMON
#define FAMILY_STANTLER                  P_GEN_2_POKEMON
#define FAMILY_SMEARGLE                  P_GEN_2_POKEMON
#define FAMILY_MILTANK                   P_GEN_2_POKEMON
#define FAMILY_RAIKOU                    P_GEN_2_POKEMON
#define FAMILY_ENTEI                     P_GEN_2_POKEMON
#define FAMILY_SUICUNE                   P_GEN_2_POKEMON
#define FAMILY_LARVITAR                  P_GEN_2_POKEMON
#define FAMILY_LUGIA                     P_GEN_2_POKEMON
#define FAMILY_HO_OH                     P_GEN_2_POKEMON
#define FAMILY_CELEBI                    P_GEN_2_POKEMON

#define FAMILY_TREECKO                   P_GEN_3_POKEMON
#define FAMILY_TORCHIC                   P_GEN_3_POKEMON
#define FAMILY_MUDKIP                    P_GEN_3_POKEMON
#define FAMILY_POOCHYENA                 P_GEN_3_POKEMON
#define FAMILY_ZIGZAGOON                 P_GEN_3_POKEMON
#define FAMILY_WURMPLE                   P_GEN_3_POKEMON
#define FAMILY_LOTAD                     P_GEN_3_POKEMON
#define FAMILY_SEEDOT                    P_GEN_3_POKEMON
#define FAMILY_TAILLOW                   P_GEN_3_POKEMON
#define FAMILY_WINGULL                   P_GEN_3_POKEMON
#define FAMILY_RALTS                     P_GEN_3_POKEMON
#define FAMILY_SURSKIT                   P_GEN_3_POKEMON
#define FAMILY_SHROOMISH                 P_GEN_3_POKEMON
#define FAMILY_SLAKOTH                   P_GEN_3_POKEMON
#define FAMILY_NINCADA                   P_GEN_3_POKEMON
#define FAMILY_WHISMUR                   P_GEN_3_POKEMON
#define FAMILY_MAKUHITA                  P_GEN_3_POKEMON
#define FAMILY_NOSEPASS                  P_GEN_3_POKEMON
#define FAMILY_SKITTY                    P_GEN_3_POKEMON
#define FAMILY_SABLEYE                   P_GEN_3_POKEMON
#define FAMILY_MAWILE                    P_GEN_3_POKEMON
#define FAMILY_ARON                      P_GEN_3_POKEMON
#define FAMILY_MEDITITE                  P_GEN_3_POKEMON
#define FAMILY_ELECTRIKE                 P_GEN_3_POKEMON
#define FAMILY_PLUSLE                    P_GEN_3_POKEMON
#define FAMILY_MINUN                     P_GEN_3_POKEMON
#define FAMILY_VOLBEAT_ILLUMISE          P_GEN_3_POKEMON
#define FAMILY_ROSELIA                   P_GEN_3_POKEMON
#define FAMILY_GULPIN                    P_GEN_3_POKEMON
#define FAMILY_CARVANHA                  P_GEN_3_POKEMON
#define FAMILY_WAILMER                   P_GEN_3_POKEMON
#define FAMILY_NUMEL                     P_GEN_3_POKEMON
#define FAMILY_TORKOAL                   P_GEN_3_POKEMON
#define FAMILY_SPOINK                    P_GEN_3_POKEMON
#define FAMILY_SPINDA                    P_GEN_3_POKEMON
#define FAMILY_TRAPINCH                  P_GEN_3_POKEMON
#define FAMILY_CACNEA                    P_GEN_3_POKEMON
#define FAMILY_SWABLU                    P_GEN_3_POKEMON
#define FAMILY_ZANGOOSE                  P_GEN_3_POKEMON
#define FAMILY_SEVIPER                   P_GEN_3_POKEMON
#define FAMILY_LUNATONE                  P_GEN_3_POKEMON
#define FAMILY_SOLROCK                   P_GEN_3_POKEMON
#define FAMILY_BARBOACH                  P_GEN_3_POKEMON
#define FAMILY_CORPHISH                  P_GEN_3_POKEMON
#define FAMILY_BALTOY                    P_GEN_3_POKEMON
#define FAMILY_LILEEP                    P_GEN_3_POKEMON
#define FAMILY_ANORITH                   P_GEN_3_POKEMON
#define FAMILY_FEEBAS                    P_GEN_3_POKEMON
#define FAMILY_CASTFORM                  P_GEN_3_POKEMON
#define FAMILY_KECLEON                   P_GEN_3_POKEMON
#define FAMILY_SHUPPET                   P_GEN_3_POKEMON
#define FAMILY_DUSKULL                   P_GEN_3_POKEMON
#define FAMILY_TROPIUS                   P_GEN_3_POKEMON
#define FAMILY_CHIMECHO                  P_GEN_3_POKEMON
#define FAMILY_ABSOL                     P_GEN_3_POKEMON
#define FAMILY_SNORUNT                   P_GEN_3_POKEMON
#define FAMILY_SPHEAL                    P_GEN_3_POKEMON
#define FAMILY_CLAMPERL                  P_GEN_3_POKEMON
#define FAMILY_RELICANTH                 P_GEN_3_POKEMON
#define FAMILY_LUVDISC                   P_GEN_3_POKEMON
#define FAMILY_BAGON                     P_GEN_3_POKEMON
#define FAMILY_BELDUM                    P_GEN_3_POKEMON
#define FAMILY_REGIROCK                  P_GEN_3_POKEMON
#define FAMILY_REGICE                    P_GEN_3_POKEMON
#define FAMILY_REGISTEEL                 P_GEN_3_POKEMON
#define FAMILY_LATIAS                    P_GEN_3_POKEMON
#define FAMILY_LATIOS                    P_GEN_3_POKEMON
#define FAMILY_KYOGRE                    P_GEN_3_POKEMON
#define FAMILY_GROUDON                   P_GEN_3_POKEMON
#define FAMILY_RAYQUAZA                  P_GEN_3_POKEMON
#define FAMILY_JIRACHI                   P_GEN_3_POKEMON
#define FAMILY_DEOXYS                    P_GEN_3_POKEMON

#define FAMILY_TURTWIG                   P_GEN_4_POKEMON
#define FAMILY_CHIMCHAR                  P_GEN_4_POKEMON
#define FAMILY_PIPLUP                    P_GEN_4_POKEMON
#define FAMILY_STARLY                    P_GEN_4_POKEMON
#define FAMILY_BIDOOF                    P_GEN_4_POKEMON
#define FAMILY_KRICKETOT                 P_GEN_4_POKEMON
#define FAMILY_SHINX                     P_GEN_4_POKEMON
#define FAMILY_CRANIDOS                  P_GEN_4_POKEMON
#define FAMILY_SHIELDON                  P_GEN_4_POKEMON
#define FAMILY_BURMY                     P_GEN_4_POKEMON
#define FAMILY_COMBEE                    P_GEN_4_POKEMON
#define FAMILY_PACHIRISU                 P_GEN_4_POKEMON
#define FAMILY_BUIZEL                    P_GEN_4_POKEMON
#define FAMILY_CHERUBI                   P_GEN_4_POKEMON
#define FAMILY_SHELLOS                   P_GEN_4_POKEMON
#define FAMILY_DRIFLOON                  P_GEN_4_POKEMON
#define FAMILY_BUNEARY                   P_GEN_4_POKEMON
#define FAMILY_GLAMEOW                   P_GEN_4_POKEMON
#define FAMILY_STUNKY                    P_GEN_4_POKEMON
#define FAMILY_BRONZOR                   P_GEN_4_POKEMON
#define FAMILY_CHATOT                    P_GEN_4_POKEMON
#define FAMILY_SPIRITOMB                 P_GEN_4_POKEMON
#define FAMILY_GIBLE                     P_GEN_4_POKEMON
#define FAMILY_RIOLU                     P_GEN_4_POKEMON
#define FAMILY_HIPPOPOTAS                P_GEN_4_POKEMON
#define FAMILY_SKORUPI                   P_GEN_4_POKEMON
#define FAMILY_CROAGUNK                  P_GEN_4_POKEMON
#define FAMILY_CARNIVINE                 P_GEN_4_POKEMON
#define FAMILY_FINNEON                   P_GEN_4_POKEMON
#define FAMILY_SNOVER                    P_GEN_4_POKEMON
#define FAMILY_ROTOM                     P_GEN_4_POKEMON
#define FAMILY_UXIE                      P_GEN_4_POKEMON
#define FAMILY_MESPRIT                   P_GEN_4_POKEMON
#define FAMILY_AZELF                     P_GEN_4_POKEMON
#define FAMILY_DIALGA                    P_GEN_4_POKEMON
#define FAMILY_PALKIA                    P_GEN_4_POKEMON
#define FAMILY_HEATRAN                   P_GEN_4_POKEMON
#define FAMILY_REGIGIGAS                 P_GEN_4_POKEMON
#define FAMILY_GIRATINA                  P_GEN_4_POKEMON
#define FAMILY_CRESSELIA                 P_GEN_4_POKEMON
#define FAMILY_MANAPHY                   P_GEN_4_POKEMON
#define FAMILY_DARKRAI                   P_GEN_4_POKEMON
#define FAMILY_SHAYMIN                   P_GEN_4_POKEMON
#define FAMILY_ARCEUS                    P_GEN_4_POKEMON

#endif // GUARD_CONFIG_SPECIES_FAMILIES_H
