SakuTown_House1_MapScripts::
	.byte 0


SakuTown_House1_EventScript_Tama::
# 7 "data/maps/SakuTown_House1/scripts.pory"
	lock
# 8 "data/maps/SakuTown_House1/scripts.pory"
	msgbox SakuTown_House1_EventScript_Tama_Text_0
# 9 "data/maps/SakuTown_House1/scripts.pory"
	closemessage
# 10 "data/maps/SakuTown_House1/scripts.pory"
	release
	return


SakuTown_House1_EventScript_Tama_Text_0:
# 8 "data/maps/SakuTown_House1/scripts.pory"
	.string "Please go away. Leave me alone.$"
