# 3 "data/scripts/movement.pory"
Common_Movement_FollowerSafeStart::
	step_end

# 4 "data/scripts/movement.pory"
Common_Movement_QuestionMark:
# 5 "data/scripts/movement.pory"
	emote_question_mark
	step_end

# 8 "data/scripts/movement.pory"
Common_Movement_ExclamationMark:
# 9 "data/scripts/movement.pory"
	emote_exclamation_mark
	step_end

# 12 "data/scripts/movement.pory"
Common_Movement_Delay48:
# 13 "data/scripts/movement.pory"
	delay_16
# 13 "data/scripts/movement.pory"
	delay_16
# 13 "data/scripts/movement.pory"
	delay_16
	step_end

# 16 "data/scripts/movement.pory"
Common_Movement_FacePlayer:
# 17 "data/scripts/movement.pory"
	face_player
	step_end

# 20 "data/scripts/movement.pory"
Common_Movement_FaceAwayPlayer:
# 21 "data/scripts/movement.pory"
	face_away_player
	step_end

# 24 "data/scripts/movement.pory"
Common_Movement_FaceOriginalDirection:
# 25 "data/scripts/movement.pory"
	face_original_direction
	step_end

# 28 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFasterLeft:
# 29 "data/scripts/movement.pory"
	walk_in_place_faster_left
	step_end

# 32 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFasterUp:
# 33 "data/scripts/movement.pory"
	walk_in_place_faster_up
	step_end

# 36 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFasterRight:
# 37 "data/scripts/movement.pory"
	walk_in_place_faster_right
	step_end

# 40 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFasterDown:
# 41 "data/scripts/movement.pory"
	walk_in_place_faster_down
	step_end

# 44 "data/scripts/movement.pory"
Common_Movement_FaceRight:
# 45 "data/scripts/movement.pory"
	face_right
	step_end

# 48 "data/scripts/movement.pory"
Common_Movement_FaceLeft:
# 49 "data/scripts/movement.pory"
	face_left
	step_end

# 52 "data/scripts/movement.pory"
Common_Movement_FaceDown:
# 53 "data/scripts/movement.pory"
	face_down
	step_end

# 56 "data/scripts/movement.pory"
Common_Movement_FaceUp:
# 57 "data/scripts/movement.pory"
	face_up
	step_end

# 60 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceDown:
# 61 "data/scripts/movement.pory"
	walk_in_place_down
	step_end

# 64 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceLeft:
# 65 "data/scripts/movement.pory"
	walk_in_place_left
	step_end

# 68 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceRight:
# 69 "data/scripts/movement.pory"
	walk_in_place_right
	step_end

# 73 "data/scripts/movement.pory"
Common_Movement_FollowerSafeEnd::
	step_end

# 75 "data/scripts/movement.pory"
Common_Movement_WalkUp6:
# 76 "data/scripts/movement.pory"
	walk_up
# 76 "data/scripts/movement.pory"
	walk_up
# 76 "data/scripts/movement.pory"
	walk_up
# 76 "data/scripts/movement.pory"
	walk_up
# 76 "data/scripts/movement.pory"
	walk_up
# 76 "data/scripts/movement.pory"
	walk_up
	step_end

# 79 "data/scripts/movement.pory"
Common_Movement_WalkUp4:
# 80 "data/scripts/movement.pory"
	walk_up
# 80 "data/scripts/movement.pory"
	walk_up
# 80 "data/scripts/movement.pory"
	walk_up
# 80 "data/scripts/movement.pory"
	walk_up
	step_end

# 83 "data/scripts/movement.pory"
Common_Movement_Delay32:
# 84 "data/scripts/movement.pory"
	delay_16
# 84 "data/scripts/movement.pory"
	delay_16
	step_end

# 87 "data/scripts/movement.pory"
Common_Movement_WalkUp:
# 88 "data/scripts/movement.pory"
	walk_up
	step_end

# 92 "data/scripts/movement.pory"
Common_Movement_WalkUp2:
# 93 "data/scripts/movement.pory"
	walk_up
# 93 "data/scripts/movement.pory"
	walk_up
	step_end

# 96 "data/scripts/movement.pory"
Common_Movement_TeleportAway:
# 97 "data/scripts/movement.pory"
	face_up
# 98 "data/scripts/movement.pory"
	delay_4
# 99 "data/scripts/movement.pory"
	face_left
# 100 "data/scripts/movement.pory"
	delay_4
# 101 "data/scripts/movement.pory"
	face_down
# 102 "data/scripts/movement.pory"
	delay_4
# 103 "data/scripts/movement.pory"
	face_right
# 104 "data/scripts/movement.pory"
	delay_4
# 105 "data/scripts/movement.pory"
	face_up
# 106 "data/scripts/movement.pory"
	disable_anim
# 107 "data/scripts/movement.pory"
	slide_up
# 108 "data/scripts/movement.pory"
	slide_up
# 109 "data/scripts/movement.pory"
	slide_up
# 110 "data/scripts/movement.pory"
	slide_up
# 111 "data/scripts/movement.pory"
	slide_up
# 112 "data/scripts/movement.pory"
	slide_up
	step_end
