#ifndef GUARD_CONFIG_TEST_SPECIES_ENABLED_H
#define GUARD_CONFIG_TEST_SPECIES_ENABLED_H

#define P_GEN_1_POKEMON                  FALSE // Generation 1 Pokémon (RGBY)
#define P_GEN_2_POKEMON                  FALSE // Generation 2 Pokémon (GSC)
#define P_GEN_3_POKEMON                  FALSE // Generation 3 Pokémon (RSE, FRLG)
#define P_GEN_4_POKEMON                  FALSE // Generation 4 Pokémon (DPPt, HGSS)
#define P_GEN_5_POKEMON                  FALSE // Generation 5 Pokémon (BW, B2W2)
#define P_GEN_6_POKEMON                  FALSE // Generation 6 Pokémon (XY, ORAS)
#define P_GEN_7_POKEMON                  FALSE // Generation 7 Pokémon (SM, USUM, LGPE)
#define P_GEN_8_POKEMON                  FALSE // Generation 8 Pokémon (SwSh, BDSP, LA)
#define P_GEN_9_POKEMON                  FALSE // Generation 9 Pokémon (SV)

// Setting this to TRUE will add the new evolutions to the Regional Dex.
#define P_NEW_EVOS_IN_REGIONAL_DEX       TRUE

// Battle gimmick specific Forms.
#define P_MEGA_EVOLUTIONS                TRUE
#define P_PRIMAL_REVERSIONS              TRUE // Groudon and Kyogre only.
#define P_ULTRA_BURST_FORMS              TRUE // Ultra Necrozma only.
#define P_GIGANTAMAX_FORMS               TRUE
#define P_TERA_FORMS                     TRUE

// Fusion forms
#define P_FUSION_FORMS                   TRUE

// Regional Forms. Includes Regional Form evolutions, like Sirfetch'd.
#define P_REGIONAL_FORMS                 TRUE
#define P_ALOLAN_FORMS                   P_REGIONAL_FORMS
#define P_GALARIAN_FORMS                 P_REGIONAL_FORMS
#define P_HISUIAN_FORMS                  P_REGIONAL_FORMS
#define P_PALDEAN_FORMS                  P_REGIONAL_FORMS

// Big groups of forms that aren't always desired when choosing families.
#define P_PIKACHU_EXTRA_FORMS            FALSE
#define P_COSPLAY_PIKACHU_FORMS          P_PIKACHU_EXTRA_FORMS
#define P_CAP_PIKACHU_FORMS              TRUE

// Cross-generation evolutions. Includes pre-evolutions.
#define P_CROSS_GENERATION_EVOS          TRUE
#define P_GEN_2_CROSS_EVOS               P_CROSS_GENERATION_EVOS
#define P_GEN_3_CROSS_EVOS               P_CROSS_GENERATION_EVOS
#define P_GEN_4_CROSS_EVOS               P_CROSS_GENERATION_EVOS
//#define P_GEN_5_CROSS_EVOS             // Gen 5 didn't introduce any cross-gen evos.
#define P_GEN_6_CROSS_EVOS               P_CROSS_GENERATION_EVOS // Just Sylveon.
//#define P_GEN_7_CROSS_EVOS             // Alolan evolutions handled by P_ALOLAN_FORMS.
#define P_GEN_8_CROSS_EVOS               P_CROSS_GENERATION_EVOS // Regional evolutions handled by P_GALARIAN_FORMS and P_HISUIAN_FORMS.
#define P_GEN_9_CROSS_EVOS               P_CROSS_GENERATION_EVOS // Clodsire handled by P_PALDEAN_FORMS.

// To disable specific families, replace P_GEN_x_POKEMON with FALSE.
#define P_FAMILY_BULBASAUR               TRUE
#define P_FAMILY_CHARMANDER              TRUE
#define P_FAMILY_SQUIRTLE                TRUE
#define P_FAMILY_CATERPIE                TRUE
#define P_FAMILY_WEEDLE                  TRUE
#define P_FAMILY_PIDGEY                  TRUE
#define P_FAMILY_RATTATA                 TRUE
#define P_FAMILY_SPEAROW                 P_GEN_1_POKEMON
#define P_FAMILY_EKANS                   TRUE
#define P_FAMILY_PIKACHU                 TRUE
#define P_FAMILY_SANDSHREW               TRUE
#define P_FAMILY_NIDORAN                 TRUE
#define P_FAMILY_CLEFAIRY                TRUE
#define P_FAMILY_VULPIX                  TRUE
#define P_FAMILY_JIGGLYPUFF              TRUE
#define P_FAMILY_ZUBAT                   TRUE
#define P_FAMILY_ODDISH                  TRUE
#define P_FAMILY_PARAS                   TRUE
#define P_FAMILY_VENONAT                 P_GEN_1_POKEMON
#define P_FAMILY_DIGLETT                 TRUE
#define P_FAMILY_MEOWTH                  TRUE
#define P_FAMILY_PSYDUCK                 TRUE
#define P_FAMILY_MANKEY                  TRUE
#define P_FAMILY_GROWLITHE               TRUE
#define P_FAMILY_POLIWAG                 TRUE
#define P_FAMILY_ABRA                    TRUE
#define P_FAMILY_MACHOP                  TRUE
#define P_FAMILY_BELLSPROUT              TRUE
#define P_FAMILY_TENTACOOL               P_GEN_1_POKEMON
#define P_FAMILY_GEODUDE                 TRUE
#define P_FAMILY_PONYTA                  TRUE
#define P_FAMILY_SLOWPOKE                TRUE
#define P_FAMILY_MAGNEMITE               TRUE
#define P_FAMILY_FARFETCHD               TRUE
#define P_FAMILY_DODUO                   P_GEN_1_POKEMON
#define P_FAMILY_SEEL                    P_GEN_1_POKEMON
#define P_FAMILY_GRIMER                  TRUE
#define P_FAMILY_SHELLDER                TRUE
#define P_FAMILY_GASTLY                  TRUE
#define P_FAMILY_ONIX                    TRUE
#define P_FAMILY_DROWZEE                 TRUE
#define P_FAMILY_KRABBY                  TRUE
#define P_FAMILY_VOLTORB                 TRUE
#define P_FAMILY_EXEGGCUTE               P_GEN_1_POKEMON
#define P_FAMILY_CUBONE                  P_GEN_1_POKEMON
#define P_FAMILY_HITMONS                 TRUE
#define P_FAMILY_LICKITUNG               P_GEN_1_POKEMON
#define P_FAMILY_KOFFING                 TRUE
#define P_FAMILY_RHYHORN                 TRUE
#define P_FAMILY_CHANSEY                 TRUE
#define P_FAMILY_TANGELA                 TRUE
#define P_FAMILY_KANGASKHAN              TRUE
#define P_FAMILY_HORSEA                  P_GEN_1_POKEMON
#define P_FAMILY_GOLDEEN                 TRUE
#define P_FAMILY_STARYU                  TRUE
#define P_FAMILY_MR_MIME                 TRUE
#define P_FAMILY_SCYTHER                 TRUE
#define P_FAMILY_JYNX                    P_GEN_1_POKEMON
#define P_FAMILY_ELECTABUZZ              TRUE
#define P_FAMILY_MAGMAR                  TRUE
#define P_FAMILY_PINSIR                  TRUE
#define P_FAMILY_TAUROS                  TRUE
#define P_FAMILY_MAGIKARP                TRUE
#define P_FAMILY_LAPRAS                  TRUE
#define P_FAMILY_DITTO                   TRUE
#define P_FAMILY_EEVEE                   TRUE
#define P_FAMILY_PORYGON                 TRUE
#define P_FAMILY_OMANYTE                 TRUE
#define P_FAMILY_KABUTO                  P_GEN_1_POKEMON
#define P_FAMILY_AERODACTYL              P_GEN_1_POKEMON
#define P_FAMILY_SNORLAX                 TRUE
#define P_FAMILY_ARTICUNO                TRUE
#define P_FAMILY_ZAPDOS                  TRUE
#define P_FAMILY_MOLTRES                 TRUE
#define P_FAMILY_DRATINI                 TRUE
#define P_FAMILY_MEWTWO                  P_GEN_1_POKEMON
#define P_FAMILY_MEW                     TRUE

#define P_FAMILY_CHIKORITA               TRUE
#define P_FAMILY_CYNDAQUIL               TRUE
#define P_FAMILY_TOTODILE                TRUE
#define P_FAMILY_SENTRET                 TRUE
#define P_FAMILY_HOOTHOOT                TRUE
#define P_FAMILY_LEDYBA                  TRUE
#define P_FAMILY_SPINARAK                P_GEN_2_POKEMON
#define P_FAMILY_CHINCHOU                TRUE
#define P_FAMILY_TOGEPI                  TRUE
#define P_FAMILY_NATU                    TRUE
#define P_FAMILY_MAREEP                  P_GEN_2_POKEMON
#define P_FAMILY_MARILL                  TRUE
#define P_FAMILY_SUDOWOODO               TRUE
#define P_FAMILY_HOPPIP                  P_GEN_2_POKEMON
#define P_FAMILY_AIPOM                   P_GEN_2_POKEMON
#define P_FAMILY_SUNKERN                 P_GEN_2_POKEMON
#define P_FAMILY_YANMA                   P_GEN_2_POKEMON
#define P_FAMILY_WOOPER                  P_GEN_2_POKEMON
#define P_FAMILY_MURKROW                 TRUE
#define P_FAMILY_MISDREAVUS              TRUE
#define P_FAMILY_UNOWN                   TRUE
#define P_FAMILY_WOBBUFFET               TRUE
#define P_FAMILY_GIRAFARIG               TRUE
#define P_FAMILY_PINECO                  TRUE
#define P_FAMILY_DUNSPARCE               TRUE
#define P_FAMILY_GLIGAR                  TRUE
#define P_FAMILY_SNUBBULL                P_GEN_2_POKEMON
#define P_FAMILY_QWILFISH                P_GEN_2_POKEMON
#define P_FAMILY_SHUCKLE                 TRUE
#define P_FAMILY_HERACROSS               P_GEN_2_POKEMON
#define P_FAMILY_SNEASEL                 TRUE
#define P_FAMILY_TEDDIURSA               TRUE
#define P_FAMILY_SLUGMA                  TRUE
#define P_FAMILY_SWINUB                  P_GEN_2_POKEMON
#define P_FAMILY_CORSOLA                 P_GEN_2_POKEMON
#define P_FAMILY_REMORAID                TRUE
#define P_FAMILY_DELIBIRD                P_GEN_2_POKEMON
#define P_FAMILY_MANTINE                 P_GEN_2_POKEMON
#define P_FAMILY_SKARMORY                TRUE
#define P_FAMILY_HOUNDOUR                TRUE
#define P_FAMILY_PHANPY                  TRUE
#define P_FAMILY_STANTLER                P_GEN_2_POKEMON
#define P_FAMILY_SMEARGLE                P_GEN_2_POKEMON
#define P_FAMILY_MILTANK                 TRUE
#define P_FAMILY_RAIKOU                  P_GEN_2_POKEMON
#define P_FAMILY_ENTEI                   P_GEN_2_POKEMON
#define P_FAMILY_SUICUNE                 P_GEN_2_POKEMON
#define P_FAMILY_LARVITAR                TRUE
#define P_FAMILY_LUGIA                   P_GEN_2_POKEMON
#define P_FAMILY_HO_OH                   P_GEN_2_POKEMON
#define P_FAMILY_CELEBI                  P_GEN_2_POKEMON

#define P_FAMILY_TREECKO                 TRUE
#define P_FAMILY_TORCHIC                 TRUE
#define P_FAMILY_MUDKIP                  TRUE
#define P_FAMILY_POOCHYENA               TRUE
#define P_FAMILY_ZIGZAGOON               TRUE
#define P_FAMILY_WURMPLE                 TRUE
#define P_FAMILY_LOTAD                   TRUE
#define P_FAMILY_SEEDOT                  P_GEN_3_POKEMON
#define P_FAMILY_TAILLOW                 TRUE
#define P_FAMILY_WINGULL                 TRUE
#define P_FAMILY_RALTS                   TRUE
#define P_FAMILY_SURSKIT                 P_GEN_3_POKEMON
#define P_FAMILY_SHROOMISH               TRUE
#define P_FAMILY_SLAKOTH                 TRUE
#define P_FAMILY_NINCADA                 TRUE
#define P_FAMILY_WHISMUR                 TRUE
#define P_FAMILY_MAKUHITA                TRUE
#define P_FAMILY_NOSEPASS                TRUE
#define P_FAMILY_SKITTY                  TRUE
#define P_FAMILY_SABLEYE                 TRUE
#define P_FAMILY_MAWILE                  TRUE
#define P_FAMILY_ARON                    TRUE
#define P_FAMILY_MEDITITE                P_GEN_3_POKEMON
#define P_FAMILY_ELECTRIKE               TRUE
#define P_FAMILY_PLUSLE                  P_GEN_3_POKEMON
#define P_FAMILY_MINUN                   P_GEN_3_POKEMON
#define P_FAMILY_VOLBEAT_ILLUMISE        TRUE
#define P_FAMILY_ROSELIA                 P_GEN_3_POKEMON
#define P_FAMILY_GULPIN                  P_GEN_3_POKEMON
#define P_FAMILY_CARVANHA                TRUE
#define P_FAMILY_WAILMER                 P_GEN_3_POKEMON
#define P_FAMILY_NUMEL                   TRUE
#define P_FAMILY_TORKOAL                 TRUE
#define P_FAMILY_SPOINK                  P_GEN_3_POKEMON
#define P_FAMILY_SPINDA                  TRUE
#define P_FAMILY_TRAPINCH                TRUE
#define P_FAMILY_CACNEA                  TRUE
#define P_FAMILY_SWABLU                  TRUE
#define P_FAMILY_ZANGOOSE                TRUE
#define P_FAMILY_SEVIPER                 P_GEN_3_POKEMON
#define P_FAMILY_LUNATONE                P_GEN_3_POKEMON
#define P_FAMILY_SOLROCK                 P_GEN_3_POKEMON
#define P_FAMILY_BARBOACH                P_GEN_3_POKEMON
#define P_FAMILY_CORPHISH                TRUE
#define P_FAMILY_BALTOY                  TRUE
#define P_FAMILY_LILEEP                  TRUE
#define P_FAMILY_ANORITH                 TRUE
#define P_FAMILY_FEEBAS                  P_GEN_3_POKEMON
#define P_FAMILY_CASTFORM                TRUE
#define P_FAMILY_KECLEON                 TRUE
#define P_FAMILY_SHUPPET                 TRUE
#define P_FAMILY_DUSKULL                 TRUE
#define P_FAMILY_TROPIUS                 P_GEN_3_POKEMON
#define P_FAMILY_CHIMECHO                P_GEN_3_POKEMON
#define P_FAMILY_ABSOL                   TRUE
#define P_FAMILY_SNORUNT                 TRUE
#define P_FAMILY_SPHEAL                  P_GEN_3_POKEMON
#define P_FAMILY_CLAMPERL                P_GEN_3_POKEMON
#define P_FAMILY_RELICANTH               P_GEN_3_POKEMON
#define P_FAMILY_LUVDISC                 P_GEN_3_POKEMON
#define P_FAMILY_BAGON                   TRUE
#define P_FAMILY_BELDUM                  TRUE
#define P_FAMILY_REGIROCK                TRUE
#define P_FAMILY_REGICE                  TRUE
#define P_FAMILY_REGISTEEL               TRUE
#define P_FAMILY_LATIAS                  TRUE
#define P_FAMILY_LATIOS                  P_GEN_3_POKEMON
#define P_FAMILY_KYOGRE                  TRUE
#define P_FAMILY_GROUDON                 TRUE
#define P_FAMILY_RAYQUAZA                TRUE
#define P_FAMILY_JIRACHI                 TRUE
#define P_FAMILY_DEOXYS                  TRUE

#define P_FAMILY_TURTWIG                 P_GEN_4_POKEMON
#define P_FAMILY_CHIMCHAR                P_GEN_4_POKEMON
#define P_FAMILY_PIPLUP                  P_GEN_4_POKEMON
#define P_FAMILY_STARLY                  P_GEN_4_POKEMON
#define P_FAMILY_BIDOOF                  P_GEN_4_POKEMON
#define P_FAMILY_KRICKETOT               P_GEN_4_POKEMON
#define P_FAMILY_SHINX                   P_GEN_4_POKEMON
#define P_FAMILY_CRANIDOS                P_GEN_4_POKEMON
#define P_FAMILY_SHIELDON                P_GEN_4_POKEMON
#define P_FAMILY_BURMY                   P_GEN_4_POKEMON
#define P_FAMILY_COMBEE                  P_GEN_4_POKEMON
#define P_FAMILY_PACHIRISU               P_GEN_4_POKEMON
#define P_FAMILY_BUIZEL                  TRUE
#define P_FAMILY_CHERUBI                 TRUE
#define P_FAMILY_SHELLOS                 TRUE
#define P_FAMILY_DRIFLOON                P_GEN_4_POKEMON
#define P_FAMILY_BUNEARY                 TRUE
#define P_FAMILY_GLAMEOW                 P_GEN_4_POKEMON
#define P_FAMILY_STUNKY                  P_GEN_4_POKEMON
#define P_FAMILY_BRONZOR                 P_GEN_4_POKEMON
#define P_FAMILY_CHATOT                  P_GEN_4_POKEMON
#define P_FAMILY_SPIRITOMB               P_GEN_4_POKEMON
#define P_FAMILY_GIBLE                   TRUE
#define P_FAMILY_RIOLU                   TRUE
#define P_FAMILY_HIPPOPOTAS              TRUE
#define P_FAMILY_SKORUPI                 P_GEN_4_POKEMON
#define P_FAMILY_CROAGUNK                TRUE
#define P_FAMILY_CARNIVINE               P_GEN_4_POKEMON
#define P_FAMILY_FINNEON                 TRUE
#define P_FAMILY_SNOVER                  TRUE
#define P_FAMILY_ROTOM                   P_GEN_4_POKEMON
#define P_FAMILY_UXIE                    P_GEN_4_POKEMON
#define P_FAMILY_MESPRIT                 P_GEN_4_POKEMON
#define P_FAMILY_AZELF                   P_GEN_4_POKEMON
#define P_FAMILY_DIALGA                  P_GEN_4_POKEMON
#define P_FAMILY_PALKIA                  P_GEN_4_POKEMON
#define P_FAMILY_HEATRAN                 P_GEN_4_POKEMON
#define P_FAMILY_REGIGIGAS               P_GEN_4_POKEMON
#define P_FAMILY_GIRATINA                P_GEN_4_POKEMON
#define P_FAMILY_CRESSELIA               P_GEN_4_POKEMON
#define P_FAMILY_MANAPHY                 P_GEN_4_POKEMON
#define P_FAMILY_DARKRAI                 TRUE
#define P_FAMILY_SHAYMIN                 TRUE
#define P_FAMILY_ARCEUS                  TRUE

#define P_FAMILY_VICTINI                 P_GEN_5_POKEMON
#define P_FAMILY_SNIVY                   TRUE
#define P_FAMILY_TEPIG                   P_GEN_5_POKEMON
#define P_FAMILY_OSHAWOTT                P_GEN_5_POKEMON
#define P_FAMILY_PATRAT                  P_GEN_5_POKEMON
#define P_FAMILY_LILLIPUP                P_GEN_5_POKEMON
#define P_FAMILY_PURRLOIN                P_GEN_5_POKEMON
#define P_FAMILY_PANSAGE                 P_GEN_5_POKEMON
#define P_FAMILY_PANSEAR                 P_GEN_5_POKEMON
#define P_FAMILY_PANPOUR                 P_GEN_5_POKEMON
#define P_FAMILY_MUNNA                   P_GEN_5_POKEMON
#define P_FAMILY_PIDOVE                  P_GEN_5_POKEMON
#define P_FAMILY_BLITZLE                 TRUE
#define P_FAMILY_ROGGENROLA              P_GEN_5_POKEMON
#define P_FAMILY_WOOBAT                  P_GEN_5_POKEMON
#define P_FAMILY_DRILBUR                 P_GEN_5_POKEMON
#define P_FAMILY_AUDINO                  P_GEN_5_POKEMON
#define P_FAMILY_TIMBURR                 P_GEN_5_POKEMON
#define P_FAMILY_TYMPOLE                 TRUE
#define P_FAMILY_THROH                   P_GEN_5_POKEMON
#define P_FAMILY_SAWK                    P_GEN_5_POKEMON
#define P_FAMILY_SEWADDLE                P_GEN_5_POKEMON
#define P_FAMILY_VENIPEDE                P_GEN_5_POKEMON
#define P_FAMILY_COTTONEE                TRUE
#define P_FAMILY_PETILIL                 P_GEN_5_POKEMON
#define P_FAMILY_BASCULIN                TRUE
#define P_FAMILY_SANDILE                 P_GEN_5_POKEMON
#define P_FAMILY_DARUMAKA                TRUE
#define P_FAMILY_MARACTUS                P_GEN_5_POKEMON
#define P_FAMILY_DWEBBLE                 P_GEN_5_POKEMON
#define P_FAMILY_SCRAGGY                 P_GEN_5_POKEMON
#define P_FAMILY_SIGILYPH                P_GEN_5_POKEMON
#define P_FAMILY_YAMASK                  TRUE
#define P_FAMILY_TIRTOUGA                P_GEN_5_POKEMON
#define P_FAMILY_ARCHEN                  TRUE
#define P_FAMILY_TRUBBISH                TRUE
#define P_FAMILY_ZORUA                   TRUE
#define P_FAMILY_MINCCINO                P_GEN_5_POKEMON
#define P_FAMILY_GOTHITA                 P_GEN_5_POKEMON
#define P_FAMILY_SOLOSIS                 P_GEN_5_POKEMON
#define P_FAMILY_DUCKLETT                P_GEN_5_POKEMON
#define P_FAMILY_VANILLITE               P_GEN_5_POKEMON
#define P_FAMILY_DEERLING                P_GEN_5_POKEMON
#define P_FAMILY_EMOLGA                  P_GEN_5_POKEMON
#define P_FAMILY_KARRABLAST              P_GEN_5_POKEMON
#define P_FAMILY_FOONGUS                 P_GEN_5_POKEMON
#define P_FAMILY_FRILLISH                TRUE
#define P_FAMILY_ALOMOMOLA               P_GEN_5_POKEMON
#define P_FAMILY_JOLTIK                  P_GEN_5_POKEMON
#define P_FAMILY_FERROSEED               P_GEN_5_POKEMON
#define P_FAMILY_KLINK                   TRUE
#define P_FAMILY_TYNAMO                  P_GEN_5_POKEMON
#define P_FAMILY_ELGYEM                  P_GEN_5_POKEMON
#define P_FAMILY_LITWICK                 P_GEN_5_POKEMON
#define P_FAMILY_AXEW                    P_GEN_5_POKEMON
#define P_FAMILY_CUBCHOO                 P_GEN_5_POKEMON
#define P_FAMILY_CRYOGONAL               P_GEN_5_POKEMON
#define P_FAMILY_SHELMET                 P_GEN_5_POKEMON
#define P_FAMILY_STUNFISK                TRUE
#define P_FAMILY_MIENFOO                 TRUE
#define P_FAMILY_DRUDDIGON               P_GEN_5_POKEMON
#define P_FAMILY_GOLETT                  TRUE
#define P_FAMILY_PAWNIARD                TRUE
#define P_FAMILY_BOUFFALANT              P_GEN_5_POKEMON
#define P_FAMILY_RUFFLET                 P_GEN_5_POKEMON
#define P_FAMILY_VULLABY                 P_GEN_5_POKEMON
#define P_FAMILY_HEATMOR                 P_GEN_5_POKEMON
#define P_FAMILY_DURANT                  P_GEN_5_POKEMON
#define P_FAMILY_DEINO                   P_GEN_5_POKEMON
#define P_FAMILY_LARVESTA                P_GEN_5_POKEMON
#define P_FAMILY_COBALION                P_GEN_5_POKEMON
#define P_FAMILY_TERRAKION               P_GEN_5_POKEMON
#define P_FAMILY_VIRIZION                P_GEN_5_POKEMON
#define P_FAMILY_TORNADUS                TRUE
#define P_FAMILY_THUNDURUS               P_GEN_5_POKEMON
#define P_FAMILY_RESHIRAM                P_GEN_5_POKEMON
#define P_FAMILY_ZEKROM                  TRUE
#define P_FAMILY_LANDORUS                P_GEN_5_POKEMON
#define P_FAMILY_KYUREM                  TRUE
#define P_FAMILY_KELDEO                  P_GEN_5_POKEMON
#define P_FAMILY_MELOETTA                TRUE
#define P_FAMILY_GENESECT                TRUE

#define P_FAMILY_CHESPIN                 TRUE
#define P_FAMILY_FENNEKIN                TRUE
#define P_FAMILY_FROAKIE                 TRUE
#define P_FAMILY_BUNNELBY                P_GEN_6_POKEMON
#define P_FAMILY_FLETCHLING              TRUE
#define P_FAMILY_SCATTERBUG              TRUE
#define P_FAMILY_LITLEO                  P_GEN_6_POKEMON
#define P_FAMILY_FLABEBE                 TRUE
#define P_FAMILY_SKIDDO                  P_GEN_6_POKEMON
#define P_FAMILY_PANCHAM                 P_GEN_6_POKEMON
#define P_FAMILY_FURFROU                 P_GEN_6_POKEMON
#define P_FAMILY_ESPURR                  P_GEN_6_POKEMON
#define P_FAMILY_HONEDGE                 TRUE
#define P_FAMILY_SPRITZEE                P_GEN_6_POKEMON
#define P_FAMILY_SWIRLIX                 P_GEN_6_POKEMON
#define P_FAMILY_INKAY                   TRUE
#define P_FAMILY_BINACLE                 TRUE
#define P_FAMILY_SKRELP                  P_GEN_6_POKEMON
#define P_FAMILY_CLAUNCHER               TRUE
#define P_FAMILY_HELIOPTILE              P_GEN_6_POKEMON
#define P_FAMILY_TYRUNT                  P_GEN_6_POKEMON
#define P_FAMILY_AMAURA                  TRUE
#define P_FAMILY_HAWLUCHA                P_GEN_6_POKEMON
#define P_FAMILY_DEDENNE                 P_GEN_6_POKEMON
#define P_FAMILY_CARBINK                 P_GEN_6_POKEMON
#define P_FAMILY_GOOMY                   TRUE
#define P_FAMILY_KLEFKI                  P_GEN_6_POKEMON
#define P_FAMILY_PHANTUMP                P_GEN_6_POKEMON
#define P_FAMILY_PUMPKABOO               P_GEN_6_POKEMON
#define P_FAMILY_BERGMITE                P_GEN_6_POKEMON
#define P_FAMILY_NOIBAT                  P_GEN_6_POKEMON
#define P_FAMILY_XERNEAS                 TRUE
#define P_FAMILY_YVELTAL                 P_GEN_6_POKEMON
#define P_FAMILY_ZYGARDE                 TRUE
#define P_FAMILY_DIANCIE                 P_GEN_6_POKEMON
#define P_FAMILY_HOOPA                   P_GEN_6_POKEMON
#define P_FAMILY_VOLCANION               P_GEN_6_POKEMON

#define P_FAMILY_ROWLET                  P_GEN_7_POKEMON
#define P_FAMILY_LITTEN                  TRUE
#define P_FAMILY_POPPLIO                 TRUE
#define P_FAMILY_PIKIPEK                 P_GEN_7_POKEMON
#define P_FAMILY_YUNGOOS                 TRUE
#define P_FAMILY_GRUBBIN                 P_GEN_7_POKEMON
#define P_FAMILY_CRABRAWLER              P_GEN_7_POKEMON
#define P_FAMILY_ORICORIO                TRUE
#define P_FAMILY_CUTIEFLY                P_GEN_7_POKEMON
#define P_FAMILY_ROCKRUFF                TRUE
#define P_FAMILY_WISHIWASHI              TRUE
#define P_FAMILY_MAREANIE                TRUE
#define P_FAMILY_MUDBRAY                 TRUE
#define P_FAMILY_DEWPIDER                TRUE
#define P_FAMILY_FOMANTIS                P_GEN_7_POKEMON
#define P_FAMILY_MORELULL                P_GEN_7_POKEMON
#define P_FAMILY_SALANDIT                TRUE
#define P_FAMILY_STUFFUL                 TRUE
#define P_FAMILY_BOUNSWEET               TRUE
#define P_FAMILY_COMFEY                  TRUE
#define P_FAMILY_ORANGURU                P_GEN_7_POKEMON
#define P_FAMILY_PASSIMIAN               TRUE
#define P_FAMILY_WIMPOD                  TRUE
#define P_FAMILY_SANDYGAST               P_GEN_7_POKEMON
#define P_FAMILY_PYUKUMUKU               TRUE
#define P_FAMILY_TYPE_NULL               TRUE
#define P_FAMILY_MINIOR                  TRUE
#define P_FAMILY_KOMALA                  TRUE
#define P_FAMILY_TURTONATOR              P_GEN_7_POKEMON
#define P_FAMILY_TOGEDEMARU              P_GEN_7_POKEMON
#define P_FAMILY_MIMIKYU                 TRUE
#define P_FAMILY_BRUXISH                 TRUE
#define P_FAMILY_DRAMPA                  TRUE
#define P_FAMILY_DHELMISE                TRUE
#define P_FAMILY_JANGMO_O                TRUE
#define P_FAMILY_TAPU_KOKO               TRUE
#define P_FAMILY_TAPU_LELE               TRUE
#define P_FAMILY_TAPU_BULU               P_GEN_7_POKEMON
#define P_FAMILY_TAPU_FINI               TRUE
#define P_FAMILY_COSMOG                  TRUE
#define P_FAMILY_NIHILEGO                TRUE
#define P_FAMILY_BUZZWOLE                P_GEN_7_POKEMON
#define P_FAMILY_PHEROMOSA               P_GEN_7_POKEMON
#define P_FAMILY_XURKITREE               P_GEN_7_POKEMON
#define P_FAMILY_CELESTEELA              P_GEN_7_POKEMON
#define P_FAMILY_KARTANA                 P_GEN_7_POKEMON
#define P_FAMILY_GUZZLORD                P_GEN_7_POKEMON
#define P_FAMILY_NECROZMA                TRUE
#define P_FAMILY_MAGEARNA                P_GEN_7_POKEMON
#define P_FAMILY_MARSHADOW               TRUE
#define P_FAMILY_POIPOLE                 P_GEN_7_POKEMON
#define P_FAMILY_STAKATAKA               P_GEN_7_POKEMON
#define P_FAMILY_BLACEPHALON             P_GEN_7_POKEMON
#define P_FAMILY_ZERAORA                 P_GEN_7_POKEMON
#define P_FAMILY_MELTAN                  TRUE

#define P_FAMILY_GROOKEY                 P_GEN_8_POKEMON
#define P_FAMILY_SCORBUNNY               P_GEN_8_POKEMON
#define P_FAMILY_SOBBLE                  TRUE
#define P_FAMILY_SKWOVET                 TRUE
#define P_FAMILY_ROOKIDEE                TRUE
#define P_FAMILY_BLIPBUG                 TRUE
#define P_FAMILY_NICKIT                  P_GEN_8_POKEMON
#define P_FAMILY_GOSSIFLEUR              TRUE
#define P_FAMILY_WOOLOO                  P_GEN_8_POKEMON
#define P_FAMILY_CHEWTLE                 TRUE
#define P_FAMILY_YAMPER                  P_GEN_8_POKEMON
#define P_FAMILY_ROLYCOLY                P_GEN_8_POKEMON
#define P_FAMILY_APPLIN                  TRUE
#define P_FAMILY_SILICOBRA               P_GEN_8_POKEMON
#define P_FAMILY_CRAMORANT               TRUE
#define P_FAMILY_ARROKUDA                P_GEN_8_POKEMON
#define P_FAMILY_TOXEL                   TRUE
#define P_FAMILY_SIZZLIPEDE              TRUE
#define P_FAMILY_CLOBBOPUS               P_GEN_8_POKEMON
#define P_FAMILY_SINISTEA                P_GEN_8_POKEMON
#define P_FAMILY_HATENNA                 TRUE
#define P_FAMILY_IMPIDIMP                TRUE
#define P_FAMILY_MILCERY                 TRUE
#define P_FAMILY_FALINKS                 P_GEN_8_POKEMON
#define P_FAMILY_PINCURCHIN              P_GEN_8_POKEMON
#define P_FAMILY_SNOM                    TRUE
#define P_FAMILY_STONJOURNER             P_GEN_8_POKEMON
#define P_FAMILY_EISCUE                  TRUE
#define P_FAMILY_INDEEDEE                P_GEN_8_POKEMON
#define P_FAMILY_MORPEKO                 TRUE
#define P_FAMILY_CUFANT                  TRUE
#define P_FAMILY_DRACOZOLT               P_GEN_8_POKEMON
#define P_FAMILY_ARCTOZOLT               P_GEN_8_POKEMON
#define P_FAMILY_DRACOVISH               P_GEN_8_POKEMON
#define P_FAMILY_ARCTOVISH               TRUE
#define P_FAMILY_DURALUDON               TRUE
#define P_FAMILY_DREEPY                  P_GEN_8_POKEMON
#define P_FAMILY_ZACIAN                  TRUE
#define P_FAMILY_ZAMAZENTA               TRUE
#define P_FAMILY_ETERNATUS               P_GEN_8_POKEMON
#define P_FAMILY_KUBFU                   TRUE
#define P_FAMILY_ZARUDE                  P_GEN_8_POKEMON
#define P_FAMILY_REGIELEKI               TRUE
#define P_FAMILY_REGIDRAGO               TRUE
#define P_FAMILY_GLASTRIER               P_GEN_8_POKEMON
#define P_FAMILY_SPECTRIER               P_GEN_8_POKEMON
#define P_FAMILY_CALYREX                 TRUE
#define P_FAMILY_ENAMORUS                P_GEN_8_POKEMON

#define P_FAMILY_SPRIGATITO              P_GEN_9_POKEMON
#define P_FAMILY_FUECOCO                 P_GEN_9_POKEMON
#define P_FAMILY_QUAXLY                  P_GEN_9_POKEMON
#define P_FAMILY_LECHONK                 TRUE
#define P_FAMILY_TAROUNTULA              P_GEN_9_POKEMON
#define P_FAMILY_NYMBLE                  P_GEN_9_POKEMON
#define P_FAMILY_PAWMI                   P_GEN_9_POKEMON
#define P_FAMILY_TANDEMAUS               P_GEN_9_POKEMON
#define P_FAMILY_FIDOUGH                 P_GEN_9_POKEMON
#define P_FAMILY_SMOLIV                  TRUE
#define P_FAMILY_SQUAWKABILLY            P_GEN_9_POKEMON
#define P_FAMILY_NACLI                   TRUE
#define P_FAMILY_CHARCADET               P_GEN_9_POKEMON
#define P_FAMILY_TADBULB                 TRUE
#define P_FAMILY_WATTREL                 TRUE
#define P_FAMILY_MASCHIFF                P_GEN_9_POKEMON
#define P_FAMILY_SHROODLE                P_GEN_9_POKEMON
#define P_FAMILY_BRAMBLIN                P_GEN_9_POKEMON
#define P_FAMILY_TOEDSCOOL               TRUE
#define P_FAMILY_KLAWF                   TRUE
#define P_FAMILY_CAPSAKID                P_GEN_9_POKEMON
#define P_FAMILY_RELLOR                  P_GEN_9_POKEMON
#define P_FAMILY_FLITTLE                 TRUE
#define P_FAMILY_TINKATINK               TRUE
#define P_FAMILY_WIGLETT                 P_GEN_9_POKEMON
#define P_FAMILY_BOMBIRDIER              TRUE
#define P_FAMILY_FINIZEN                 TRUE
#define P_FAMILY_VAROOM                  P_GEN_9_POKEMON
#define P_FAMILY_CYCLIZAR                P_GEN_9_POKEMON
#define P_FAMILY_ORTHWORM                TRUE
#define P_FAMILY_GLIMMET                 TRUE
#define P_FAMILY_GREAVARD                TRUE
#define P_FAMILY_FLAMIGO                 P_GEN_9_POKEMON
#define P_FAMILY_CETODDLE                P_GEN_9_POKEMON
#define P_FAMILY_VELUZA                  P_GEN_9_POKEMON
#define P_FAMILY_DONDOZO                 P_GEN_9_POKEMON
#define P_FAMILY_TATSUGIRI               TRUE
#define P_FAMILY_GREAT_TUSK              TRUE
#define P_FAMILY_SCREAM_TAIL             P_GEN_9_POKEMON
#define P_FAMILY_BRUTE_BONNET            P_GEN_9_POKEMON
#define P_FAMILY_FLUTTER_MANE            P_GEN_9_POKEMON
#define P_FAMILY_SLITHER_WING            P_GEN_9_POKEMON
#define P_FAMILY_SANDY_SHOCKS            P_GEN_9_POKEMON
#define P_FAMILY_IRON_TREADS             P_GEN_9_POKEMON
#define P_FAMILY_IRON_BUNDLE             P_GEN_9_POKEMON
#define P_FAMILY_IRON_HANDS              P_GEN_9_POKEMON
#define P_FAMILY_IRON_JUGULIS            P_GEN_9_POKEMON
#define P_FAMILY_IRON_MOTH               TRUE
#define P_FAMILY_IRON_THORNS             P_GEN_9_POKEMON
#define P_FAMILY_FRIGIBAX                TRUE
#define P_FAMILY_GIMMIGHOUL              TRUE
#define P_FAMILY_WO_CHIEN                TRUE
#define P_FAMILY_CHIEN_PAO               TRUE
#define P_FAMILY_TING_LU                 TRUE
#define P_FAMILY_CHI_YU                  TRUE
#define P_FAMILY_ROARING_MOON            TRUE
#define P_FAMILY_IRON_VALIANT            TRUE
#define P_FAMILY_KORAIDON                P_GEN_9_POKEMON
#define P_FAMILY_MIRAIDON                P_GEN_9_POKEMON
#define P_FAMILY_WALKING_WAKE            TRUE
#define P_FAMILY_IRON_LEAVES             P_GEN_9_POKEMON
#define P_FAMILY_POLTCHAGEIST            TRUE
#define P_FAMILY_OKIDOGI                 TRUE
#define P_FAMILY_MUNKIDORI               P_GEN_9_POKEMON
#define P_FAMILY_FEZANDIPITI             P_GEN_9_POKEMON
#define P_FAMILY_OGERPON                 TRUE
#define P_FAMILY_GOUGING_FIRE            P_GEN_9_POKEMON
#define P_FAMILY_RAGING_BOLT             TRUE
#define P_FAMILY_IRON_BOULDER            P_GEN_9_POKEMON
#define P_FAMILY_IRON_CROWN              P_GEN_9_POKEMON
#define P_FAMILY_TERAPAGOS               TRUE
#define P_FAMILY_PECHARUNT               TRUE

#endif // GUARD_CONFIG_TEST_SPECIES_ENABLED_H
