#include "global.h"
#include "battle.h"
#include "pokemon.h"
#include "string_util.h"
#include "strings.h"
#include "compatibility.h"
#include "util.h"
#include "characters.h"
#include "battle_message.h"
#include "constants/abilities.h"
#include "constants/items.h"
#include "constants/moves.h"
#include "constants/species.h"

u32 Vanilla_GetMonData(struct VanillaPokemon *mon, s32 field, u8 *data);
u32 Vanilla_GetBoxMonData(struct VanillaBoxPokemon *boxMon, s32 field, u8 *data);
u8 Vanilla_GetNature(struct VanillaPokemon *mon);
u32 Vanilla_GetBoxMonData(struct VanillaBoxPokemon *boxMon, s32 field, u8 *data);
u16 Vanilla_CalculateBoxMonChecksum(struct VanillaBoxPokemon *boxMon);
void Vanilla_SetBoxMonData(struct VanillaBoxPokemon *boxMon, s32 field, const void *dataArg);
u16 Vanilla_GetDeoxysStat(struct VanillaPokemon *mon, s32 statId);
union VanillaPokemonSubstruct *Vanilla_GetSubstruct(struct VanillaBoxPokemon *boxMon, u32 personality, u8 substructType);

// Data
static const u16 sExpansionSpeciesToVanilla[] =
{
    [SPECIES_NONE] = VANILLA_SPECIES_NONE,
    [SPECIES_BULBASAUR] = VANILLA_SPECIES_BULBASAUR,
    [SPECIES_IVYSAUR] = VANILLA_SPECIES_IVYSAUR,
    [SPECIES_VENUSAUR] = VANILLA_SPECIES_VENUSAUR,
    [SPECIES_CHARMANDER] = VANILLA_SPECIES_CHARMANDER,
    [SPECIES_CHARMELEON] = VANILLA_SPECIES_CHARMELEON,
    [SPECIES_CHARIZARD] = VANILLA_SPECIES_CHARIZARD,
    [SPECIES_SQUIRTLE] = VANILLA_SPECIES_SQUIRTLE,
    [SPECIES_WARTORTLE] = VANILLA_SPECIES_WARTORTLE,
    [SPECIES_BLASTOISE] = VANILLA_SPECIES_BLASTOISE,
    [SPECIES_CATERPIE] = VANILLA_SPECIES_CATERPIE,
    [SPECIES_METAPOD] = VANILLA_SPECIES_METAPOD,
    [SPECIES_BUTTERFREE] = VANILLA_SPECIES_BUTTERFREE,
    [SPECIES_WEEDLE] = VANILLA_SPECIES_WEEDLE,
    [SPECIES_KAKUNA] = VANILLA_SPECIES_KAKUNA,
    [SPECIES_BEEDRILL] = VANILLA_SPECIES_BEEDRILL,
    [SPECIES_PIDGEY] = VANILLA_SPECIES_PIDGEY,
    [SPECIES_PIDGEOTTO] = VANILLA_SPECIES_PIDGEOTTO,
    [SPECIES_PIDGEOT] = VANILLA_SPECIES_PIDGEOT,
    [SPECIES_RATTATA] = VANILLA_SPECIES_RATTATA,
    [SPECIES_RATICATE] = VANILLA_SPECIES_RATICATE,
    [SPECIES_SPEAROW] = VANILLA_SPECIES_SPEAROW,
    [SPECIES_FEAROW] = VANILLA_SPECIES_FEAROW,
    [SPECIES_EKANS] = VANILLA_SPECIES_EKANS,
    [SPECIES_ARBOK] = VANILLA_SPECIES_ARBOK,
    [SPECIES_PIKACHU] = VANILLA_SPECIES_PIKACHU,
    [SPECIES_RAICHU] = VANILLA_SPECIES_RAICHU,
    [SPECIES_SANDSHREW] = VANILLA_SPECIES_SANDSHREW,
    [SPECIES_SANDSLASH] = VANILLA_SPECIES_SANDSLASH,
    [SPECIES_NIDORAN_F] = VANILLA_SPECIES_NIDORAN_F,
    [SPECIES_NIDORINA] = VANILLA_SPECIES_NIDORINA,
    [SPECIES_NIDOQUEEN] = VANILLA_SPECIES_NIDOQUEEN,
    [SPECIES_NIDORAN_M] = VANILLA_SPECIES_NIDORAN_M,
    [SPECIES_NIDORINO] = VANILLA_SPECIES_NIDORINO,
    [SPECIES_NIDOKING] = VANILLA_SPECIES_NIDOKING,
    [SPECIES_CLEFAIRY] = VANILLA_SPECIES_CLEFAIRY,
    [SPECIES_CLEFABLE] = VANILLA_SPECIES_CLEFABLE,
    [SPECIES_VULPIX] = VANILLA_SPECIES_VULPIX,
    [SPECIES_NINETALES] = VANILLA_SPECIES_NINETALES,
    [SPECIES_JIGGLYPUFF] = VANILLA_SPECIES_JIGGLYPUFF,
    [SPECIES_WIGGLYTUFF] = VANILLA_SPECIES_WIGGLYTUFF,
    [SPECIES_ZUBAT] = VANILLA_SPECIES_ZUBAT,
    [SPECIES_GOLBAT] = VANILLA_SPECIES_GOLBAT,
    [SPECIES_ODDISH] = VANILLA_SPECIES_ODDISH,
    [SPECIES_GLOOM] = VANILLA_SPECIES_GLOOM,
    [SPECIES_VILEPLUME] = VANILLA_SPECIES_VILEPLUME,
    [SPECIES_PARAS] = VANILLA_SPECIES_PARAS,
    [SPECIES_PARASECT] = VANILLA_SPECIES_PARASECT,
    [SPECIES_VENONAT] = VANILLA_SPECIES_VENONAT,
    [SPECIES_VENOMOTH] = VANILLA_SPECIES_VENOMOTH,
    [SPECIES_DIGLETT] = VANILLA_SPECIES_DIGLETT,
    [SPECIES_DUGTRIO] = VANILLA_SPECIES_DUGTRIO,
    [SPECIES_MEOWTH] = VANILLA_SPECIES_MEOWTH,
    [SPECIES_PERSIAN] = VANILLA_SPECIES_PERSIAN,
    [SPECIES_PSYDUCK] = VANILLA_SPECIES_PSYDUCK,
    [SPECIES_GOLDUCK] = VANILLA_SPECIES_GOLDUCK,
    [SPECIES_MANKEY] = VANILLA_SPECIES_MANKEY,
    [SPECIES_PRIMEAPE] = VANILLA_SPECIES_PRIMEAPE,
    [SPECIES_GROWLITHE] = VANILLA_SPECIES_GROWLITHE,
    [SPECIES_ARCANINE] = VANILLA_SPECIES_ARCANINE,
    [SPECIES_POLIWAG] = VANILLA_SPECIES_POLIWAG,
    [SPECIES_POLIWHIRL] = VANILLA_SPECIES_POLIWHIRL,
    [SPECIES_POLIWRATH] = VANILLA_SPECIES_POLIWRATH,
    [SPECIES_ABRA] = VANILLA_SPECIES_ABRA,
    [SPECIES_KADABRA] = VANILLA_SPECIES_KADABRA,
    [SPECIES_ALAKAZAM] = VANILLA_SPECIES_ALAKAZAM,
    [SPECIES_MACHOP] = VANILLA_SPECIES_MACHOP,
    [SPECIES_MACHOKE] = VANILLA_SPECIES_MACHOKE,
    [SPECIES_MACHAMP] = VANILLA_SPECIES_MACHAMP,
    [SPECIES_BELLSPROUT] = VANILLA_SPECIES_BELLSPROUT,
    [SPECIES_WEEPINBELL] = VANILLA_SPECIES_WEEPINBELL,
    [SPECIES_VICTREEBEL] = VANILLA_SPECIES_VICTREEBEL,
    [SPECIES_TENTACOOL] = VANILLA_SPECIES_TENTACOOL,
    [SPECIES_TENTACRUEL] = VANILLA_SPECIES_TENTACRUEL,
    [SPECIES_GEODUDE] = VANILLA_SPECIES_GEODUDE,
    [SPECIES_GRAVELER] = VANILLA_SPECIES_GRAVELER,
    [SPECIES_GOLEM] = VANILLA_SPECIES_GOLEM,
    [SPECIES_PONYTA] = VANILLA_SPECIES_PONYTA,
    [SPECIES_RAPIDASH] = VANILLA_SPECIES_RAPIDASH,
    [SPECIES_SLOWPOKE] = VANILLA_SPECIES_SLOWPOKE,
    [SPECIES_SLOWBRO] = VANILLA_SPECIES_SLOWBRO,
    [SPECIES_MAGNEMITE] = VANILLA_SPECIES_MAGNEMITE,
    [SPECIES_MAGNETON] = VANILLA_SPECIES_MAGNETON,
    [SPECIES_FARFETCHD] = VANILLA_SPECIES_FARFETCHD,
    [SPECIES_DODUO] = VANILLA_SPECIES_DODUO,
    [SPECIES_DODRIO] = VANILLA_SPECIES_DODRIO,
    [SPECIES_SEEL] = VANILLA_SPECIES_SEEL,
    [SPECIES_DEWGONG] = VANILLA_SPECIES_DEWGONG,
    [SPECIES_GRIMER] = VANILLA_SPECIES_GRIMER,
    [SPECIES_MUK] = VANILLA_SPECIES_MUK,
    [SPECIES_SHELLDER] = VANILLA_SPECIES_SHELLDER,
    [SPECIES_CLOYSTER] = VANILLA_SPECIES_CLOYSTER,
    [SPECIES_GASTLY] = VANILLA_SPECIES_GASTLY,
    [SPECIES_HAUNTER] = VANILLA_SPECIES_HAUNTER,
    [SPECIES_GENGAR] = VANILLA_SPECIES_GENGAR,
    [SPECIES_ONIX] = VANILLA_SPECIES_ONIX,
    [SPECIES_DROWZEE] = VANILLA_SPECIES_DROWZEE,
    [SPECIES_HYPNO] = VANILLA_SPECIES_HYPNO,
    [SPECIES_KRABBY] = VANILLA_SPECIES_KRABBY,
    [SPECIES_KINGLER] = VANILLA_SPECIES_KINGLER,
    [SPECIES_VOLTORB] = VANILLA_SPECIES_VOLTORB,
    [SPECIES_ELECTRODE] = VANILLA_SPECIES_ELECTRODE,
    [SPECIES_EXEGGCUTE] = VANILLA_SPECIES_EXEGGCUTE,
    [SPECIES_EXEGGUTOR] = VANILLA_SPECIES_EXEGGUTOR,
    [SPECIES_CUBONE] = VANILLA_SPECIES_CUBONE,
    [SPECIES_MAROWAK] = VANILLA_SPECIES_MAROWAK,
    [SPECIES_HITMONLEE] = VANILLA_SPECIES_HITMONLEE,
    [SPECIES_HITMONCHAN] = VANILLA_SPECIES_HITMONCHAN,
    [SPECIES_LICKITUNG] = VANILLA_SPECIES_LICKITUNG,
    [SPECIES_KOFFING] = VANILLA_SPECIES_KOFFING,
    [SPECIES_WEEZING] = VANILLA_SPECIES_WEEZING,
    [SPECIES_RHYHORN] = VANILLA_SPECIES_RHYHORN,
    [SPECIES_RHYDON] = VANILLA_SPECIES_RHYDON,
    [SPECIES_CHANSEY] = VANILLA_SPECIES_CHANSEY,
    [SPECIES_TANGELA] = VANILLA_SPECIES_TANGELA,
    [SPECIES_KANGASKHAN] = VANILLA_SPECIES_KANGASKHAN,
    [SPECIES_HORSEA] = VANILLA_SPECIES_HORSEA,
    [SPECIES_SEADRA] = VANILLA_SPECIES_SEADRA,
    [SPECIES_GOLDEEN] = VANILLA_SPECIES_GOLDEEN,
    [SPECIES_SEAKING] = VANILLA_SPECIES_SEAKING,
    [SPECIES_STARYU] = VANILLA_SPECIES_STARYU,
    [SPECIES_STARMIE] = VANILLA_SPECIES_STARMIE,
    [SPECIES_MR_MIME] = VANILLA_SPECIES_MR_MIME,
    [SPECIES_SCYTHER] = VANILLA_SPECIES_SCYTHER,
    [SPECIES_JYNX] = VANILLA_SPECIES_JYNX,
    [SPECIES_ELECTABUZZ] = VANILLA_SPECIES_ELECTABUZZ,
    [SPECIES_MAGMAR] = VANILLA_SPECIES_MAGMAR,
    [SPECIES_PINSIR] = VANILLA_SPECIES_PINSIR,
    [SPECIES_TAUROS] = VANILLA_SPECIES_TAUROS,
    [SPECIES_MAGIKARP] = VANILLA_SPECIES_MAGIKARP,
    [SPECIES_GYARADOS] = VANILLA_SPECIES_GYARADOS,
    [SPECIES_LAPRAS] = VANILLA_SPECIES_LAPRAS,
    [SPECIES_DITTO] = VANILLA_SPECIES_DITTO,
    [SPECIES_EEVEE] = VANILLA_SPECIES_EEVEE,
    [SPECIES_VAPOREON] = VANILLA_SPECIES_VAPOREON,
    [SPECIES_JOLTEON] = VANILLA_SPECIES_JOLTEON,
    [SPECIES_FLAREON] = VANILLA_SPECIES_FLAREON,
    [SPECIES_PORYGON] = VANILLA_SPECIES_PORYGON,
    [SPECIES_OMANYTE] = VANILLA_SPECIES_OMANYTE,
    [SPECIES_OMASTAR] = VANILLA_SPECIES_OMASTAR,
    [SPECIES_KABUTO] = VANILLA_SPECIES_KABUTO,
    [SPECIES_KABUTOPS] = VANILLA_SPECIES_KABUTOPS,
    [SPECIES_AERODACTYL] = VANILLA_SPECIES_AERODACTYL,
    [SPECIES_SNORLAX] = VANILLA_SPECIES_SNORLAX,
    [SPECIES_ARTICUNO] = VANILLA_SPECIES_ARTICUNO,
    [SPECIES_ZAPDOS] = VANILLA_SPECIES_ZAPDOS,
    [SPECIES_MOLTRES] = VANILLA_SPECIES_MOLTRES,
    [SPECIES_DRATINI] = VANILLA_SPECIES_DRATINI,
    [SPECIES_DRAGONAIR] = VANILLA_SPECIES_DRAGONAIR,
    [SPECIES_DRAGONITE] = VANILLA_SPECIES_DRAGONITE,
    [SPECIES_MEWTWO] = VANILLA_SPECIES_MEWTWO,
    [SPECIES_MEW] = VANILLA_SPECIES_MEW,
    [SPECIES_CHIKORITA] = VANILLA_SPECIES_CHIKORITA,
    [SPECIES_BAYLEEF] = VANILLA_SPECIES_BAYLEEF,
    [SPECIES_MEGANIUM] = VANILLA_SPECIES_MEGANIUM,
    [SPECIES_CYNDAQUIL] = VANILLA_SPECIES_CYNDAQUIL,
    [SPECIES_QUILAVA] = VANILLA_SPECIES_QUILAVA,
    [SPECIES_TYPHLOSION] = VANILLA_SPECIES_TYPHLOSION,
    [SPECIES_TOTODILE] = VANILLA_SPECIES_TOTODILE,
    [SPECIES_CROCONAW] = VANILLA_SPECIES_CROCONAW,
    [SPECIES_FERALIGATR] = VANILLA_SPECIES_FERALIGATR,
    [SPECIES_SENTRET] = VANILLA_SPECIES_SENTRET,
    [SPECIES_FURRET] = VANILLA_SPECIES_FURRET,
    [SPECIES_HOOTHOOT] = VANILLA_SPECIES_HOOTHOOT,
    [SPECIES_NOCTOWL] = VANILLA_SPECIES_NOCTOWL,
    [SPECIES_LEDYBA] = VANILLA_SPECIES_LEDYBA,
    [SPECIES_LEDIAN] = VANILLA_SPECIES_LEDIAN,
    [SPECIES_SPINARAK] = VANILLA_SPECIES_SPINARAK,
    [SPECIES_ARIADOS] = VANILLA_SPECIES_ARIADOS,
    [SPECIES_CROBAT] = VANILLA_SPECIES_CROBAT,
    [SPECIES_CHINCHOU] = VANILLA_SPECIES_CHINCHOU,
    [SPECIES_LANTURN] = VANILLA_SPECIES_LANTURN,
    [SPECIES_PICHU] = VANILLA_SPECIES_PICHU,
    [SPECIES_CLEFFA] = VANILLA_SPECIES_CLEFFA,
    [SPECIES_IGGLYBUFF] = VANILLA_SPECIES_IGGLYBUFF,
    [SPECIES_TOGEPI] = VANILLA_SPECIES_TOGEPI,
    [SPECIES_TOGETIC] = VANILLA_SPECIES_TOGETIC,
    [SPECIES_NATU] = VANILLA_SPECIES_NATU,
    [SPECIES_XATU] = VANILLA_SPECIES_XATU,
    [SPECIES_MAREEP] = VANILLA_SPECIES_MAREEP,
    [SPECIES_FLAAFFY] = VANILLA_SPECIES_FLAAFFY,
    [SPECIES_AMPHAROS] = VANILLA_SPECIES_AMPHAROS,
    [SPECIES_BELLOSSOM] = VANILLA_SPECIES_BELLOSSOM,
    [SPECIES_MARILL] = VANILLA_SPECIES_MARILL,
    [SPECIES_AZUMARILL] = VANILLA_SPECIES_AZUMARILL,
    [SPECIES_SUDOWOODO] = VANILLA_SPECIES_SUDOWOODO,
    [SPECIES_POLITOED] = VANILLA_SPECIES_POLITOED,
    [SPECIES_HOPPIP] = VANILLA_SPECIES_HOPPIP,
    [SPECIES_SKIPLOOM] = VANILLA_SPECIES_SKIPLOOM,
    [SPECIES_JUMPLUFF] = VANILLA_SPECIES_JUMPLUFF,
    [SPECIES_AIPOM] = VANILLA_SPECIES_AIPOM,
    [SPECIES_SUNKERN] = VANILLA_SPECIES_SUNKERN,
    [SPECIES_SUNFLORA] = VANILLA_SPECIES_SUNFLORA,
    [SPECIES_YANMA] = VANILLA_SPECIES_YANMA,
    [SPECIES_WOOPER] = VANILLA_SPECIES_WOOPER,
    [SPECIES_QUAGSIRE] = VANILLA_SPECIES_QUAGSIRE,
    [SPECIES_ESPEON] = VANILLA_SPECIES_ESPEON,
    [SPECIES_UMBREON] = VANILLA_SPECIES_UMBREON,
    [SPECIES_MURKROW] = VANILLA_SPECIES_MURKROW,
    [SPECIES_SLOWKING] = VANILLA_SPECIES_SLOWKING,
    [SPECIES_MISDREAVUS] = VANILLA_SPECIES_MISDREAVUS,
    [SPECIES_UNOWN] = VANILLA_SPECIES_UNOWN,
    [SPECIES_WOBBUFFET] = VANILLA_SPECIES_WOBBUFFET,
    [SPECIES_GIRAFARIG] = VANILLA_SPECIES_GIRAFARIG,
    [SPECIES_PINECO] = VANILLA_SPECIES_PINECO,
    [SPECIES_FORRETRESS] = VANILLA_SPECIES_FORRETRESS,
    [SPECIES_DUNSPARCE] = VANILLA_SPECIES_DUNSPARCE,
    [SPECIES_GLIGAR] = VANILLA_SPECIES_GLIGAR,
    [SPECIES_STEELIX] = VANILLA_SPECIES_STEELIX,
    [SPECIES_SNUBBULL] = VANILLA_SPECIES_SNUBBULL,
    [SPECIES_GRANBULL] = VANILLA_SPECIES_GRANBULL,
    [SPECIES_QWILFISH] = VANILLA_SPECIES_QWILFISH,
    [SPECIES_SCIZOR] = VANILLA_SPECIES_SCIZOR,
    [SPECIES_SHUCKLE] = VANILLA_SPECIES_SHUCKLE,
    [SPECIES_HERACROSS] = VANILLA_SPECIES_HERACROSS,
    [SPECIES_SNEASEL] = VANILLA_SPECIES_SNEASEL,
    [SPECIES_TEDDIURSA] = VANILLA_SPECIES_TEDDIURSA,
    [SPECIES_URSARING] = VANILLA_SPECIES_URSARING,
    [SPECIES_SLUGMA] = VANILLA_SPECIES_SLUGMA,
    [SPECIES_MAGCARGO] = VANILLA_SPECIES_MAGCARGO,
    [SPECIES_SWINUB] = VANILLA_SPECIES_SWINUB,
    [SPECIES_PILOSWINE] = VANILLA_SPECIES_PILOSWINE,
    [SPECIES_CORSOLA] = VANILLA_SPECIES_CORSOLA,
    [SPECIES_REMORAID] = VANILLA_SPECIES_REMORAID,
    [SPECIES_OCTILLERY] = VANILLA_SPECIES_OCTILLERY,
    [SPECIES_DELIBIRD] = VANILLA_SPECIES_DELIBIRD,
    [SPECIES_MANTINE] = VANILLA_SPECIES_MANTINE,
    [SPECIES_SKARMORY] = VANILLA_SPECIES_SKARMORY,
    [SPECIES_HOUNDOUR] = VANILLA_SPECIES_HOUNDOUR,
    [SPECIES_HOUNDOOM] = VANILLA_SPECIES_HOUNDOOM,
    [SPECIES_KINGDRA] = VANILLA_SPECIES_KINGDRA,
    [SPECIES_PHANPY] = VANILLA_SPECIES_PHANPY,
    [SPECIES_DONPHAN] = VANILLA_SPECIES_DONPHAN,
    [SPECIES_PORYGON2] = VANILLA_SPECIES_PORYGON2,
    [SPECIES_STANTLER] = VANILLA_SPECIES_STANTLER,
    [SPECIES_SMEARGLE] = VANILLA_SPECIES_SMEARGLE,
    [SPECIES_TYROGUE] = VANILLA_SPECIES_TYROGUE,
    [SPECIES_HITMONTOP] = VANILLA_SPECIES_HITMONTOP,
    [SPECIES_SMOOCHUM] = VANILLA_SPECIES_SMOOCHUM,
    [SPECIES_ELEKID] = VANILLA_SPECIES_ELEKID,
    [SPECIES_MAGBY] = VANILLA_SPECIES_MAGBY,
    [SPECIES_MILTANK] = VANILLA_SPECIES_MILTANK,
    [SPECIES_BLISSEY] = VANILLA_SPECIES_BLISSEY,
    [SPECIES_RAIKOU] = VANILLA_SPECIES_RAIKOU,
    [SPECIES_ENTEI] = VANILLA_SPECIES_ENTEI,
    [SPECIES_SUICUNE] = VANILLA_SPECIES_SUICUNE,
    [SPECIES_LARVITAR] = VANILLA_SPECIES_LARVITAR,
    [SPECIES_PUPITAR] = VANILLA_SPECIES_PUPITAR,
    [SPECIES_TYRANITAR] = VANILLA_SPECIES_TYRANITAR,
    [SPECIES_LUGIA] = VANILLA_SPECIES_LUGIA,
    [SPECIES_HO_OH] = VANILLA_SPECIES_HO_OH,
    [SPECIES_CELEBI] = VANILLA_SPECIES_CELEBI,
    [SPECIES_TREECKO] = VANILLA_SPECIES_TREECKO,
    [SPECIES_GROVYLE] = VANILLA_SPECIES_GROVYLE,
    [SPECIES_SCEPTILE] = VANILLA_SPECIES_SCEPTILE,
    [SPECIES_TORCHIC] = VANILLA_SPECIES_TORCHIC,
    [SPECIES_COMBUSKEN] = VANILLA_SPECIES_COMBUSKEN,
    [SPECIES_BLAZIKEN] = VANILLA_SPECIES_BLAZIKEN,
    [SPECIES_MUDKIP] = VANILLA_SPECIES_MUDKIP,
    [SPECIES_MARSHTOMP] = VANILLA_SPECIES_MARSHTOMP,
    [SPECIES_SWAMPERT] = VANILLA_SPECIES_SWAMPERT,
    [SPECIES_POOCHYENA] = VANILLA_SPECIES_POOCHYENA,
    [SPECIES_MIGHTYENA] = VANILLA_SPECIES_MIGHTYENA,
    [SPECIES_ZIGZAGOON] = VANILLA_SPECIES_ZIGZAGOON,
    [SPECIES_LINOONE] = VANILLA_SPECIES_LINOONE,
    [SPECIES_WURMPLE] = VANILLA_SPECIES_WURMPLE,
    [SPECIES_SILCOON] = VANILLA_SPECIES_SILCOON,
    [SPECIES_BEAUTIFLY] = VANILLA_SPECIES_BEAUTIFLY,
    [SPECIES_CASCOON] = VANILLA_SPECIES_CASCOON,
    [SPECIES_DUSTOX] = VANILLA_SPECIES_DUSTOX,
    [SPECIES_LOTAD] = VANILLA_SPECIES_LOTAD,
    [SPECIES_LOMBRE] = VANILLA_SPECIES_LOMBRE,
    [SPECIES_LUDICOLO] = VANILLA_SPECIES_LUDICOLO,
    [SPECIES_SEEDOT] = VANILLA_SPECIES_SEEDOT,
    [SPECIES_NUZLEAF] = VANILLA_SPECIES_NUZLEAF,
    [SPECIES_SHIFTRY] = VANILLA_SPECIES_SHIFTRY,
    [SPECIES_NINCADA] = VANILLA_SPECIES_NINCADA,
    [SPECIES_NINJASK] = VANILLA_SPECIES_NINJASK,
    [SPECIES_SHEDINJA] = VANILLA_SPECIES_SHEDINJA,
    [SPECIES_TAILLOW] = VANILLA_SPECIES_TAILLOW,
    [SPECIES_SWELLOW] = VANILLA_SPECIES_SWELLOW,
    [SPECIES_SHROOMISH] = VANILLA_SPECIES_SHROOMISH,
    [SPECIES_BRELOOM] = VANILLA_SPECIES_BRELOOM,
    [SPECIES_SPINDA] = VANILLA_SPECIES_SPINDA,
    [SPECIES_WINGULL] = VANILLA_SPECIES_WINGULL,
    [SPECIES_PELIPPER] = VANILLA_SPECIES_PELIPPER,
    [SPECIES_SURSKIT] = VANILLA_SPECIES_SURSKIT,
    [SPECIES_MASQUERAIN] = VANILLA_SPECIES_MASQUERAIN,
    [SPECIES_WAILMER] = VANILLA_SPECIES_WAILMER,
    [SPECIES_WAILORD] = VANILLA_SPECIES_WAILORD,
    [SPECIES_SKITTY] = VANILLA_SPECIES_SKITTY,
    [SPECIES_DELCATTY] = VANILLA_SPECIES_DELCATTY,
    [SPECIES_KECLEON] = VANILLA_SPECIES_KECLEON,
    [SPECIES_BALTOY] = VANILLA_SPECIES_BALTOY,
    [SPECIES_CLAYDOL] = VANILLA_SPECIES_CLAYDOL,
    [SPECIES_NOSEPASS] = VANILLA_SPECIES_NOSEPASS,
    [SPECIES_TORKOAL] = VANILLA_SPECIES_TORKOAL,
    [SPECIES_SABLEYE] = VANILLA_SPECIES_SABLEYE,
    [SPECIES_BARBOACH] = VANILLA_SPECIES_BARBOACH,
    [SPECIES_WHISCASH] = VANILLA_SPECIES_WHISCASH,
    [SPECIES_LUVDISC] = VANILLA_SPECIES_LUVDISC,
    [SPECIES_CORPHISH] = VANILLA_SPECIES_CORPHISH,
    [SPECIES_CRAWDAUNT] = VANILLA_SPECIES_CRAWDAUNT,
    [SPECIES_FEEBAS] = VANILLA_SPECIES_FEEBAS,
    [SPECIES_MILOTIC] = VANILLA_SPECIES_MILOTIC,
    [SPECIES_CARVANHA] = VANILLA_SPECIES_CARVANHA,
    [SPECIES_SHARPEDO] = VANILLA_SPECIES_SHARPEDO,
    [SPECIES_TRAPINCH] = VANILLA_SPECIES_TRAPINCH,
    [SPECIES_VIBRAVA] = VANILLA_SPECIES_VIBRAVA,
    [SPECIES_FLYGON] = VANILLA_SPECIES_FLYGON,
    [SPECIES_MAKUHITA] = VANILLA_SPECIES_MAKUHITA,
    [SPECIES_HARIYAMA] = VANILLA_SPECIES_HARIYAMA,
    [SPECIES_ELECTRIKE] = VANILLA_SPECIES_ELECTRIKE,
    [SPECIES_MANECTRIC] = VANILLA_SPECIES_MANECTRIC,
    [SPECIES_NUMEL] = VANILLA_SPECIES_NUMEL,
    [SPECIES_CAMERUPT] = VANILLA_SPECIES_CAMERUPT,
    [SPECIES_SPHEAL] = VANILLA_SPECIES_SPHEAL,
    [SPECIES_SEALEO] = VANILLA_SPECIES_SEALEO,
    [SPECIES_WALREIN] = VANILLA_SPECIES_WALREIN,
    [SPECIES_CACNEA] = VANILLA_SPECIES_CACNEA,
    [SPECIES_CACTURNE] = VANILLA_SPECIES_CACTURNE,
    [SPECIES_SNORUNT] = VANILLA_SPECIES_SNORUNT,
    [SPECIES_GLALIE] = VANILLA_SPECIES_GLALIE,
    [SPECIES_LUNATONE] = VANILLA_SPECIES_LUNATONE,
    [SPECIES_SOLROCK] = VANILLA_SPECIES_SOLROCK,
    [SPECIES_AZURILL] = VANILLA_SPECIES_AZURILL,
    [SPECIES_SPOINK] = VANILLA_SPECIES_SPOINK,
    [SPECIES_GRUMPIG] = VANILLA_SPECIES_GRUMPIG,
    [SPECIES_PLUSLE] = VANILLA_SPECIES_PLUSLE,
    [SPECIES_MINUN] = VANILLA_SPECIES_MINUN,
    [SPECIES_MAWILE] = VANILLA_SPECIES_MAWILE,
    [SPECIES_MEDITITE] = VANILLA_SPECIES_MEDITITE,
    [SPECIES_MEDICHAM] = VANILLA_SPECIES_MEDICHAM,
    [SPECIES_SWABLU] = VANILLA_SPECIES_SWABLU,
    [SPECIES_ALTARIA] = VANILLA_SPECIES_ALTARIA,
    [SPECIES_WYNAUT] = VANILLA_SPECIES_WYNAUT,
    [SPECIES_DUSKULL] = VANILLA_SPECIES_DUSKULL,
    [SPECIES_DUSCLOPS] = VANILLA_SPECIES_DUSCLOPS,
    [SPECIES_ROSELIA] = VANILLA_SPECIES_ROSELIA,
    [SPECIES_SLAKOTH] = VANILLA_SPECIES_SLAKOTH,
    [SPECIES_VIGOROTH] = VANILLA_SPECIES_VIGOROTH,
    [SPECIES_SLAKING] = VANILLA_SPECIES_SLAKING,
    [SPECIES_GULPIN] = VANILLA_SPECIES_GULPIN,
    [SPECIES_SWALOT] = VANILLA_SPECIES_SWALOT,
    [SPECIES_TROPIUS] = VANILLA_SPECIES_TROPIUS,
    [SPECIES_WHISMUR] = VANILLA_SPECIES_WHISMUR,
    [SPECIES_LOUDRED] = VANILLA_SPECIES_LOUDRED,
    [SPECIES_EXPLOUD] = VANILLA_SPECIES_EXPLOUD,
    [SPECIES_CLAMPERL] = VANILLA_SPECIES_CLAMPERL,
    [SPECIES_HUNTAIL] = VANILLA_SPECIES_HUNTAIL,
    [SPECIES_GOREBYSS] = VANILLA_SPECIES_GOREBYSS,
    [SPECIES_ABSOL] = VANILLA_SPECIES_ABSOL,
    [SPECIES_SHUPPET] = VANILLA_SPECIES_SHUPPET,
    [SPECIES_BANETTE] = VANILLA_SPECIES_BANETTE,
    [SPECIES_SEVIPER] = VANILLA_SPECIES_SEVIPER,
    [SPECIES_ZANGOOSE] = VANILLA_SPECIES_ZANGOOSE,
    [SPECIES_RELICANTH] = VANILLA_SPECIES_RELICANTH,
    [SPECIES_ARON] = VANILLA_SPECIES_ARON,
    [SPECIES_LAIRON] = VANILLA_SPECIES_LAIRON,
    [SPECIES_AGGRON] = VANILLA_SPECIES_AGGRON,
    [SPECIES_CASTFORM] = VANILLA_SPECIES_CASTFORM,
    [SPECIES_VOLBEAT] = VANILLA_SPECIES_VOLBEAT,
    [SPECIES_ILLUMISE] = VANILLA_SPECIES_ILLUMISE,
    [SPECIES_LILEEP] = VANILLA_SPECIES_LILEEP,
    [SPECIES_CRADILY] = VANILLA_SPECIES_CRADILY,
    [SPECIES_ANORITH] = VANILLA_SPECIES_ANORITH,
    [SPECIES_ARMALDO] = VANILLA_SPECIES_ARMALDO,
    [SPECIES_RALTS] = VANILLA_SPECIES_RALTS,
    [SPECIES_KIRLIA] = VANILLA_SPECIES_KIRLIA,
    [SPECIES_GARDEVOIR] = VANILLA_SPECIES_GARDEVOIR,
    [SPECIES_BAGON] = VANILLA_SPECIES_BAGON,
    [SPECIES_SHELGON] = VANILLA_SPECIES_SHELGON,
    [SPECIES_SALAMENCE] = VANILLA_SPECIES_SALAMENCE,
    [SPECIES_BELDUM] = VANILLA_SPECIES_BELDUM,
    [SPECIES_METANG] = VANILLA_SPECIES_METANG,
    [SPECIES_METAGROSS] = VANILLA_SPECIES_METAGROSS,
    [SPECIES_REGIROCK] = VANILLA_SPECIES_REGIROCK,
    [SPECIES_REGICE] = VANILLA_SPECIES_REGICE,
    [SPECIES_REGISTEEL] = VANILLA_SPECIES_REGISTEEL,
    [SPECIES_KYOGRE] = VANILLA_SPECIES_KYOGRE,
    [SPECIES_GROUDON] = VANILLA_SPECIES_GROUDON,
    [SPECIES_RAYQUAZA] = VANILLA_SPECIES_RAYQUAZA,
    [SPECIES_LATIAS] = VANILLA_SPECIES_LATIAS,
    [SPECIES_LATIOS] = VANILLA_SPECIES_LATIOS,
    [SPECIES_JIRACHI] = VANILLA_SPECIES_JIRACHI,
    [SPECIES_DEOXYS] = VANILLA_SPECIES_DEOXYS,
    [SPECIES_CHIMECHO] = VANILLA_SPECIES_CHIMECHO,
};

static const u16 sVanillaSpeciesToExpansion[] =
{
  	[VANILLA_SPECIES_NONE] = SPECIES_NONE,
	[VANILLA_SPECIES_BULBASAUR] = SPECIES_BULBASAUR,
	[VANILLA_SPECIES_IVYSAUR] = SPECIES_IVYSAUR,
	[VANILLA_SPECIES_VENUSAUR] = SPECIES_VENUSAUR,
	[VANILLA_SPECIES_CHARMANDER] = SPECIES_CHARMANDER,
	[VANILLA_SPECIES_CHARMELEON] = SPECIES_CHARMELEON,
	[VANILLA_SPECIES_CHARIZARD] = SPECIES_CHARIZARD,
	[VANILLA_SPECIES_SQUIRTLE] = SPECIES_SQUIRTLE,
	[VANILLA_SPECIES_WARTORTLE] = SPECIES_WARTORTLE,
	[VANILLA_SPECIES_BLASTOISE] = SPECIES_BLASTOISE,
	[VANILLA_SPECIES_CATERPIE] = SPECIES_CATERPIE,
	[VANILLA_SPECIES_METAPOD] = SPECIES_METAPOD,
	[VANILLA_SPECIES_BUTTERFREE] = SPECIES_BUTTERFREE,
	[VANILLA_SPECIES_WEEDLE] = SPECIES_WEEDLE,
	[VANILLA_SPECIES_KAKUNA] = SPECIES_KAKUNA,
	[VANILLA_SPECIES_BEEDRILL] = SPECIES_BEEDRILL,
	[VANILLA_SPECIES_PIDGEY] = SPECIES_PIDGEY,
	[VANILLA_SPECIES_PIDGEOTTO] = SPECIES_PIDGEOTTO,
	[VANILLA_SPECIES_PIDGEOT] = SPECIES_PIDGEOT,
	[VANILLA_SPECIES_RATTATA] = SPECIES_RATTATA,
	[VANILLA_SPECIES_RATICATE] = SPECIES_RATICATE,
	[VANILLA_SPECIES_SPEAROW] = SPECIES_SPEAROW,
	[VANILLA_SPECIES_FEAROW] = SPECIES_FEAROW,
	[VANILLA_SPECIES_EKANS] = SPECIES_EKANS,
	[VANILLA_SPECIES_ARBOK] = SPECIES_ARBOK,
	[VANILLA_SPECIES_PIKACHU] = SPECIES_PIKACHU,
	[VANILLA_SPECIES_RAICHU] = SPECIES_RAICHU,
	[VANILLA_SPECIES_SANDSHREW] = SPECIES_SANDSHREW,
	[VANILLA_SPECIES_SANDSLASH] = SPECIES_SANDSLASH,
	[VANILLA_SPECIES_NIDORAN_F] = SPECIES_NIDORAN_F,
	[VANILLA_SPECIES_NIDORINA] = SPECIES_NIDORINA,
	[VANILLA_SPECIES_NIDOQUEEN] = SPECIES_NIDOQUEEN,
	[VANILLA_SPECIES_NIDORAN_M] = SPECIES_NIDORAN_M,
	[VANILLA_SPECIES_NIDORINO] = SPECIES_NIDORINO,
	[VANILLA_SPECIES_NIDOKING] = SPECIES_NIDOKING,
	[VANILLA_SPECIES_CLEFAIRY] = SPECIES_CLEFAIRY,
	[VANILLA_SPECIES_CLEFABLE] = SPECIES_CLEFABLE,
	[VANILLA_SPECIES_VULPIX] = SPECIES_VULPIX,
	[VANILLA_SPECIES_NINETALES] = SPECIES_NINETALES,
	[VANILLA_SPECIES_JIGGLYPUFF] = SPECIES_JIGGLYPUFF,
	[VANILLA_SPECIES_WIGGLYTUFF] = SPECIES_WIGGLYTUFF,
	[VANILLA_SPECIES_ZUBAT] = SPECIES_ZUBAT,
	[VANILLA_SPECIES_GOLBAT] = SPECIES_GOLBAT,
	[VANILLA_SPECIES_ODDISH] = SPECIES_ODDISH,
	[VANILLA_SPECIES_GLOOM] = SPECIES_GLOOM,
	[VANILLA_SPECIES_VILEPLUME] = SPECIES_VILEPLUME,
	[VANILLA_SPECIES_PARAS] = SPECIES_PARAS,
	[VANILLA_SPECIES_PARASECT] = SPECIES_PARASECT,
	[VANILLA_SPECIES_VENONAT] = SPECIES_VENONAT,
	[VANILLA_SPECIES_VENOMOTH] = SPECIES_VENOMOTH,
	[VANILLA_SPECIES_DIGLETT] = SPECIES_DIGLETT,
	[VANILLA_SPECIES_DUGTRIO] = SPECIES_DUGTRIO,
	[VANILLA_SPECIES_MEOWTH] = SPECIES_MEOWTH,
	[VANILLA_SPECIES_PERSIAN] = SPECIES_PERSIAN,
	[VANILLA_SPECIES_PSYDUCK] = SPECIES_PSYDUCK,
	[VANILLA_SPECIES_GOLDUCK] = SPECIES_GOLDUCK,
	[VANILLA_SPECIES_MANKEY] = SPECIES_MANKEY,
	[VANILLA_SPECIES_PRIMEAPE] = SPECIES_PRIMEAPE,
	[VANILLA_SPECIES_GROWLITHE] = SPECIES_GROWLITHE,
	[VANILLA_SPECIES_ARCANINE] = SPECIES_ARCANINE,
	[VANILLA_SPECIES_POLIWAG] = SPECIES_POLIWAG,
	[VANILLA_SPECIES_POLIWHIRL] = SPECIES_POLIWHIRL,
	[VANILLA_SPECIES_POLIWRATH] = SPECIES_POLIWRATH,
	[VANILLA_SPECIES_ABRA] = SPECIES_ABRA,
	[VANILLA_SPECIES_KADABRA] = SPECIES_KADABRA,
	[VANILLA_SPECIES_ALAKAZAM] = SPECIES_ALAKAZAM,
	[VANILLA_SPECIES_MACHOP] = SPECIES_MACHOP,
	[VANILLA_SPECIES_MACHOKE] = SPECIES_MACHOKE,
	[VANILLA_SPECIES_MACHAMP] = SPECIES_MACHAMP,
	[VANILLA_SPECIES_BELLSPROUT] = SPECIES_BELLSPROUT,
	[VANILLA_SPECIES_WEEPINBELL] = SPECIES_WEEPINBELL,
	[VANILLA_SPECIES_VICTREEBEL] = SPECIES_VICTREEBEL,
	[VANILLA_SPECIES_TENTACOOL] = SPECIES_TENTACOOL,
	[VANILLA_SPECIES_TENTACRUEL] = SPECIES_TENTACRUEL,
	[VANILLA_SPECIES_GEODUDE] = SPECIES_GEODUDE,
	[VANILLA_SPECIES_GRAVELER] = SPECIES_GRAVELER,
	[VANILLA_SPECIES_GOLEM] = SPECIES_GOLEM,
	[VANILLA_SPECIES_PONYTA] = SPECIES_PONYTA,
	[VANILLA_SPECIES_RAPIDASH] = SPECIES_RAPIDASH,
	[VANILLA_SPECIES_SLOWPOKE] = SPECIES_SLOWPOKE,
	[VANILLA_SPECIES_SLOWBRO] = SPECIES_SLOWBRO,
	[VANILLA_SPECIES_MAGNEMITE] = SPECIES_MAGNEMITE,
	[VANILLA_SPECIES_MAGNETON] = SPECIES_MAGNETON,
	[VANILLA_SPECIES_FARFETCHD] = SPECIES_FARFETCHD,
	[VANILLA_SPECIES_DODUO] = SPECIES_DODUO,
	[VANILLA_SPECIES_DODRIO] = SPECIES_DODRIO,
	[VANILLA_SPECIES_SEEL] = SPECIES_SEEL,
	[VANILLA_SPECIES_DEWGONG] = SPECIES_DEWGONG,
	[VANILLA_SPECIES_GRIMER] = SPECIES_GRIMER,
	[VANILLA_SPECIES_MUK] = SPECIES_MUK,
	[VANILLA_SPECIES_SHELLDER] = SPECIES_SHELLDER,
	[VANILLA_SPECIES_CLOYSTER] = SPECIES_CLOYSTER,
	[VANILLA_SPECIES_GASTLY] = SPECIES_GASTLY,
	[VANILLA_SPECIES_HAUNTER] = SPECIES_HAUNTER,
	[VANILLA_SPECIES_GENGAR] = SPECIES_GENGAR,
	[VANILLA_SPECIES_ONIX] = SPECIES_ONIX,
	[VANILLA_SPECIES_DROWZEE] = SPECIES_DROWZEE,
	[VANILLA_SPECIES_HYPNO] = SPECIES_HYPNO,
	[VANILLA_SPECIES_KRABBY] = SPECIES_KRABBY,
	[VANILLA_SPECIES_KINGLER] = SPECIES_KINGLER,
	[VANILLA_SPECIES_VOLTORB] = SPECIES_VOLTORB,
	[VANILLA_SPECIES_ELECTRODE] = SPECIES_ELECTRODE,
	[VANILLA_SPECIES_EXEGGCUTE] = SPECIES_EXEGGCUTE,
	[VANILLA_SPECIES_EXEGGUTOR] = SPECIES_EXEGGUTOR,
	[VANILLA_SPECIES_CUBONE] = SPECIES_CUBONE,
	[VANILLA_SPECIES_MAROWAK] = SPECIES_MAROWAK,
	[VANILLA_SPECIES_HITMONLEE] = SPECIES_HITMONLEE,
	[VANILLA_SPECIES_HITMONCHAN] = SPECIES_HITMONCHAN,
	[VANILLA_SPECIES_LICKITUNG] = SPECIES_LICKITUNG,
	[VANILLA_SPECIES_KOFFING] = SPECIES_KOFFING,
	[VANILLA_SPECIES_WEEZING] = SPECIES_WEEZING,
	[VANILLA_SPECIES_RHYHORN] = SPECIES_RHYHORN,
	[VANILLA_SPECIES_RHYDON] = SPECIES_RHYDON,
	[VANILLA_SPECIES_CHANSEY] = SPECIES_CHANSEY,
	[VANILLA_SPECIES_TANGELA] = SPECIES_TANGELA,
	[VANILLA_SPECIES_KANGASKHAN] = SPECIES_KANGASKHAN,
	[VANILLA_SPECIES_HORSEA] = SPECIES_HORSEA,
	[VANILLA_SPECIES_SEADRA] = SPECIES_SEADRA,
	[VANILLA_SPECIES_GOLDEEN] = SPECIES_GOLDEEN,
	[VANILLA_SPECIES_SEAKING] = SPECIES_SEAKING,
	[VANILLA_SPECIES_STARYU] = SPECIES_STARYU,
	[VANILLA_SPECIES_STARMIE] = SPECIES_STARMIE,
	[VANILLA_SPECIES_MR_MIME] = SPECIES_MR_MIME,
	[VANILLA_SPECIES_SCYTHER] = SPECIES_SCYTHER,
	[VANILLA_SPECIES_JYNX] = SPECIES_JYNX,
	[VANILLA_SPECIES_ELECTABUZZ] = SPECIES_ELECTABUZZ,
	[VANILLA_SPECIES_MAGMAR] = SPECIES_MAGMAR,
	[VANILLA_SPECIES_PINSIR] = SPECIES_PINSIR,
	[VANILLA_SPECIES_TAUROS] = SPECIES_TAUROS,
	[VANILLA_SPECIES_MAGIKARP] = SPECIES_MAGIKARP,
	[VANILLA_SPECIES_GYARADOS] = SPECIES_GYARADOS,
	[VANILLA_SPECIES_LAPRAS] = SPECIES_LAPRAS,
	[VANILLA_SPECIES_DITTO] = SPECIES_DITTO,
	[VANILLA_SPECIES_EEVEE] = SPECIES_EEVEE,
	[VANILLA_SPECIES_VAPOREON] = SPECIES_VAPOREON,
	[VANILLA_SPECIES_JOLTEON] = SPECIES_JOLTEON,
	[VANILLA_SPECIES_FLAREON] = SPECIES_FLAREON,
	[VANILLA_SPECIES_PORYGON] = SPECIES_PORYGON,
	[VANILLA_SPECIES_OMANYTE] = SPECIES_OMANYTE,
	[VANILLA_SPECIES_OMASTAR] = SPECIES_OMASTAR,
	[VANILLA_SPECIES_KABUTO] = SPECIES_KABUTO,
	[VANILLA_SPECIES_KABUTOPS] = SPECIES_KABUTOPS,
	[VANILLA_SPECIES_AERODACTYL] = SPECIES_AERODACTYL,
	[VANILLA_SPECIES_SNORLAX] = SPECIES_SNORLAX,
	[VANILLA_SPECIES_ARTICUNO] = SPECIES_ARTICUNO,
	[VANILLA_SPECIES_ZAPDOS] = SPECIES_ZAPDOS,
	[VANILLA_SPECIES_MOLTRES] = SPECIES_MOLTRES,
	[VANILLA_SPECIES_DRATINI] = SPECIES_DRATINI,
	[VANILLA_SPECIES_DRAGONAIR] = SPECIES_DRAGONAIR,
	[VANILLA_SPECIES_DRAGONITE] = SPECIES_DRAGONITE,
	[VANILLA_SPECIES_MEWTWO] = SPECIES_MEWTWO,
	[VANILLA_SPECIES_MEW] = SPECIES_MEW,
	[VANILLA_SPECIES_CHIKORITA] = SPECIES_CHIKORITA,
	[VANILLA_SPECIES_BAYLEEF] = SPECIES_BAYLEEF,
	[VANILLA_SPECIES_MEGANIUM] = SPECIES_MEGANIUM,
	[VANILLA_SPECIES_CYNDAQUIL] = SPECIES_CYNDAQUIL,
	[VANILLA_SPECIES_QUILAVA] = SPECIES_QUILAVA,
	[VANILLA_SPECIES_TYPHLOSION] = SPECIES_TYPHLOSION,
	[VANILLA_SPECIES_TOTODILE] = SPECIES_TOTODILE,
	[VANILLA_SPECIES_CROCONAW] = SPECIES_CROCONAW,
	[VANILLA_SPECIES_FERALIGATR] = SPECIES_FERALIGATR,
	[VANILLA_SPECIES_SENTRET] = SPECIES_SENTRET,
	[VANILLA_SPECIES_FURRET] = SPECIES_FURRET,
	[VANILLA_SPECIES_HOOTHOOT] = SPECIES_HOOTHOOT,
	[VANILLA_SPECIES_NOCTOWL] = SPECIES_NOCTOWL,
	[VANILLA_SPECIES_LEDYBA] = SPECIES_LEDYBA,
	[VANILLA_SPECIES_LEDIAN] = SPECIES_LEDIAN,
	[VANILLA_SPECIES_SPINARAK] = SPECIES_SPINARAK,
	[VANILLA_SPECIES_ARIADOS] = SPECIES_ARIADOS,
	[VANILLA_SPECIES_CROBAT] = SPECIES_CROBAT,
	[VANILLA_SPECIES_CHINCHOU] = SPECIES_CHINCHOU,
	[VANILLA_SPECIES_LANTURN] = SPECIES_LANTURN,
	[VANILLA_SPECIES_PICHU] = SPECIES_PICHU,
	[VANILLA_SPECIES_CLEFFA] = SPECIES_CLEFFA,
	[VANILLA_SPECIES_IGGLYBUFF] = SPECIES_IGGLYBUFF,
	[VANILLA_SPECIES_TOGEPI] = SPECIES_TOGEPI,
	[VANILLA_SPECIES_TOGETIC] = SPECIES_TOGETIC,
	[VANILLA_SPECIES_NATU] = SPECIES_NATU,
	[VANILLA_SPECIES_XATU] = SPECIES_XATU,
	[VANILLA_SPECIES_MAREEP] = SPECIES_MAREEP,
	[VANILLA_SPECIES_FLAAFFY] = SPECIES_FLAAFFY,
	[VANILLA_SPECIES_AMPHAROS] = SPECIES_AMPHAROS,
	[VANILLA_SPECIES_BELLOSSOM] = SPECIES_BELLOSSOM,
	[VANILLA_SPECIES_MARILL] = SPECIES_MARILL,
	[VANILLA_SPECIES_AZUMARILL] = SPECIES_AZUMARILL,
	[VANILLA_SPECIES_SUDOWOODO] = SPECIES_SUDOWOODO,
	[VANILLA_SPECIES_POLITOED] = SPECIES_POLITOED,
	[VANILLA_SPECIES_HOPPIP] = SPECIES_HOPPIP,
	[VANILLA_SPECIES_SKIPLOOM] = SPECIES_SKIPLOOM,
	[VANILLA_SPECIES_JUMPLUFF] = SPECIES_JUMPLUFF,
	[VANILLA_SPECIES_AIPOM] = SPECIES_AIPOM,
	[VANILLA_SPECIES_SUNKERN] = SPECIES_SUNKERN,
	[VANILLA_SPECIES_SUNFLORA] = SPECIES_SUNFLORA,
	[VANILLA_SPECIES_YANMA] = SPECIES_YANMA,
	[VANILLA_SPECIES_WOOPER] = SPECIES_WOOPER,
	[VANILLA_SPECIES_QUAGSIRE] = SPECIES_QUAGSIRE,
	[VANILLA_SPECIES_ESPEON] = SPECIES_ESPEON,
	[VANILLA_SPECIES_UMBREON] = SPECIES_UMBREON,
	[VANILLA_SPECIES_MURKROW] = SPECIES_MURKROW,
	[VANILLA_SPECIES_SLOWKING] = SPECIES_SLOWKING,
	[VANILLA_SPECIES_MISDREAVUS] = SPECIES_MISDREAVUS,
	[VANILLA_SPECIES_UNOWN] = SPECIES_UNOWN,
	[VANILLA_SPECIES_WOBBUFFET] = SPECIES_WOBBUFFET,
	[VANILLA_SPECIES_GIRAFARIG] = SPECIES_GIRAFARIG,
	[VANILLA_SPECIES_PINECO] = SPECIES_PINECO,
	[VANILLA_SPECIES_FORRETRESS] = SPECIES_FORRETRESS,
	[VANILLA_SPECIES_DUNSPARCE] = SPECIES_DUNSPARCE,
	[VANILLA_SPECIES_GLIGAR] = SPECIES_GLIGAR,
	[VANILLA_SPECIES_STEELIX] = SPECIES_STEELIX,
	[VANILLA_SPECIES_SNUBBULL] = SPECIES_SNUBBULL,
	[VANILLA_SPECIES_GRANBULL] = SPECIES_GRANBULL,
	[VANILLA_SPECIES_QWILFISH] = SPECIES_QWILFISH,
	[VANILLA_SPECIES_SCIZOR] = SPECIES_SCIZOR,
	[VANILLA_SPECIES_SHUCKLE] = SPECIES_SHUCKLE,
	[VANILLA_SPECIES_HERACROSS] = SPECIES_HERACROSS,
	[VANILLA_SPECIES_SNEASEL] = SPECIES_SNEASEL,
	[VANILLA_SPECIES_TEDDIURSA] = SPECIES_TEDDIURSA,
	[VANILLA_SPECIES_URSARING] = SPECIES_URSARING,
	[VANILLA_SPECIES_SLUGMA] = SPECIES_SLUGMA,
	[VANILLA_SPECIES_MAGCARGO] = SPECIES_MAGCARGO,
	[VANILLA_SPECIES_SWINUB] = SPECIES_SWINUB,
	[VANILLA_SPECIES_PILOSWINE] = SPECIES_PILOSWINE,
	[VANILLA_SPECIES_CORSOLA] = SPECIES_CORSOLA,
	[VANILLA_SPECIES_REMORAID] = SPECIES_REMORAID,
	[VANILLA_SPECIES_OCTILLERY] = SPECIES_OCTILLERY,
	[VANILLA_SPECIES_DELIBIRD] = SPECIES_DELIBIRD,
	[VANILLA_SPECIES_MANTINE] = SPECIES_MANTINE,
	[VANILLA_SPECIES_SKARMORY] = SPECIES_SKARMORY,
	[VANILLA_SPECIES_HOUNDOUR] = SPECIES_HOUNDOUR,
	[VANILLA_SPECIES_HOUNDOOM] = SPECIES_HOUNDOOM,
	[VANILLA_SPECIES_KINGDRA] = SPECIES_KINGDRA,
	[VANILLA_SPECIES_PHANPY] = SPECIES_PHANPY,
	[VANILLA_SPECIES_DONPHAN] = SPECIES_DONPHAN,
	[VANILLA_SPECIES_PORYGON2] = SPECIES_PORYGON2,
	[VANILLA_SPECIES_STANTLER] = SPECIES_STANTLER,
	[VANILLA_SPECIES_SMEARGLE] = SPECIES_SMEARGLE,
	[VANILLA_SPECIES_TYROGUE] = SPECIES_TYROGUE,
	[VANILLA_SPECIES_HITMONTOP] = SPECIES_HITMONTOP,
	[VANILLA_SPECIES_SMOOCHUM] = SPECIES_SMOOCHUM,
	[VANILLA_SPECIES_ELEKID] = SPECIES_ELEKID,
	[VANILLA_SPECIES_MAGBY] = SPECIES_MAGBY,
	[VANILLA_SPECIES_MILTANK] = SPECIES_MILTANK,
	[VANILLA_SPECIES_BLISSEY] = SPECIES_BLISSEY,
	[VANILLA_SPECIES_RAIKOU] = SPECIES_RAIKOU,
	[VANILLA_SPECIES_ENTEI] = SPECIES_ENTEI,
	[VANILLA_SPECIES_SUICUNE] = SPECIES_SUICUNE,
	[VANILLA_SPECIES_LARVITAR] = SPECIES_LARVITAR,
	[VANILLA_SPECIES_PUPITAR] = SPECIES_PUPITAR,
	[VANILLA_SPECIES_TYRANITAR] = SPECIES_TYRANITAR,
	[VANILLA_SPECIES_LUGIA] = SPECIES_LUGIA,
	[VANILLA_SPECIES_HO_OH] = SPECIES_HO_OH,
	[VANILLA_SPECIES_CELEBI] = SPECIES_CELEBI,
	[VANILLA_SPECIES_TREECKO] = SPECIES_TREECKO,
	[VANILLA_SPECIES_GROVYLE] = SPECIES_GROVYLE,
	[VANILLA_SPECIES_SCEPTILE] = SPECIES_SCEPTILE,
	[VANILLA_SPECIES_TORCHIC] = SPECIES_TORCHIC,
	[VANILLA_SPECIES_COMBUSKEN] = SPECIES_COMBUSKEN,
	[VANILLA_SPECIES_BLAZIKEN] = SPECIES_BLAZIKEN,
	[VANILLA_SPECIES_MUDKIP] = SPECIES_MUDKIP,
	[VANILLA_SPECIES_MARSHTOMP] = SPECIES_MARSHTOMP,
	[VANILLA_SPECIES_SWAMPERT] = SPECIES_SWAMPERT,
	[VANILLA_SPECIES_POOCHYENA] = SPECIES_POOCHYENA,
	[VANILLA_SPECIES_MIGHTYENA] = SPECIES_MIGHTYENA,
	[VANILLA_SPECIES_ZIGZAGOON] = SPECIES_ZIGZAGOON,
	[VANILLA_SPECIES_LINOONE] = SPECIES_LINOONE,
	[VANILLA_SPECIES_WURMPLE] = SPECIES_WURMPLE,
	[VANILLA_SPECIES_SILCOON] = SPECIES_SILCOON,
	[VANILLA_SPECIES_BEAUTIFLY] = SPECIES_BEAUTIFLY,
	[VANILLA_SPECIES_CASCOON] = SPECIES_CASCOON,
	[VANILLA_SPECIES_DUSTOX] = SPECIES_DUSTOX,
	[VANILLA_SPECIES_LOTAD] = SPECIES_LOTAD,
	[VANILLA_SPECIES_LOMBRE] = SPECIES_LOMBRE,
	[VANILLA_SPECIES_LUDICOLO] = SPECIES_LUDICOLO,
	[VANILLA_SPECIES_SEEDOT] = SPECIES_SEEDOT,
	[VANILLA_SPECIES_NUZLEAF] = SPECIES_NUZLEAF,
	[VANILLA_SPECIES_SHIFTRY] = SPECIES_SHIFTRY,
	[VANILLA_SPECIES_NINCADA] = SPECIES_NINCADA,
	[VANILLA_SPECIES_NINJASK] = SPECIES_NINJASK,
	[VANILLA_SPECIES_SHEDINJA] = SPECIES_SHEDINJA,
	[VANILLA_SPECIES_TAILLOW] = SPECIES_TAILLOW,
	[VANILLA_SPECIES_SWELLOW] = SPECIES_SWELLOW,
	[VANILLA_SPECIES_SHROOMISH] = SPECIES_SHROOMISH,
	[VANILLA_SPECIES_BRELOOM] = SPECIES_BRELOOM,
	[VANILLA_SPECIES_SPINDA] = SPECIES_SPINDA,
	[VANILLA_SPECIES_WINGULL] = SPECIES_WINGULL,
	[VANILLA_SPECIES_PELIPPER] = SPECIES_PELIPPER,
	[VANILLA_SPECIES_SURSKIT] = SPECIES_SURSKIT,
	[VANILLA_SPECIES_MASQUERAIN] = SPECIES_MASQUERAIN,
	[VANILLA_SPECIES_WAILMER] = SPECIES_WAILMER,
	[VANILLA_SPECIES_WAILORD] = SPECIES_WAILORD,
	[VANILLA_SPECIES_SKITTY] = SPECIES_SKITTY,
	[VANILLA_SPECIES_DELCATTY] = SPECIES_DELCATTY,
	[VANILLA_SPECIES_KECLEON] = SPECIES_KECLEON,
	[VANILLA_SPECIES_BALTOY] = SPECIES_BALTOY,
	[VANILLA_SPECIES_CLAYDOL] = SPECIES_CLAYDOL,
	[VANILLA_SPECIES_NOSEPASS] = SPECIES_NOSEPASS,
	[VANILLA_SPECIES_TORKOAL] = SPECIES_TORKOAL,
	[VANILLA_SPECIES_SABLEYE] = SPECIES_SABLEYE,
	[VANILLA_SPECIES_BARBOACH] = SPECIES_BARBOACH,
	[VANILLA_SPECIES_WHISCASH] = SPECIES_WHISCASH,
	[VANILLA_SPECIES_LUVDISC] = SPECIES_LUVDISC,
	[VANILLA_SPECIES_CORPHISH] = SPECIES_CORPHISH,
	[VANILLA_SPECIES_CRAWDAUNT] = SPECIES_CRAWDAUNT,
	[VANILLA_SPECIES_FEEBAS] = SPECIES_FEEBAS,
	[VANILLA_SPECIES_MILOTIC] = SPECIES_MILOTIC,
	[VANILLA_SPECIES_CARVANHA] = SPECIES_CARVANHA,
	[VANILLA_SPECIES_SHARPEDO] = SPECIES_SHARPEDO,
	[VANILLA_SPECIES_TRAPINCH] = SPECIES_TRAPINCH,
	[VANILLA_SPECIES_VIBRAVA] = SPECIES_VIBRAVA,
	[VANILLA_SPECIES_FLYGON] = SPECIES_FLYGON,
	[VANILLA_SPECIES_MAKUHITA] = SPECIES_MAKUHITA,
	[VANILLA_SPECIES_HARIYAMA] = SPECIES_HARIYAMA,
	[VANILLA_SPECIES_ELECTRIKE] = SPECIES_ELECTRIKE,
	[VANILLA_SPECIES_MANECTRIC] = SPECIES_MANECTRIC,
	[VANILLA_SPECIES_NUMEL] = SPECIES_NUMEL,
	[VANILLA_SPECIES_CAMERUPT] = SPECIES_CAMERUPT,
	[VANILLA_SPECIES_SPHEAL] = SPECIES_SPHEAL,
	[VANILLA_SPECIES_SEALEO] = SPECIES_SEALEO,
	[VANILLA_SPECIES_WALREIN] = SPECIES_WALREIN,
	[VANILLA_SPECIES_CACNEA] = SPECIES_CACNEA,
	[VANILLA_SPECIES_CACTURNE] = SPECIES_CACTURNE,
	[VANILLA_SPECIES_SNORUNT] = SPECIES_SNORUNT,
	[VANILLA_SPECIES_GLALIE] = SPECIES_GLALIE,
	[VANILLA_SPECIES_LUNATONE] = SPECIES_LUNATONE,
	[VANILLA_SPECIES_SOLROCK] = SPECIES_SOLROCK,
	[VANILLA_SPECIES_AZURILL] = SPECIES_AZURILL,
	[VANILLA_SPECIES_SPOINK] = SPECIES_SPOINK,
	[VANILLA_SPECIES_GRUMPIG] = SPECIES_GRUMPIG,
	[VANILLA_SPECIES_PLUSLE] = SPECIES_PLUSLE,
	[VANILLA_SPECIES_MINUN] = SPECIES_MINUN,
	[VANILLA_SPECIES_MAWILE] = SPECIES_MAWILE,
	[VANILLA_SPECIES_MEDITITE] = SPECIES_MEDITITE,
	[VANILLA_SPECIES_MEDICHAM] = SPECIES_MEDICHAM,
	[VANILLA_SPECIES_SWABLU] = SPECIES_SWABLU,
	[VANILLA_SPECIES_ALTARIA] = SPECIES_ALTARIA,
	[VANILLA_SPECIES_WYNAUT] = SPECIES_WYNAUT,
	[VANILLA_SPECIES_DUSKULL] = SPECIES_DUSKULL,
	[VANILLA_SPECIES_DUSCLOPS] = SPECIES_DUSCLOPS,
	[VANILLA_SPECIES_ROSELIA] = SPECIES_ROSELIA,
	[VANILLA_SPECIES_SLAKOTH] = SPECIES_SLAKOTH,
	[VANILLA_SPECIES_VIGOROTH] = SPECIES_VIGOROTH,
	[VANILLA_SPECIES_SLAKING] = SPECIES_SLAKING,
	[VANILLA_SPECIES_GULPIN] = SPECIES_GULPIN,
	[VANILLA_SPECIES_SWALOT] = SPECIES_SWALOT,
	[VANILLA_SPECIES_TROPIUS] = SPECIES_TROPIUS,
	[VANILLA_SPECIES_WHISMUR] = SPECIES_WHISMUR,
	[VANILLA_SPECIES_LOUDRED] = SPECIES_LOUDRED,
	[VANILLA_SPECIES_EXPLOUD] = SPECIES_EXPLOUD,
	[VANILLA_SPECIES_CLAMPERL] = SPECIES_CLAMPERL,
	[VANILLA_SPECIES_HUNTAIL] = SPECIES_HUNTAIL,
	[VANILLA_SPECIES_GOREBYSS] = SPECIES_GOREBYSS,
	[VANILLA_SPECIES_ABSOL] = SPECIES_ABSOL,
	[VANILLA_SPECIES_SHUPPET] = SPECIES_SHUPPET,
	[VANILLA_SPECIES_BANETTE] = SPECIES_BANETTE,
	[VANILLA_SPECIES_SEVIPER] = SPECIES_SEVIPER,
	[VANILLA_SPECIES_ZANGOOSE] = SPECIES_ZANGOOSE,
	[VANILLA_SPECIES_RELICANTH] = SPECIES_RELICANTH,
	[VANILLA_SPECIES_ARON] = SPECIES_ARON,
	[VANILLA_SPECIES_LAIRON] = SPECIES_LAIRON,
	[VANILLA_SPECIES_AGGRON] = SPECIES_AGGRON,
	[VANILLA_SPECIES_CASTFORM] = SPECIES_CASTFORM,
	[VANILLA_SPECIES_VOLBEAT] = SPECIES_VOLBEAT,
	[VANILLA_SPECIES_ILLUMISE] = SPECIES_ILLUMISE,
	[VANILLA_SPECIES_LILEEP] = SPECIES_LILEEP,
	[VANILLA_SPECIES_CRADILY] = SPECIES_CRADILY,
	[VANILLA_SPECIES_ANORITH] = SPECIES_ANORITH,
	[VANILLA_SPECIES_ARMALDO] = SPECIES_ARMALDO,
	[VANILLA_SPECIES_RALTS] = SPECIES_RALTS,
	[VANILLA_SPECIES_KIRLIA] = SPECIES_KIRLIA,
	[VANILLA_SPECIES_GARDEVOIR] = SPECIES_GARDEVOIR,
	[VANILLA_SPECIES_BAGON] = SPECIES_BAGON,
	[VANILLA_SPECIES_SHELGON] = SPECIES_SHELGON,
	[VANILLA_SPECIES_SALAMENCE] = SPECIES_SALAMENCE,
	[VANILLA_SPECIES_BELDUM] = SPECIES_BELDUM,
	[VANILLA_SPECIES_METANG] = SPECIES_METANG,
	[VANILLA_SPECIES_METAGROSS] = SPECIES_METAGROSS,
	[VANILLA_SPECIES_REGIROCK] = SPECIES_REGIROCK,
	[VANILLA_SPECIES_REGICE] = SPECIES_REGICE,
	[VANILLA_SPECIES_REGISTEEL] = SPECIES_REGISTEEL,
	[VANILLA_SPECIES_KYOGRE] = SPECIES_KYOGRE,
	[VANILLA_SPECIES_GROUDON] = SPECIES_GROUDON,
	[VANILLA_SPECIES_RAYQUAZA] = SPECIES_RAYQUAZA,
	[VANILLA_SPECIES_LATIAS] = SPECIES_LATIAS,
	[VANILLA_SPECIES_LATIOS] = SPECIES_LATIOS,
	[VANILLA_SPECIES_JIRACHI] = SPECIES_JIRACHI,
	[VANILLA_SPECIES_DEOXYS] = SPECIES_DEOXYS,
	[VANILLA_SPECIES_CHIMECHO] = SPECIES_CHIMECHO,
	[VANILLA_SPECIES_EGG] = SPECIES_EGG,
};

static const u8 sVanillaDeoxysBaseStats[] =
{
    [STAT_HP]    = 50,
    [STAT_ATK]   = 95,
    [STAT_DEF]   = 90,
    [STAT_SPEED] = 180,
    [STAT_SPATK] = 95,
    [STAT_SPDEF] = 90,
};

// Code
s32 SpeciesExpansionToVanilla(s32 speciesExpansion)
{
    s32 speciesVanilla;

    if (speciesExpansion == SPECIES_EGG)
        speciesVanilla = VANILLA_SPECIES_EGG;
    // Must be gen3 species only
    else if (speciesExpansion >= SPECIES_TURTWIG)
        speciesVanilla = -1; // Invalid
    else
        speciesVanilla = sExpansionSpeciesToVanilla[speciesExpansion];

    return speciesVanilla;
}

s32 SpeciesVanillaToExpansion(s32 speciesVanilla)
{
    if (speciesVanilla >= VANILLA_NUM_SPECIES)
        return -1;

    return sVanillaSpeciesToExpansion[speciesVanilla];
}

static void Vanilla_EncryptBoxMon(struct VanillaBoxPokemon *boxMon)
{
    u32 i;
    for (i = 0; i < ARRAY_COUNT(boxMon->secure.raw); i++)
    {
        boxMon->secure.raw[i] ^= boxMon->personality;
        boxMon->secure.raw[i] ^= boxMon->otId;
    }
}

static void Vanilla_DecryptBoxMon(struct VanillaBoxPokemon *boxMon)
{
    u32 i;
    for (i = 0; i < ARRAY_COUNT(boxMon->secure.raw); i++)
    {
        boxMon->secure.raw[i] ^= boxMon->otId;
        boxMon->secure.raw[i] ^= boxMon->personality;
    }
}

#define SUBSTRUCT_CASE(n, v1, v2, v3, v4)                               \
case n:                                                                 \
    {                                                                   \
    UNUSED union VanillaPokemonSubstruct *substructs0 = boxMon->secure.substructs;    \
    UNUSED union VanillaPokemonSubstruct *substructs1 = boxMon->secure.substructs;    \
    UNUSED union VanillaPokemonSubstruct *substructs2 = boxMon->secure.substructs;    \
    UNUSED union VanillaPokemonSubstruct *substructs3 = boxMon->secure.substructs;    \
    UNUSED union VanillaPokemonSubstruct *substructs4 = boxMon->secure.substructs;    \
    UNUSED union VanillaPokemonSubstruct *substructs5 = boxMon->secure.substructs;    \
    UNUSED union VanillaPokemonSubstruct *substructs6 = boxMon->secure.substructs;    \
    UNUSED union VanillaPokemonSubstruct *substructs7 = boxMon->secure.substructs;    \
    UNUSED union VanillaPokemonSubstruct *substructs8 = boxMon->secure.substructs;    \
    UNUSED union VanillaPokemonSubstruct *substructs9 = boxMon->secure.substructs;    \
    UNUSED union VanillaPokemonSubstruct *substructs10 = boxMon->secure.substructs;   \
    UNUSED union VanillaPokemonSubstruct *substructs11 = boxMon->secure.substructs;   \
    UNUSED union VanillaPokemonSubstruct *substructs12 = boxMon->secure.substructs;   \
    UNUSED union VanillaPokemonSubstruct *substructs13 = boxMon->secure.substructs;   \
    UNUSED union VanillaPokemonSubstruct *substructs14 = boxMon->secure.substructs;   \
    UNUSED union VanillaPokemonSubstruct *substructs15 = boxMon->secure.substructs;   \
    UNUSED union VanillaPokemonSubstruct *substructs16 = boxMon->secure.substructs;   \
    UNUSED union VanillaPokemonSubstruct *substructs17 = boxMon->secure.substructs;   \
    UNUSED union VanillaPokemonSubstruct *substructs18 = boxMon->secure.substructs;   \
    UNUSED union VanillaPokemonSubstruct *substructs19 = boxMon->secure.substructs;   \
    UNUSED union VanillaPokemonSubstruct *substructs20 = boxMon->secure.substructs;   \
    UNUSED union VanillaPokemonSubstruct *substructs21 = boxMon->secure.substructs;   \
    UNUSED union VanillaPokemonSubstruct *substructs22 = boxMon->secure.substructs;   \
    UNUSED union VanillaPokemonSubstruct *substructs23 = boxMon->secure.substructs;   \
                                                                        \
        switch (substructType)                                          \
        {                                                               \
        case 0:                                                         \
            substruct = &substructs ## n [v1];                          \
            break;                                                      \
        case 1:                                                         \
            substruct = &substructs ## n [v2];                          \
            break;                                                      \
        case 2:                                                         \
            substruct = &substructs ## n [v3];                          \
            break;                                                      \
        case 3:                                                         \
            substruct = &substructs ## n [v4];                          \
            break;                                                      \
        }                                                               \
        break;                                                          \
    }                                                                   \


union VanillaPokemonSubstruct *Vanilla_GetSubstruct(struct VanillaBoxPokemon *boxMon, u32 personality, u8 substructType)
{
    union VanillaPokemonSubstruct *substruct = NULL;

    switch (personality % 24)
    {
        SUBSTRUCT_CASE( 0,0,1,2,3)
        SUBSTRUCT_CASE( 1,0,1,3,2)
        SUBSTRUCT_CASE( 2,0,2,1,3)
        SUBSTRUCT_CASE( 3,0,3,1,2)
        SUBSTRUCT_CASE( 4,0,2,3,1)
        SUBSTRUCT_CASE( 5,0,3,2,1)
        SUBSTRUCT_CASE( 6,1,0,2,3)
        SUBSTRUCT_CASE( 7,1,0,3,2)
        SUBSTRUCT_CASE( 8,2,0,1,3)
        SUBSTRUCT_CASE( 9,3,0,1,2)
        SUBSTRUCT_CASE(10,2,0,3,1)
        SUBSTRUCT_CASE(11,3,0,2,1)
        SUBSTRUCT_CASE(12,1,2,0,3)
        SUBSTRUCT_CASE(13,1,3,0,2)
        SUBSTRUCT_CASE(14,2,1,0,3)
        SUBSTRUCT_CASE(15,3,1,0,2)
        SUBSTRUCT_CASE(16,2,3,0,1)
        SUBSTRUCT_CASE(17,3,2,0,1)
        SUBSTRUCT_CASE(18,1,2,3,0)
        SUBSTRUCT_CASE(19,1,3,2,0)
        SUBSTRUCT_CASE(20,2,1,3,0)
        SUBSTRUCT_CASE(21,3,1,2,0)
        SUBSTRUCT_CASE(22,2,3,1,0)
        SUBSTRUCT_CASE(23,3,2,1,0)
    }

    return substruct;
}

u16 Vanilla_GetDeoxysStat(struct VanillaPokemon *mon, s32 statId)
{
    s32 ivVal, evVal;
    u16 statValue = 0;
    u8 nature;

    if (gBattleTypeFlags & BATTLE_TYPE_LINK_IN_BATTLE || Vanilla_GetMonData(mon, MON_DATA_SPECIES, NULL) != SPECIES_DEOXYS)
        return 0;

    ivVal = Vanilla_GetMonData(mon, MON_DATA_HP_IV + statId, NULL);
    evVal = Vanilla_GetMonData(mon, MON_DATA_HP_EV + statId, NULL);
    statValue = ((sVanillaDeoxysBaseStats[statId] * 2 + ivVal + evVal / 4) * mon->level) / 100 + 5;
    nature = Vanilla_GetNature(mon);
    statValue = ModifyStatByNature(nature, statValue, (u8)statId);
    return statValue;
}

u8 Vanilla_GetNature(struct VanillaPokemon *mon)
{
    return Vanilla_GetMonData(mon, MON_DATA_PERSONALITY, 0) % NUM_NATURES;
}

u32 Vanilla_GetMonData(struct VanillaPokemon *mon, s32 field, u8 *data)
{
    u32 ret;

    switch (field)
    {
    case VANILLA_MON_DATA_STATUS:
        ret = mon->status;
        break;
    case VANILLA_MON_DATA_LEVEL:
        ret = mon->level;
        break;
    case VANILLA_MON_DATA_HP:
        ret = mon->hp;
        break;
    case VANILLA_MON_DATA_MAX_HP:
        ret = mon->maxHP;
        break;
    case VANILLA_MON_DATA_ATK:
        ret = Vanilla_GetDeoxysStat(mon, STAT_ATK);
        if (!ret)
            ret = mon->attack;
        break;
    case VANILLA_MON_DATA_DEF:
        ret = Vanilla_GetDeoxysStat(mon, STAT_DEF);
        if (!ret)
            ret = mon->defense;
        break;
    case VANILLA_MON_DATA_SPEED:
        ret = Vanilla_GetDeoxysStat(mon, STAT_SPEED);
        if (!ret)
            ret = mon->speed;
        break;
    case VANILLA_MON_DATA_SPATK:
        ret = Vanilla_GetDeoxysStat(mon, STAT_SPATK);
        if (!ret)
            ret = mon->spAttack;
        break;
    case VANILLA_MON_DATA_SPDEF:
        ret = Vanilla_GetDeoxysStat(mon, STAT_SPDEF);
        if (!ret)
            ret = mon->spDefense;
        break;
    case VANILLA_MON_DATA_ATK2:
        ret = mon->attack;
        break;
    case VANILLA_MON_DATA_DEF2:
        ret = mon->defense;
        break;
    case VANILLA_MON_DATA_SPEED2:
        ret = mon->speed;
        break;
    case VANILLA_MON_DATA_SPATK2:
        ret = mon->spAttack;
        break;
    case VANILLA_MON_DATA_SPDEF2:
        ret = mon->spDefense;
        break;
    case VANILLA_MON_DATA_MAIL:
        ret = mon->mail;
        break;
    default:
        ret = Vanilla_GetBoxMonData(&mon->box, field, data);
        break;
    }
    return ret;
}

u32 Vanilla_GetBoxMonData(struct VanillaBoxPokemon *boxMon, s32 field, u8 *data)
{
    s32 i;
    u32 retVal = 0;
    struct VanillaPokemonSubstruct0 *substruct0 = NULL;
    struct VanillaPokemonSubstruct1 *substruct1 = NULL;
    struct VanillaPokemonSubstruct2 *substruct2 = NULL;
    struct VanillaPokemonSubstruct3 *substruct3 = NULL;

    // Any field greater than VANILLA_MON_DATA_ENCRYPT_SEPARATOR is encrypted and must be treated as such
    if (field > VANILLA_MON_DATA_ENCRYPT_SEPARATOR)
    {
        substruct0 = &(Vanilla_GetSubstruct(boxMon, boxMon->personality, 0)->type0);
        substruct1 = &(Vanilla_GetSubstruct(boxMon, boxMon->personality, 1)->type1);
        substruct2 = &(Vanilla_GetSubstruct(boxMon, boxMon->personality, 2)->type2);
        substruct3 = &(Vanilla_GetSubstruct(boxMon, boxMon->personality, 3)->type3);

        Vanilla_DecryptBoxMon(boxMon);

        if (Vanilla_CalculateBoxMonChecksum(boxMon) != boxMon->checksum)
        {
            boxMon->isBadEgg = TRUE;
            boxMon->isEgg = TRUE;
            substruct3->isEgg = TRUE;
        }
    }

    switch (field)
    {
    case VANILLA_MON_DATA_PERSONALITY:
        retVal = boxMon->personality;
        break;
    case VANILLA_MON_DATA_OT_ID:
        retVal = boxMon->otId;
        break;
    case VANILLA_MON_DATA_NICKNAME:
    {
        if (boxMon->isBadEgg)
        {
            for (retVal = 0;
                retVal < VANILLA_POKEMON_NAME_LENGTH && gText_BadEgg[retVal] != EOS;
                data[retVal] = gText_BadEgg[retVal], retVal++) {}

            data[retVal] = EOS;
        }
        else if (boxMon->isEgg)
        {
            StringCopy(data, gText_EggNickname);
            retVal = StringLength(data);
        }
        else if (boxMon->language == LANGUAGE_JAPANESE)
        {
            data[0] = EXT_CTRL_CODE_BEGIN;
            data[1] = EXT_CTRL_CODE_JPN;

            for (retVal = 2, i = 0;
                i < 5 && boxMon->nickname[i] != EOS;
                data[retVal] = boxMon->nickname[i], retVal++, i++) {}

            data[retVal++] = EXT_CTRL_CODE_BEGIN;
            data[retVal++] = EXT_CTRL_CODE_ENG;
            data[retVal] = EOS;
        }
        else
        {
            for (retVal = 0;
                retVal < VANILLA_POKEMON_NAME_LENGTH;
                data[retVal] = boxMon->nickname[retVal], retVal++){}

            data[retVal] = EOS;
        }
        break;
    }
    case VANILLA_MON_DATA_LANGUAGE:
        retVal = boxMon->language;
        break;
    case VANILLA_MON_DATA_SANITY_IS_BAD_EGG:
        retVal = boxMon->isBadEgg;
        break;
    case VANILLA_MON_DATA_SANITY_HAS_SPECIES:
        retVal = boxMon->hasSpecies;
        break;
    case VANILLA_MON_DATA_SANITY_IS_EGG:
        retVal = boxMon->isEgg;
        break;
    case VANILLA_MON_DATA_OT_NAME:
    {
        retVal = 0;

        while (retVal < PLAYER_NAME_LENGTH)
        {
            data[retVal] = boxMon->otName[retVal];
            retVal++;
        }

        data[retVal] = EOS;
        break;
    }
    case VANILLA_MON_DATA_MARKINGS:
        retVal = boxMon->markings;
        break;
    case VANILLA_MON_DATA_CHECKSUM:
        retVal = boxMon->checksum;
        break;
    case VANILLA_MON_DATA_ENCRYPT_SEPARATOR:
        retVal = boxMon->unknown;
        break;
    case VANILLA_MON_DATA_SPECIES:
        retVal = boxMon->isBadEgg ? SPECIES_EGG : substruct0->species;
        break;
    case VANILLA_MON_DATA_HELD_ITEM:
        retVal = substruct0->heldItem;
        break;
    case VANILLA_MON_DATA_EXP:
        retVal = substruct0->experience;
        break;
    case VANILLA_MON_DATA_PP_BONUSES:
        retVal = substruct0->ppBonuses;
        break;
    case VANILLA_MON_DATA_FRIENDSHIP:
        retVal = substruct0->friendship;
        break;
    case VANILLA_MON_DATA_MOVE1:
    case VANILLA_MON_DATA_MOVE2:
    case VANILLA_MON_DATA_MOVE3:
    case VANILLA_MON_DATA_MOVE4:
        retVal = substruct1->moves[field - VANILLA_MON_DATA_MOVE1];
        break;
    case VANILLA_MON_DATA_PP1:
    case VANILLA_MON_DATA_PP2:
    case VANILLA_MON_DATA_PP3:
    case VANILLA_MON_DATA_PP4:
        retVal = substruct1->pp[field - VANILLA_MON_DATA_PP1];
        break;
    case VANILLA_MON_DATA_HP_EV:
        retVal = substruct2->hpEV;
        break;
    case VANILLA_MON_DATA_ATK_EV:
        retVal = substruct2->attackEV;
        break;
    case VANILLA_MON_DATA_DEF_EV:
        retVal = substruct2->defenseEV;
        break;
    case VANILLA_MON_DATA_SPEED_EV:
        retVal = substruct2->speedEV;
        break;
    case VANILLA_MON_DATA_SPATK_EV:
        retVal = substruct2->spAttackEV;
        break;
    case VANILLA_MON_DATA_SPDEF_EV:
        retVal = substruct2->spDefenseEV;
        break;
    case VANILLA_MON_DATA_COOL:
        retVal = substruct2->cool;
        break;
    case VANILLA_MON_DATA_BEAUTY:
        retVal = substruct2->beauty;
        break;
    case VANILLA_MON_DATA_CUTE:
        retVal = substruct2->cute;
        break;
    case VANILLA_MON_DATA_SMART:
        retVal = substruct2->smart;
        break;
    case VANILLA_MON_DATA_TOUGH:
        retVal = substruct2->tough;
        break;
    case VANILLA_MON_DATA_SHEEN:
        retVal = substruct2->sheen;
        break;
    case VANILLA_MON_DATA_POKERUS:
        retVal = substruct3->pokerus;
        break;
    case VANILLA_MON_DATA_MET_LOCATION:
        retVal = substruct3->metLocation;
        break;
    case VANILLA_MON_DATA_MET_LEVEL:
        retVal = substruct3->metLevel;
        break;
    case VANILLA_MON_DATA_MET_GAME:
        retVal = substruct3->metGame;
        break;
    case VANILLA_MON_DATA_POKEBALL:
        retVal = substruct3->pokeball;
        break;
    case VANILLA_MON_DATA_OT_GENDER:
        retVal = substruct3->otGender;
        break;
    case VANILLA_MON_DATA_HP_IV:
        retVal = substruct3->hpIV;
        break;
    case VANILLA_MON_DATA_ATK_IV:
        retVal = substruct3->attackIV;
        break;
    case VANILLA_MON_DATA_DEF_IV:
        retVal = substruct3->defenseIV;
        break;
    case VANILLA_MON_DATA_SPEED_IV:
        retVal = substruct3->speedIV;
        break;
    case VANILLA_MON_DATA_SPATK_IV:
        retVal = substruct3->spAttackIV;
        break;
    case VANILLA_MON_DATA_SPDEF_IV:
        retVal = substruct3->spDefenseIV;
        break;
    case VANILLA_MON_DATA_IS_EGG:
        retVal = substruct3->isEgg;
        break;
    case VANILLA_MON_DATA_ABILITY_NUM:
        retVal = substruct3->abilityNum;
        break;
    case VANILLA_MON_DATA_COOL_RIBBON:
        retVal = substruct3->coolRibbon;
        break;
    case VANILLA_MON_DATA_BEAUTY_RIBBON:
        retVal = substruct3->beautyRibbon;
        break;
    case VANILLA_MON_DATA_CUTE_RIBBON:
        retVal = substruct3->cuteRibbon;
        break;
    case VANILLA_MON_DATA_SMART_RIBBON:
        retVal = substruct3->smartRibbon;
        break;
    case VANILLA_MON_DATA_TOUGH_RIBBON:
        retVal = substruct3->toughRibbon;
        break;
    case VANILLA_MON_DATA_CHAMPION_RIBBON:
        retVal = substruct3->championRibbon;
        break;
    case VANILLA_MON_DATA_WINNING_RIBBON:
        retVal = substruct3->winningRibbon;
        break;
    case VANILLA_MON_DATA_VICTORY_RIBBON:
        retVal = substruct3->victoryRibbon;
        break;
    case VANILLA_MON_DATA_ARTIST_RIBBON:
        retVal = substruct3->artistRibbon;
        break;
    case VANILLA_MON_DATA_EFFORT_RIBBON:
        retVal = substruct3->effortRibbon;
        break;
    case VANILLA_MON_DATA_MARINE_RIBBON:
        retVal = substruct3->marineRibbon;
        break;
    case VANILLA_MON_DATA_LAND_RIBBON:
        retVal = substruct3->landRibbon;
        break;
    case VANILLA_MON_DATA_SKY_RIBBON:
        retVal = substruct3->skyRibbon;
        break;
    case VANILLA_MON_DATA_COUNTRY_RIBBON:
        retVal = substruct3->countryRibbon;
        break;
    case VANILLA_MON_DATA_NATIONAL_RIBBON:
        retVal = substruct3->nationalRibbon;
        break;
    case VANILLA_MON_DATA_EARTH_RIBBON:
        retVal = substruct3->earthRibbon;
        break;
    case VANILLA_MON_DATA_WORLD_RIBBON:
        retVal = substruct3->worldRibbon;
        break;
    case VANILLA_MON_DATA_UNUSED_RIBBONS:
        retVal = substruct3->unusedRibbons;
        break;
    case VANILLA_MON_DATA_MODERN_FATEFUL_ENCOUNTER:
        retVal = substruct3->modernFatefulEncounter;
        break;
    case VANILLA_MON_DATA_SPECIES_OR_EGG:
        retVal = substruct0->species;
        if (substruct0->species && (substruct3->isEgg || boxMon->isBadEgg))
            retVal = SPECIES_EGG;
        break;
    case VANILLA_MON_DATA_IVS:
        retVal = substruct3->hpIV
              | (substruct3->attackIV << 5)
              | (substruct3->defenseIV << 10)
              | (substruct3->speedIV << 15)
              | (substruct3->spAttackIV << 20)
              | (substruct3->spDefenseIV << 25);
        break;
    case VANILLA_MON_DATA_KNOWN_MOVES:
        if (substruct0->species && !substruct3->isEgg)
        {
            u16 *moves = (u16 *)data;
            s32 i = 0;

            while (moves[i] != MOVES_COUNT)
            {
                u16 move = moves[i];
                if (substruct1->moves[0] == move
                 || substruct1->moves[1] == move
                 || substruct1->moves[2] == move
                 || substruct1->moves[3] == move)
                    retVal |= gBitTable[i];
                i++;
            }
        }
        break;
    case VANILLA_MON_DATA_RIBBON_COUNT:
        retVal = 0;
        if (substruct0->species && !substruct3->isEgg)
        {
            retVal += substruct3->coolRibbon;
            retVal += substruct3->beautyRibbon;
            retVal += substruct3->cuteRibbon;
            retVal += substruct3->smartRibbon;
            retVal += substruct3->toughRibbon;
            retVal += substruct3->championRibbon;
            retVal += substruct3->winningRibbon;
            retVal += substruct3->victoryRibbon;
            retVal += substruct3->artistRibbon;
            retVal += substruct3->effortRibbon;
            retVal += substruct3->marineRibbon;
            retVal += substruct3->landRibbon;
            retVal += substruct3->skyRibbon;
            retVal += substruct3->countryRibbon;
            retVal += substruct3->nationalRibbon;
            retVal += substruct3->earthRibbon;
            retVal += substruct3->worldRibbon;
        }
        break;
    case VANILLA_MON_DATA_RIBBONS:
        retVal = 0;
        if (substruct0->species && !substruct3->isEgg)
        {
            retVal = substruct3->championRibbon
                | (substruct3->coolRibbon << 1)
                | (substruct3->beautyRibbon << 4)
                | (substruct3->cuteRibbon << 7)
                | (substruct3->smartRibbon << 10)
                | (substruct3->toughRibbon << 13)
                | (substruct3->winningRibbon << 16)
                | (substruct3->victoryRibbon << 17)
                | (substruct3->artistRibbon << 18)
                | (substruct3->effortRibbon << 19)
                | (substruct3->marineRibbon << 20)
                | (substruct3->landRibbon << 21)
                | (substruct3->skyRibbon << 22)
                | (substruct3->countryRibbon << 23)
                | (substruct3->nationalRibbon << 24)
                | (substruct3->earthRibbon << 25)
                | (substruct3->worldRibbon << 26);
        }
        break;
    default:
        break;
    }

    if (field > VANILLA_MON_DATA_ENCRYPT_SEPARATOR)
        Vanilla_EncryptBoxMon(boxMon);

    return retVal;
}

#define SET8(lhs) (lhs) = *data
#define SET16(lhs) (lhs) = data[0] + (data[1] << 8)
#define SET32(lhs) (lhs) = data[0] + (data[1] << 8) + (data[2] << 16) + (data[3] << 24)

void Vanilla_SetMonData(struct VanillaPokemon *mon, s32 field, const void *dataArg)
{
    const u8 *data = dataArg;

    switch (field)
    {
    case VANILLA_MON_DATA_STATUS:
        SET32(mon->status);
        break;
    case VANILLA_MON_DATA_LEVEL:
        SET8(mon->level);
        break;
    case VANILLA_MON_DATA_HP:
        SET16(mon->hp);
        break;
    case VANILLA_MON_DATA_MAX_HP:
        SET16(mon->maxHP);
        break;
    case VANILLA_MON_DATA_ATK:
        SET16(mon->attack);
        break;
    case VANILLA_MON_DATA_DEF:
        SET16(mon->defense);
        break;
    case VANILLA_MON_DATA_SPEED:
        SET16(mon->speed);
        break;
    case VANILLA_MON_DATA_SPATK:
        SET16(mon->spAttack);
        break;
    case VANILLA_MON_DATA_SPDEF:
        SET16(mon->spDefense);
        break;
    case VANILLA_MON_DATA_MAIL:
        SET8(mon->mail);
        break;
    case VANILLA_MON_DATA_SPECIES_OR_EGG:
        break;
    default:
        Vanilla_SetBoxMonData(&mon->box, field, data);
        break;
    }
}

void Vanilla_SetBoxMonData(struct VanillaBoxPokemon *boxMon, s32 field, const void *dataArg)
{
    const u8 *data = dataArg;

    struct VanillaPokemonSubstruct0 *substruct0 = NULL;
    struct VanillaPokemonSubstruct1 *substruct1 = NULL;
    struct VanillaPokemonSubstruct2 *substruct2 = NULL;
    struct VanillaPokemonSubstruct3 *substruct3 = NULL;

    if (field > VANILLA_MON_DATA_ENCRYPT_SEPARATOR)
    {
        substruct0 = &(Vanilla_GetSubstruct(boxMon, boxMon->personality, 0)->type0);
        substruct1 = &(Vanilla_GetSubstruct(boxMon, boxMon->personality, 1)->type1);
        substruct2 = &(Vanilla_GetSubstruct(boxMon, boxMon->personality, 2)->type2);
        substruct3 = &(Vanilla_GetSubstruct(boxMon, boxMon->personality, 3)->type3);

        Vanilla_DecryptBoxMon(boxMon);

        if (Vanilla_CalculateBoxMonChecksum(boxMon) != boxMon->checksum)
        {
            boxMon->isBadEgg = TRUE;
            boxMon->isEgg = TRUE;
            substruct3->isEgg = TRUE;
            Vanilla_EncryptBoxMon(boxMon);
            return;
        }
    }

    switch (field)
    {
    case VANILLA_MON_DATA_PERSONALITY:
        SET32(boxMon->personality);
        break;
    case VANILLA_MON_DATA_OT_ID:
        SET32(boxMon->otId);
        break;
    case VANILLA_MON_DATA_NICKNAME:
    {
        s32 i;
        for (i = 0; i < VANILLA_POKEMON_NAME_LENGTH; i++)
            boxMon->nickname[i] = data[i];
        break;
    }
    case VANILLA_MON_DATA_LANGUAGE:
        SET8(boxMon->language);
        break;
    case VANILLA_MON_DATA_SANITY_IS_BAD_EGG:
        SET8(boxMon->isBadEgg);
        break;
    case VANILLA_MON_DATA_SANITY_HAS_SPECIES:
        SET8(boxMon->hasSpecies);
        break;
    case VANILLA_MON_DATA_SANITY_IS_EGG:
        SET8(boxMon->isEgg);
        break;
    case VANILLA_MON_DATA_OT_NAME:
    {
        s32 i;
        for (i = 0; i < PLAYER_NAME_LENGTH; i++)
            boxMon->otName[i] = data[i];
        break;
    }
    case VANILLA_MON_DATA_MARKINGS:
        SET8(boxMon->markings);
        break;
    case VANILLA_MON_DATA_CHECKSUM:
        SET16(boxMon->checksum);
        break;
    case VANILLA_MON_DATA_ENCRYPT_SEPARATOR:
        SET16(boxMon->unknown);
        break;
    case VANILLA_MON_DATA_SPECIES:
    {
        SET16(substruct0->species);
        if (substruct0->species)
            boxMon->hasSpecies = TRUE;
        else
            boxMon->hasSpecies = FALSE;
        break;
    }
    case VANILLA_MON_DATA_HELD_ITEM:
        SET16(substruct0->heldItem);
        break;
    case VANILLA_MON_DATA_EXP:
        SET32(substruct0->experience);
        break;
    case VANILLA_MON_DATA_PP_BONUSES:
        SET8(substruct0->ppBonuses);
        break;
    case VANILLA_MON_DATA_FRIENDSHIP:
        SET8(substruct0->friendship);
        break;
    case VANILLA_MON_DATA_MOVE1:
    case VANILLA_MON_DATA_MOVE2:
    case VANILLA_MON_DATA_MOVE3:
    case VANILLA_MON_DATA_MOVE4:
        SET16(substruct1->moves[field - VANILLA_MON_DATA_MOVE1]);
        break;
    case VANILLA_MON_DATA_PP1:
    case VANILLA_MON_DATA_PP2:
    case VANILLA_MON_DATA_PP3:
    case VANILLA_MON_DATA_PP4:
        if ((field - VANILLA_MON_DATA_PP1) < MAX_MON_MOVES)
            SET8(substruct1->pp[field - VANILLA_MON_DATA_PP1]);
        break;
    case VANILLA_MON_DATA_HP_EV:
        SET8(substruct2->hpEV);
        break;
    case VANILLA_MON_DATA_ATK_EV:
        SET8(substruct2->attackEV);
        break;
    case VANILLA_MON_DATA_DEF_EV:
        SET8(substruct2->defenseEV);
        break;
    case VANILLA_MON_DATA_SPEED_EV:
        SET8(substruct2->speedEV);
        break;
    case VANILLA_MON_DATA_SPATK_EV:
        SET8(substruct2->spAttackEV);
        break;
    case VANILLA_MON_DATA_SPDEF_EV:
        SET8(substruct2->spDefenseEV);
        break;
    case VANILLA_MON_DATA_COOL:
        SET8(substruct2->cool);
        break;
    case VANILLA_MON_DATA_BEAUTY:
        SET8(substruct2->beauty);
        break;
    case VANILLA_MON_DATA_CUTE:
        SET8(substruct2->cute);
        break;
    case VANILLA_MON_DATA_SMART:
        SET8(substruct2->smart);
        break;
    case VANILLA_MON_DATA_TOUGH:
        SET8(substruct2->tough);
        break;
    case VANILLA_MON_DATA_SHEEN:
        SET8(substruct2->sheen);
        break;
    case VANILLA_MON_DATA_POKERUS:
        SET8(substruct3->pokerus);
        break;
    case VANILLA_MON_DATA_MET_LOCATION:
        SET8(substruct3->metLocation);
        break;
    case VANILLA_MON_DATA_MET_LEVEL:
    {
        u8 metLevel = *data;
        substruct3->metLevel = metLevel;
        break;
    }
    case VANILLA_MON_DATA_MET_GAME:
        SET8(substruct3->metGame);
        break;
    case VANILLA_MON_DATA_POKEBALL:
    {
        u8 pokeball = *data;
        substruct3->pokeball = pokeball;
        break;
    }
    case VANILLA_MON_DATA_OT_GENDER:
        SET8(substruct3->otGender);
        break;
    case VANILLA_MON_DATA_HP_IV:
        SET8(substruct3->hpIV);
        break;
    case VANILLA_MON_DATA_ATK_IV:
        SET8(substruct3->attackIV);
        break;
    case VANILLA_MON_DATA_DEF_IV:
        SET8(substruct3->defenseIV);
        break;
    case VANILLA_MON_DATA_SPEED_IV:
        SET8(substruct3->speedIV);
        break;
    case VANILLA_MON_DATA_SPATK_IV:
        SET8(substruct3->spAttackIV);
        break;
    case VANILLA_MON_DATA_SPDEF_IV:
        SET8(substruct3->spDefenseIV);
        break;
    case VANILLA_MON_DATA_IS_EGG:
        SET8(substruct3->isEgg);
        if (substruct3->isEgg)
            boxMon->isEgg = TRUE;
        else
            boxMon->isEgg = FALSE;
        break;
    case VANILLA_MON_DATA_ABILITY_NUM:
        SET8(substruct3->abilityNum);
        break;
    case VANILLA_MON_DATA_COOL_RIBBON:
        SET8(substruct3->coolRibbon);
        break;
    case VANILLA_MON_DATA_BEAUTY_RIBBON:
        SET8(substruct3->beautyRibbon);
        break;
    case VANILLA_MON_DATA_CUTE_RIBBON:
        SET8(substruct3->cuteRibbon);
        break;
    case VANILLA_MON_DATA_SMART_RIBBON:
        SET8(substruct3->smartRibbon);
        break;
    case VANILLA_MON_DATA_TOUGH_RIBBON:
        SET8(substruct3->toughRibbon);
        break;
    case VANILLA_MON_DATA_CHAMPION_RIBBON:
        SET8(substruct3->championRibbon);
        break;
    case VANILLA_MON_DATA_WINNING_RIBBON:
        SET8(substruct3->winningRibbon);
        break;
    case VANILLA_MON_DATA_VICTORY_RIBBON:
        SET8(substruct3->victoryRibbon);
        break;
    case VANILLA_MON_DATA_ARTIST_RIBBON:
        SET8(substruct3->artistRibbon);
        break;
    case VANILLA_MON_DATA_EFFORT_RIBBON:
        SET8(substruct3->effortRibbon);
        break;
    case VANILLA_MON_DATA_MARINE_RIBBON:
        SET8(substruct3->marineRibbon);
        break;
    case VANILLA_MON_DATA_LAND_RIBBON:
        SET8(substruct3->landRibbon);
        break;
    case VANILLA_MON_DATA_SKY_RIBBON:
        SET8(substruct3->skyRibbon);
        break;
    case VANILLA_MON_DATA_COUNTRY_RIBBON:
        SET8(substruct3->countryRibbon);
        break;
    case VANILLA_MON_DATA_NATIONAL_RIBBON:
        SET8(substruct3->nationalRibbon);
        break;
    case VANILLA_MON_DATA_EARTH_RIBBON:
        SET8(substruct3->earthRibbon);
        break;
    case VANILLA_MON_DATA_WORLD_RIBBON:
        SET8(substruct3->worldRibbon);
        break;
    case VANILLA_MON_DATA_UNUSED_RIBBONS:
        SET8(substruct3->unusedRibbons);
        break;
    case VANILLA_MON_DATA_MODERN_FATEFUL_ENCOUNTER:
        SET8(substruct3->modernFatefulEncounter);
        break;
    case VANILLA_MON_DATA_IVS:
    {
        u32 ivs = data[0] | (data[1] << 8) | (data[2] << 16) | (data[3] << 24);
        substruct3->hpIV = ivs & MAX_IV_MASK;
        substruct3->attackIV = (ivs >> 5) & MAX_IV_MASK;
        substruct3->defenseIV = (ivs >> 10) & MAX_IV_MASK;
        substruct3->speedIV = (ivs >> 15) & MAX_IV_MASK;
        substruct3->spAttackIV = (ivs >> 20) & MAX_IV_MASK;
        substruct3->spDefenseIV = (ivs >> 25) & MAX_IV_MASK;
        break;
    }
    default:
        break;
    }

    if (field > VANILLA_MON_DATA_ENCRYPT_SEPARATOR)
    {
        boxMon->checksum = Vanilla_CalculateBoxMonChecksum(boxMon);
        Vanilla_EncryptBoxMon(boxMon);
    }
}

u16 Vanilla_CalculateBoxMonChecksum(struct VanillaBoxPokemon *boxMon)
{
    u16 checksum = 0;
    union VanillaPokemonSubstruct *substruct0 = Vanilla_GetSubstruct(boxMon, boxMon->personality, 0);
    union VanillaPokemonSubstruct *substruct1 = Vanilla_GetSubstruct(boxMon, boxMon->personality, 1);
    union VanillaPokemonSubstruct *substruct2 = Vanilla_GetSubstruct(boxMon, boxMon->personality, 2);
    union VanillaPokemonSubstruct *substruct3 = Vanilla_GetSubstruct(boxMon, boxMon->personality, 3);
    s32 i;

    for (i = 0; i < (s32)ARRAY_COUNT(substruct0->raw); i++)
        checksum += substruct0->raw[i];

    for (i = 0; i < (s32)ARRAY_COUNT(substruct1->raw); i++)
        checksum += substruct1->raw[i];

    for (i = 0; i < (s32)ARRAY_COUNT(substruct2->raw); i++)
        checksum += substruct2->raw[i];

    for (i = 0; i < (s32)ARRAY_COUNT(substruct3->raw); i++)
        checksum += substruct3->raw[i];

    return checksum;
}

void Vanilla_CreateMon(struct VanillaPokemon *mon, u16 vanillaSpecies, u32 level, u32 personality, u32 otId)
{
    u16 checksum;
    struct VanillaBoxPokemon *boxMon = &mon->box;

    memset(mon, 0, sizeof(*mon));
    Vanilla_SetBoxMonData(boxMon, VANILLA_MON_DATA_PERSONALITY, &personality);
    Vanilla_SetBoxMonData(boxMon, VANILLA_MON_DATA_OT_ID, &otId);

    checksum = Vanilla_CalculateBoxMonChecksum(boxMon);
    Vanilla_SetBoxMonData(boxMon, VANILLA_MON_DATA_CHECKSUM, &checksum);
    Vanilla_EncryptBoxMon(boxMon);

    Vanilla_SetMonData(mon, VANILLA_MON_DATA_SPECIES, &vanillaSpecies);
    Vanilla_SetMonData(mon, VANILLA_MON_DATA_LEVEL, &level);
}

static inline void CopyMonData(struct Pokemon *expMon, struct VanillaPokemon *vanMon, u32 fieldExp, u32 fieldVan, bool32 expToVan)
{
    if (expToVan)
    {
        u32 data = GetMonData2(expMon, fieldExp);
        Vanilla_SetMonData(vanMon, fieldVan, &data);
    }
    else
    {
        u32 data = Vanilla_GetMonData(vanMon, fieldVan, NULL);
        SetMonData(expMon, fieldExp, &data);
    }
}

static inline void CopyStrMonData(struct Pokemon *expMon, struct VanillaPokemon *vanMon, u32 fieldExp, u32 fieldVan, u8 *s, bool32 expToVan)
{
    if (expToVan)
    {
        GetMonData3(expMon, fieldExp, s);
        Vanilla_SetMonData(vanMon, fieldVan, s);
    }
    else
    {
        Vanilla_GetMonData(vanMon, fieldVan, s);
        SetMonData(expMon, fieldExp, s);
    }
}

static void CopyAllMonData(struct Pokemon *expMon, struct VanillaPokemon *vanMon, bool32 expToVan)
{
    u32 i;
    u8 text[VANILLA_POKEMON_NAME_LENGTH + TRAINER_NAME_LENGTH];

    CopyStrMonData(expMon, vanMon, MON_DATA_NICKNAME, VANILLA_MON_DATA_NICKNAME, text, expToVan);
    CopyStrMonData(expMon, vanMon, MON_DATA_OT_NAME, VANILLA_MON_DATA_OT_NAME, text, expToVan);

    CopyMonData(expMon, vanMon, MON_DATA_MAIL, VANILLA_MON_DATA_MAIL, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_OT_GENDER, VANILLA_MON_DATA_OT_GENDER, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_POKEBALL, VANILLA_MON_DATA_POKEBALL, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_MET_GAME, VANILLA_MON_DATA_MET_GAME, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_MET_LEVEL, VANILLA_MON_DATA_MET_LEVEL, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_MET_LOCATION, VANILLA_MON_DATA_MET_LOCATION, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_LANGUAGE, VANILLA_MON_DATA_LANGUAGE, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_FRIENDSHIP, VANILLA_MON_DATA_FRIENDSHIP, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_OT_GENDER, VANILLA_MON_DATA_OT_GENDER, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_IVS, VANILLA_MON_DATA_IVS, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_ATK, VANILLA_MON_DATA_ATK, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_SPATK, VANILLA_MON_DATA_SPATK, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_DEF, VANILLA_MON_DATA_DEF, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_SPDEF, VANILLA_MON_DATA_SPDEF, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_SPEED, VANILLA_MON_DATA_SPEED, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_HP, VANILLA_MON_DATA_HP, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_MAX_HP, VANILLA_MON_DATA_MAX_HP, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_ATK_EV, VANILLA_MON_DATA_ATK_EV, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_SPATK_EV, VANILLA_MON_DATA_SPATK_EV, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_DEF_EV, VANILLA_MON_DATA_DEF_EV, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_SPDEF_EV, VANILLA_MON_DATA_SPDEF_EV, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_SPEED_EV, VANILLA_MON_DATA_SPEED_EV, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_POKERUS, VANILLA_MON_DATA_POKERUS, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_ABILITY_NUM, VANILLA_MON_DATA_ABILITY_NUM, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_PP_BONUSES, VANILLA_MON_DATA_PP_BONUSES, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_HELD_ITEM, VANILLA_MON_DATA_HELD_ITEM, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_IS_EGG, VANILLA_MON_DATA_IS_EGG, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_MARKINGS, VANILLA_MON_DATA_MARKINGS, expToVan);
    CopyMonData(expMon, vanMon, MON_DATA_EXP, VANILLA_MON_DATA_EXP, expToVan);
    for (i = 0; i < MAX_MON_MOVES; i++)
    {
        CopyMonData(expMon, vanMon, MON_DATA_MOVE1 + i, VANILLA_MON_DATA_MOVE1 + i, expToVan);
        CopyMonData(expMon, vanMon, MON_DATA_PP1 + i, VANILLA_MON_DATA_PP1 + i, expToVan);
    }
}

bool32 ExpansionMonToVanillaMon(struct Pokemon *src, struct VanillaPokemon *dst)
{
    u32 speciesExpansion = GetMonData(src, MON_DATA_SPECIES_OR_EGG);
    u32 level = GetMonData(src, MON_DATA_LEVEL);
    u32 personality = GetMonData(src, MON_DATA_PERSONALITY);
    u32 otId = GetMonData(src, MON_DATA_OT_ID);

    s32 vanillaSpecies = SpeciesExpansionToVanilla(speciesExpansion);
    if (vanillaSpecies == -1)
        return FALSE;

    Vanilla_CreateMon(dst, vanillaSpecies, level, personality, otId);
    CopyAllMonData(src, dst, TRUE);
    return TRUE;
}

bool32 VanillaMonToExpansion(struct VanillaPokemon *src, struct Pokemon *dst)
{
    u32 vanillaSpecies = Vanilla_GetMonData(src, VANILLA_MON_DATA_SPECIES_OR_EGG, NULL);
    u32 level = Vanilla_GetMonData(src, VANILLA_MON_DATA_LEVEL, NULL);
    u32 personality = Vanilla_GetMonData(src, VANILLA_MON_DATA_PERSONALITY, NULL);
    u32 otId = Vanilla_GetMonData(src, VANILLA_MON_DATA_OT_ID, NULL);

    s32 speciesExpansion = SpeciesVanillaToExpansion(vanillaSpecies);
    if (speciesExpansion == -1)
        return FALSE;

    CreateMon(dst, speciesExpansion, level, 0, TRUE, personality, OT_ID_PRESET, otId);
    CopyAllMonData(dst, src, FALSE);
    return TRUE;
}
